### ISSUE TITLE
Firefox IME

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/mozilla-os2#10]
We need to integrate also IME support once it's completed by KO Myung-Hun.
His reply to my question about the diff:

Hi/2.

I'll submit the patch to bugzilla of Mozilla as soon as users confirm that it works as expected.

Then, you can get the finally approved patch here,

    https://bugzilla.mozilla.org/show_bug.cgi?id=768742

Thanks for your efforts to port FireFox 17.

**Comment by SilvanScherrer** [comment]
should we add that?

**Comment by dryeo** [comment]
It was committed to trunk and pulled when the fork was updated to 24ESR.
Issue can be closed.

**Comment by dmik** [comment]
Ok, good.
