### ISSUE TITLE
Implement ECMAScript Internationalization API

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#101]
ECMAScript Internationalization API exposed through the `Intl` namespace in JavaScript (that allows performs language sensitive string comparison and so on) was enabled in Firefox Desktop between `esr24` and `esr31`. However it has to be disabled on OS/2 because it is not yet ported. This issue is to track its porting and future enablement.

**Comment by dmik** [comment]
The original Mozilla ticket dedicated where it was done is this: https://bugzilla.mozilla.org/show_bug.cgi?id=853301. And this is the link to the `Intl` API documentaiton: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl.

**Comment by dmik** [comment]
The Intl API was disabled on OS/2 in be6a8dc54faba2b4cb31182657156f973983a69e. This commit needs to be reverted when this task is done.

**Comment by dmik** [comment]
There are two ways of implementing it (as usual):

  1. Enable building of the the Firefox in-tree copy (`intl/isu/source`) which is imported from http://source.icu-project.org/repos/icu/icu/tags/release-52-1.
  2. Host a separate OS/2 port of ICU at http://trac.netlabs.org/ports/ and use it from Firefox as a system DLL.

I vote for option 2 as it will allow to reuse ICU from other applications (it's actually quite a nice library, see http://site.icu-project.org).

**Comment by ydario** [comment]
ICU is already ported to OS/2 and available as rpm. 4.2 is current available version.

**Comment by dmik** [comment]
@ydario yes, but Mozilla needs version 50.1 and up. And besides, it expects `pkgconfig` for it which is missing from your RPMs. So I will ry to built the latest one (56.1) using your patches.

**Comment by dmik** [comment]
I ported ICU 56.1 to OS/2 and built it. Then re-enablied INTL on OS/2 and rebuilt Mozilla with `--with-system-icu` and the `Intl` JS module is now there. I will leave this issue open until I create an ICU SVN in http://trac.netlabs.org/ports and commit my patches there.

I also want to give ICU some more testing (run its internal tests etc) before finally enabling it in Mozilla.

**Comment by dmik** [comment]
I created a repository for ICU (http://trac.netlabs.org/ports/log/icu) and created RPMs today and tried to build Firefox with the released packages. It seems to work well. So I will revert be6a8dc now.
