### ISSUE TITLE
plugin-container.exe gives 100% CPU load

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#106]
In ESR31, `plugin-container.exe` (responsible for out-of-process plugin functionality) gives us as many troubles as in ESR24 it seems. In many cases the only solution is to `kill -9` both plugin-container.exe and firefox.exe to get the CPU back. This finally needs some attention.

Note that using of `plugin-container.exe` (and of OOP) may be disabled globally by setting the `dom.ipc.plugins.enabled` property to `false` or per-plugin by setting `dom.ipc.plugins.enabled.<plugin_dll_name>` to `false`.

Note however that in ESR31 `plugin-container.exe` sometimes gets started anyway, even when IPC is disabled as described above. There is #105 to deal with that problem.

This defect is a the source of problems described in #47 and #28 as well (which I will close in favor of this one).

**NB**. When this issue is resolved, we need to revert bc58af1f7ed39cf84ddb7cccd3ec84660e309895 as well as 8569cbde4a68d05da93ba1b31a955391ecf120a7.

**Comment by dmik** [comment]
As it is mentioned in some other issues, the hang of `plugin-container.exe` is caused by a non-working communication between Firefox and this container process. The IPC communication is implemented using parts of the chromium library (that use local sockets( and sometimes the channel just screws up giving this 100% CPU load. See #20 and #7 that provide a lot of details about IPC and plugins.

**Comment by dmik** [comment]
As a temporary workaround, I completely disabled IPC for plugins for now in 8569cbde4a68d05da93ba1b31a955391ecf120a7. Note #105 though.

**Comment by dmik** [comment]
Note that when this is fixed, we should enable `PROXY_PRINTING` in `embedding/components/builld/moz.build` (similarly to Windows) to protect taking down the browser by crashes in printing (like #75).

**Comment by lerdmann** [comment]
Hallo dmik,

As I experienced the same prob I disabled all add-ons and restarted Firefox again and again, each time with one additional add-on reenabled.

It now turns out that "HTTPS Everywhere 5.1.2" is the culprit.
If I have it disabled, I don't see this issue, if I enable it, I run into the above mentioned problem. This is even true if an "internal" webpage like about:addons is displayed in Firefox.

Now, I don't blame Firefox for this error but we would need to find out how an add-on executes within the Firefox application process and we would need to think about how an add-on can be prevented from monopolizing the whole application process. 

I can confirm that I have set "dom.ipc.plugins.enabled" to FALSE.
Is plugin-container.exe still started anyway ?

Lars

**Comment by dryeo** [comment]
On 02/14/16 03:50 AM, lerdmann wrote:
> I can confirm that I have set "dom.ipc.plugins.enabled" to FALSE.
> Is plugin-container.exe still started anyway ?

Use Top to check if plugin-container.exe is loaded though I think your 
issue is different.

**Comment by lerdmann** [comment]
I checked. For me plugin-container.exe is NOT loaded.
It has to do with the add-ins that are loaded. To me it looks like they 
can monopolize the whole process which they should not.

**Comment by dmik** [comment]
The problems mentioned in this ticked may be caused by `pipe()` that was used by libevent used in turn for IPC communication in Mozilla. GCC `pipe()` creates native OS/2 file handles not compatible with `select()` which usually gives 100% CPU load because `select()` aborts with EINVAL (22) and then starts over in an infinite loop. With `pipe()` disabled in 84b282cac4a164c518c36a07cd833c04c57735a2 `socketpair()` gets used instead which is perfectly fine for us.

This issue should be re-evaluated once ESR 45 is released.

**Comment by dmik** [comment]
It doesn't seem that the above commit fixed the problem, see https://github.com/bitwiseworks/mozilla-os2/issues/199#issuecomment-297195498. And here is the log from that comment relevant to this issue:
```
[warn] select: Bad file number
[warn] select: Bad file number
[NPAPI 78] WARNING: pipe error: Broken pipe: file D:/Coding/mozilla/master/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 772
[warn] select: Bad file number
[warn] select: Bad file number
```

**Comment by dmik** [comment]
BTW, plugin-container.exe seems to be part of what they call e10s or Electrolysis. Electrolysis is described here in detail: https://wiki.mozilla.org/Electrolysis. This may give some hints.

**Comment by lerdmann** [comment]
Here are some very wild and rudimentary thoughts about this:
1) maybe the data exchange between threads requires a memory address that is the very same address in all threads but points to thread specific memory. In that case, make sure that such memory is allocated via DosAllocThreadLocalMemory.
2) OS/2 presentation manager prohibits creating a window in one thread and destroying it in another thread or even creating it in one process and destroying it in another process (see "WinDestroyWindow" help). If that is necessary, a workaround would be needed that,on window destruction for example, calls back into the process and thread that initially created the window and have the initial thread destroy the window. There might be further PM limitations.
3) if a pointer is passed via WinSendMsg to another process (a window in another process), then it is not guaranteed that the receiving window will be able to access that memory. That would require to allocate shared memory with the GETTABLE attribute (or named shared memory). I guess the same would hold true for WinPostMsg.
4) there are multiple things to consider regarding Drag and Drop between different processes. But I guess that does not apply to this problem.

**Comment by dmik** [comment]
Got another 100% reproducible (here) case of the problem. Just go to yonder.ru and wait a bit, you will get plugin-container.exe started and a 100% CPU load.

A hardcore workaround to it is to just remove plugin-container.exe from the Firefox directory. No side effects of this is seen in my test runs so I will go this way in the upcoming RPM release of Firefox.

**Comment by dmik** [comment]
Surprise-surprise, this is a regression of ESR 31 or so. At least in that part where `[warn] select: Bad file number` messages are spit out. I fixed it once back in 2013 (see 82e92bff30d8f1d32fcab7e0555f452b8efd4845) using the chromium's `OS_OS2` macro for OS/2 specific code. However they dropped chromium defines from a libevent build later so OS/2 code was inactive. Changing this to `__OS2__` fixes the problem. A commit will follow.

This doesn't fix the problem completely though. No more `select` hangs but either the parent or the child is still spinning in some tight loop when doing IPC. Sometimes I see this:
```
###!!! [Parent][MessageChannel::Call] Error: Channel error: cannot send/recv
```
coming from `ipc/glue/MessageChannel.cpp`. I need better understanding of libevent and mozilla IPC internals in order to sort this out. Libevent uses `sendmsg/recvmsg` for message exchange instead of plain read/write, maybe there is some problem with those. I already fixed a couple of glitches there in 2013, see 6e59cbba020c5ea60ae1d924463f97377608935d and 1042a817a383553857d49972fcfbd6d9994f8c8d. May be these went out of alignment too somehow.

**Comment by dmik** [comment]
Ok, it's more or less clear why we get 100% CPU load involving `plugin-container.exe`. It's because OS/2 doesn't seem to support the SCM_RIGHTS messages in particular and ancillary data fields of `msghdr` in general when doing `sendmsg/recvmsg`, at least not for local sockets. (The TCP/IP Version 4.21 Programming Reference clearly states: ```The fields msg_control and msg_controllen are ignored for the NetBIOS and Local IPC domains.```).

The SCM_RIGHTS message type allows to pass open file descriptors between two unrelated processes and this functionality is obviously missing in OS/2. The missing SCM_RIGHTS support looks like this. In chromium code, the `sendmsg` party (parent process) initializes `msghdr.msg_control` to NULL and `msghdr.msg_controllen` to 0 (as there are no file descriptors to pass). The `recvmsg` party (the child process) initializes these fields to a buffer big enough to receive all control data (as required by the API). However, `recvmsg` on OS/2 does **not** reset the length field to the actual number of control bytes (0 in this case) leaving it as it was before the call.

Further chromium code thinks that some control data was passed, tries to walk through all `cmsg` structures but since the buffer contains zeroes instead of real data. This makes this walk an endless loop and hence 100% CPU load.

I faced this SCM_RIGHTS problem already in the past and disabled code using it back in 2013, see https://github.com/bitwiseworks/mozilla-os2/issues/20#issuecomment-29312893. And there is even #42 which is about to provide a replacement for the missing SCM_RIGHTS functionality as it's sometimes needed by Firefox. But some of the further upstream updates seems to have enabled SCM_RIGHTS again on OS/2 and brought the 100% CPU load back.

**Comment by dmik** [comment]
Next, if I disable SCM_RIGHTS usage again, the 100% CPU hang problem goes away, the browser continues to function (at least visually), but IPC doesn't seem to work correctly. I see errors like these (with `export NSPR_LOG_MODULES=chromium:9`):
```
0[33e0a9e0]: D:/Coding/mozilla/master/ipc/chromium/src/chrome/common/ipc_channel_posix.cc:489: pipe error (3): Bad file number
[134] WARNING: pipe error (3): Bad file number: file D:/Coding/mozilla/master/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 489
[NPAPI 140] WARNING: pipe error: Broken pipe: file D:/Coding/mozilla/master/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 800
[NPAPI 140] ###!!! ABORT: Aborting on channel error.: file D:/Coding/mozilla/master/ipc/glue/MessageChannel.cpp, line 1861
[NPAPI 140] ###!!! ABORT: Aborting on channel error.: file D:/Coding/mozilla/master/ipc/glue/MessageChannel.cpp, line 1861
```
Note that the code doesn't try to pass file descriptors in this particular run so no missing SCM_RIGHTS  support is involved here. Looks like `plugin-container.exe` unexpectedly terminates for some reason and it causes `Bad file descriptor` in the parent Firefox process.

**Comment by dmik** [comment]
Rebuilding `plugin-container.exe` seems to fix unexpected termination. Also, adding some more logging reveals that it gets started to execute the Flash plugin (I have it in MOZ_PLUG here). It seems to work but when it comes to doing some real painting I see this:
```
IPDL protocol error: Handler for CreateChildPluginWindow returned error code

###!!! [Child][DispatchInterruptMessage] Error: (msgtype=0xAA0003,name=PPluginInstance::Msg_CreateChildPluginWindow) Processing error: message was deserialized, but the handler returned false (indicating failure)
```
Perhaps, some interprocess window access failure or such.

**Comment by dmik** [comment]
It also seems that `dom.ipc.plugins.enabled` (which we set to false in 8569cbde4a68d05da93ba1b31a955391ecf120a7 ) is not used any more and that's why it started using it again after some ESR upstream update.

**Comment by dryeo** [comment]
Issue #225 may be related, especially the crash in nspr

**Comment by komh** [comment]
@dmik I appreciate your hard work. I've always learned from your great analysis and solution. Thanks!

**Comment by dmik** [comment]
@komh thank you! I'm glad to know that.

**Comment by an64** [comment]
Sorry for bothering you, will plugins work 
As i understood - only while all issues with ipc will be fixed?

**Comment by AndiB-2** [comment]
I've to second komh. Dmitriys constant progress reports helps others to learn about various aspects of FF. But also how to deal with various other shortcomings of our system. Keep up your work and your postings. Thanks.

**Comment by dmik** [comment]
@AndiB-2 thanks!
@an64 This defect is essentially about to make plugins finally work. And yes, they will only work when all critical IPC issues are fixed.
@dryeo good, I will perhaps use it as a test case as this plugin is very simple and doesn't involve complex cases involving passing an open stream (file handle) from one process to another.

**Comment by dmik** [comment]
Research has shown that in-process plugin support was completely removed in around FF 43, this is the respective bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1194780. This is one of the patches removing the major part including `dom.ipc.plugins.enabled` preference support: https://hg.mozilla.org/releases/mozilla-esr45/rev/32e5b68506f4 (note that the bug number in the ticket is wrong).

I'm pretty sure that restoring such a support is a bad idea (many reasons). So the only way is to fix IPC. I will remove the respective preference overrides.

**Comment by dmik** [comment]
Hmm, no need to 8569cbde4a68d05da93ba1b31a955391ecf120a7 as this was already reverted (by me, manually) when merging ESR 45 changes in.

**Comment by dmik** [comment]
Short update. SCM_RIGHTS is surely a dead end — double checked it. The OS/2 TCP/IP stack completely ignores control message fields. With SCM_RIGHTS disabled, I see that sometimes (pretty rarely) the first plugin-container.exe invocation fails for an unknown reason (no crash, just unexpected exit) and FF starts a new process which seems to work then. I've added extra logging to see what's going on so I can tell more if it happens again. The problem is most likely the initial handshake between the parent and the started child done in `GMPProcessChild::Init()` (this goes really deep down to `ProcessLink::Open` via `MessageChannel::Open`, quite complex logic).

I'm trying the AWGet plugin now within #225 to see if it all works or not.

**Comment by dmik** [comment]
Note that the above commit fixes 100% CPU load during IPC so that even if the plugin doesn't work properly, it at least doesn't hang the browser. While I couldn't make the Awget plugin work, it seems to be unrelated to IPC (see #225 for more info) and IPC itself seems to work well with SCM_RIGHTS disabled. The failed `plugin-container.exe` invocation mentioned above turns out to be a child process killed by the parent process after a timeout (see #225), so not an issue.

Also note the error from https://github.com/bitwiseworks/mozilla-os2/issues/106#issuecomment-310791304 when using the Flash plugin has gone with aaeb27a52333a1f9e8c2007c2ec03d3c63937ff5. IPC in Flash appears to work but just leaves the plugin area completely black (it also reacts to mouse clicks, according to IPC logs). This is to be further addressed in #43.

I'm going to try out a few other plugins to see if there are any IPC specific issues (besides the one tracked by #42) before deciding on closing this one.

**Comment by dmik** [comment]
The AWget plugin problem is solved within #225 by replacing `DosWaitEventSem` with `WinWaitEventSem` in NSPR (see also http://trac.netlabs.org/ports/ticket/166). This means that IPC generally works on OS/2 now so we are about to close this issue.

The NPFLOS2.DLL plugin (Flash) still doesn't work, however it doesn't complain about a `CreateChildPluginWindow` failure as it did when IPC was broken. It still continues to show a black rectangle and reacts to mouse clicks. Again this may be not related to IPC any more but to our Win32 plugin wrapper not compatible with OOP or such. It needs some more investigation and then I will decide if it deserves a new issue.

The NPDJVU.DLL plugin also loads but it doesn't work properly for some reason — crashes somewhere in NPDJVU.DLL. It's known that not all plugins are compatible with OOP mode and old plugins crash on other platforms too. We should update it to make it work if we really care. Anyway, a separate topic as well.

**Comment by dmik** [comment]
Given that both NPFLOS2.DLL and NPDJVU.DLL work if I make `nsNPAPIPlugin::RunPluginOOP` return  `false` on OS/2, we should think what to do with them:

1. We deprecate all plugins incompatible with OOP completely and work on plugins in order to make them work with FF in OOP mode. This is a good choice as it increases stability of the browser.
2. We provide some compatibility environment variable that, when set, makes listed plugins run in old in-process mode. The stability will degrade but the users will be able to use old crappy plugins if they wish.

Of course, we may combine two ways by supporting such a compatibility environment variable but set it to nothing by default (i.e. force OOP for all plugins). This will, however, most likely result in all systems having this variable set and nobody caring about making crappy plugins work nice in OOP.

I will let us to have some discussion on that and fix NSPR in the mean time (and also try to gather some more details about why Flash doesn't work in OOP mode).

**Comment by dmik** [comment]
Also, given that both NPFLOS2.DLL and NPDJVU.DLL do some painting, it's possible that IPC itself works now but painting over IPC still doesn't. And this may involve #42.

**Comment by dmik** [comment]
Given that we have #228 and #229, this issue may be closed as IPC generally works now according to my numerous tests and `plugin-container.exe` doesn't give 100% CPU load any more even with OOP enabled. All further edge cases (if any, not known ATM) are to be resolved in separate issues.
