### ISSUE TITLE
Update Firefox 31 ESR

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/mozilla-os2#109]
update the current firefox 31 ESR to 31.8 ESR release.

**Comment by dryeo** [comment]
ESR31.8 (along with ESR38.2 and regular release 39) have been delayed 
for at least a couple of days, so no release as planned today.

**Comment by wztest** [comment]
Whats the problem? We just need 31.x for the moment.

**Comment by dmik** [comment]
It makes no sense to release 31.6 when there is 31.8 already available. Updating a minor release is usually quick and easy.

**Comment by dryeo** [comment]
Mozilla has made FF 31.8.0 available for download.

**Comment by wztest** [comment]
That's nice, source should be ready to merge or update the current branch.

**Comment by dmik** [comment]
I successfully merged 31.8.0 to `master` in 19dd4da3bab561344bbc571e7e55cbcd5843885d, it had only a few conflicts. Will now try to build it. I didn't spot any huge changes in platform-dependent parts so far, so I hope it will work. They added some new stuff to the chromium IPC code but that shouldn't affect us at all at the moment as IPC is currently disabled.

**Comment by dmik** [comment]
Another thing to mention that there was a change in `toolkit/mozapps/installer/packager.mk` (parts of which migrated to `upload-files.mk`). I tried to adapt it to OS/2 on the fly but this needs testing.

**Comment by dmik** [comment]
The build is ready and seems to work just as 31.6 did so far. I also fixed a small merge glitch related to packaging in 8c76b3451d40973c876f063296f69dff37ad3431. This task appears to be done, closing.
