### ISSUE TITLE
Google Docs still eats all shared mem frequently

### ISSUE THREAD

**Issue by herwigb** [bitwiseworks/mozilla-os2#111]
Using (especially) Google Sheets still results in FF eating up all shared mem after some time. Reloading the same Google Docs upon restart doesn't show the same behaviour immediately - however after some work and/or opening another sheet it happens again. This is easily reproducible.

**Comment by dmik** [comment]
Herwig, I guess this falls into #55 so I'm closing this one. Thanks for reporting anyway.
