### ISSUE TITLE
Shumway worked on on FF24 but not on FF31

### ISSUE THREAD

**Issue by herwigb** [bitwiseworks/mozilla-os2#112]
FF Extension Shumway http://mozilla.github.io/shumway/ (Mozilla "Flash Plugin" based upon JavaScript and HTML5) worked nicely on YouTube (and some, but not all other Flash sites) with our FF24.

On FF31.A1, the video is played, however there is no picture.

**Comment by dmik** [comment]
@herwigb I installed this add-on in FF31 and it seems to work — at least the SWF test files it provides work well (except some of the AS3 examples though). However, I don't know how to activate it on YouTube — HTML5 always takes over. If you can give me a direct link to an SWF movie I will check.

And, BTW, I tried to install this extension in FF24 beta 4 (a clean profile) and I must say it doesn't work at all there. None of the examples work. So I wonder how you made it work there — some special settings? Or maybe somehow it's our Flash DLL that handles this on FF24 for you?

**Comment by dmik** [comment]
Hmm, after restarting FF31 I must say that all AS3 examples now work too. Looks like they require some longer time to initialize than AS2 content. Still unclear about how to activate it on YouTube.

**Comment by herwigb** [comment]
Strange, I cannot reproduce the problem anymore on FF31.A1 
I didn't do all the stuff on a cleam profile however...
