### ISSUE TITLE
Wrong downloaded file name

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#114]
It turns out that if the name of the downloaded file contanis characters outside of the ASCII table, two files get created in the Downloads folder:

![2015-07-07 16 13 35](https://cloud.githubusercontent.com/assets/900726/8546811/263073ee-24c3-11e5-8bc2-be31b79421b1.png)

The first one has the correct file name, but its size is 0. The second one has the correct size (and contents) but its name looks like a raw UTF-8 string not converted to the local charset.

This happens in particular if you download an attached file from the gmail interface.

**Comment by dmik** [comment]
I think I know what's wrong here. The new Downloader manager uses the `osfile` component which on OS/2 uses posix (libc) for file operations. But while the code assumes that on Unix posix works in UTF-8 mode and supplies it with UTF-8 strings, on OS/2 this is not true. I need to check how we can convert strings passed to `osfile` to a local charset.

**Comment by dmik** [comment]
In the JS-ctypes bridge (`js/src/ctypes`) they provide a callback to convert from a JS string to a local charset for the path name but it is only used in the library object deals with importing C functions from DLLs into JS using libffi — a DLL name is converted before passing it to `PR_LoadLibraryWithFlags` using this callback.

It is strange that they didn't provide the same mechanism to pass path strings to C functions imported from e.g. `libc`. This looks like a design flaw to me and seems to work only because most (all?) *nix based systems have uff-8 by default.

There should be a way to introduce a new type for paths and setup a hook that will convert the string before passing it to `libc` from JS. This is extremely important as more and more components migrate to `osfile`.

**Comment by dmik** [comment]
For instance, many files in the profile directory are now accessed through `osfile` and if the profile directory ever happens to be located in a directory containing non-ASCII characters, this will effectively kill Mozilla functionality because the files will be created in a completely different directory (due to UTF-8 representation instead of the local charset).

Luckily, I found a place where this conversion happens (in `CTypes.cpp`). Indeed, the code assumes that all C single byte strings are in UTF-8. On Windows this code only works because `osfile` uses widechar (Unicode) API there (which maps directly to Unicode jschar used in JS). It will take some time to add conversion in these bits.

**Comment by dmik** [comment]
Okay, I have fixed conversion of input strings when passing them from JS to `libc` via `ctypes`. Downloading now works perfectly, preserving the native file name correctly. See affe4be76621ca9930608952c5bd937cff68039b for details.

However, I found that there is also a need to convert the strings passed from`libc` back to JS. It's little bit more complex as requires an extension to the callbacks list in the JS-ctypes bridge (to add a function that converts from the native charset to Unicode).

**Comment by dmik** [comment]
Fixed the output string conversion as well, see above. Also, in 6d0725893193754b296a854d305dd5a50b67df61 I corrected the wrong code that detects the length of the native string.

**Comment by ydario** [comment]
It happens again in ff38 test builds.

**Comment by dmik** [comment]
Clarification: between 31esr and 38esr, they added a notion of 8-bit latin strings to `JSString` and friends in addition to its native two-byte internal representation. This looks like an optimization, to avoid conversion for two-byte strings not actually using national characters (besides latin1) when passing them between JS and native platform C code. Unfortunately, OS/2 uses cp850 for Latin locales, not ISO/IEC 8859-1 as on other platforms. This is still strange though since I don't understand how this can work on platforms using UTF8 natively (as Latin1 isn't compatible with UTF8).
 
The respective CTypes change is this: https://bugzilla.mozilla.org/show_bug.cgi?id=1029622

**Comment by dmik** [comment]
The problem was brought by merging with 38esr. The original code didn't perform encoding in CTypes in the first place so there was no issues there. The original idea behind having a Latin1 storage in JSString was to optimize for ASCII strings but in fact they went further to Latin1 (iso-8859-1). The reason is that because iso-8859-1 fully matches the Unicode range 0x0000-0x00FF, so Latin1 strings can be very easily converted to/from two-byte Unicode (by adding/removing the high 0x00 part). The code I added to CTypes to fix JS encodings on OS/2 in the first place (see above) was treating Latin1 strings as if they were ASCII and hence didn't perform any charset conversion (to cp850 for instance). Now it's fixed by the above commit.
