### ISSUE TITLE
ESR 31.8 build issues

### ISSUE THREAD

**Issue by abwillis** [bitwiseworks/mozilla-os2#116]
When building 31.8 via the client.mk there are problems similar to the issues in #52 and #82:
Index: security/nss/coreconf/rules.mk
===================================================================
--- security/nss/coreconf/rules.mk	(revision 412)
+++ security/nss/coreconf/rules.mk	(working copy)
@@ -200,10 +200,10 @@
 # Substitute \$ for $ so the shell doesn't choke
 ifdef BUILD_OPT
 release_classes::
-	$(INSTALL) -m 444 $(subst $$,\$$,$(RELEASE_FILES)) $(SOURCE_RELEASE_PREFIX)/$(SOURCE_RELEASE_CLASSES_DIR)/$(PACKAGE)
+	$(INSTALL) -m 644 $(subst $$,\$$,$(RELEASE_FILES)) $(SOURCE_RELEASE_PREFIX)/$(SOURCE_RELEASE_CLASSES_DIR)/$(PACKAGE)
 else
 release_classes::
-	$(INSTALL) -m 444 $(subst $$,\$$,$(RELEASE_DBG_FILES)) $(SOURCE_RELEASE_PREFIX)/$(SOURCE_RELEASE_CLASSES_DBG_DIR)/$(PACKAGE)
+	$(INSTALL) -m 644 $(subst $$,\$$,$(RELEASE_DBG_FILES)) $(SOURCE_RELEASE_PREFIX)/$(SOURCE_RELEASE_CLASSES_DBG_DIR)/$(PACKAGE)
 endif
 
 endif
@@ -231,7 +231,7 @@
 
 release_md::
 ifneq ($(MD_LIB_RELEASE_FILES),)
-	$(INSTALL) -m 444 $(MD_LIB_RELEASE_FILES) $(SOURCE_RELEASE_PREFIX)/$(SOURCE_RELEASE_LIB_DIR)
+	$(INSTALL) -m 644 $(MD_LIB_RELEASE_FILES) $(SOURCE_RELEASE_PREFIX)/$(SOURCE_RELEASE_LIB_DIR)
 endif
 ifneq ($(MD_BIN_RELEASE_FILES),)
 	$(INSTALL) -m 555 $(MD_BIN_RELEASE_FILES) $(SOURCE_RELEASE_PREFIX)/$(SOURCE_RELEASE_BIN_DIR)
@@ -725,7 +725,7 @@
 # problem because the source isn't in the current directory:
 #
 export:: $(JMC_EXPORT_FILES) $(JMCSRCDIR)
-	$(NSINSTALL) -t -m 444 $(JMC_EXPORT_FILES) $(JMCSRCDIR)
+	$(NSINSTALL) -t -m 644 $(JMC_EXPORT_FILES) $(JMCSRCDIR)
 endif
 
 #
@@ -769,7 +769,7 @@
 export:: $(PUBLIC_EXPORT_DIR) 
 
 export:: $(EXPORTS) 
-	$(INSTALL) -m 444 $^ $(PUBLIC_EXPORT_DIR)
+	$(INSTALL) -m 644 $^ $(PUBLIC_EXPORT_DIR)
 
 export:: $(BUILT_SRCS)
 endif
@@ -788,7 +788,7 @@
 private_export:: $(PRIVATE_EXPORT_DIR)
 
 private_export:: $(PRIVATE_EXPORTS) 
-	$(INSTALL) -m 444 $^ $(PRIVATE_EXPORT_DIR)
+	$(INSTALL) -m 644 $^ $(PRIVATE_EXPORT_DIR)
 else
 private_export:: 
 	@echo There are no private exports.;
@@ -839,7 +839,7 @@
 release_export:: $(SOURCE_RELEASE_XP_DIR)/include
 
 release_export:: $(EXPORTS)
-	$(INSTALL) -m 444 $^ $(SOURCE_RELEASE_XP_DIR)/include
+	$(INSTALL) -m 644 $^ $(SOURCE_RELEASE_XP_DIR)/include
 endif
 
 
Index: nsprpub/pr/include/md/Makefile.in
===================================================================
--- nsprpub/pr/include/md/Makefile.in	(revision 412)
+++ nsprpub/pr/include/md/Makefile.in	(working copy)
@@ -19,8 +19,8 @@
 include $(topsrcdir)/config/rules.mk
 
 export:: $(MDCPUCFG_H)
-	$(INSTALL) -m 444 $(CONFIGS) $(dist_includedir)/md
-	$(INSTALL) -m 444 $(srcdir)/$(MDCPUCFG_H) $(dist_includedir)
+	$(INSTALL) -m 644 $(CONFIGS) $(dist_includedir)/md
+	$(INSTALL) -m 644 $(srcdir)/$(MDCPUCFG_H) $(dist_includedir)
 	mv -f $(dist_includedir)/$(MDCPUCFG_H) $(dist_includedir)/prcpucfg.h
 
 install::
Index: nsprpub/lib/libc/src/Makefile.in
===================================================================
--- nsprpub/lib/libc/src/Makefile.in	(revision 412)
+++ nsprpub/lib/libc/src/Makefile.in	(working copy)
@@ -141,16 +141,16 @@
 #
 
 export:: $(TARGETS)
-	$(INSTALL) -m 444 $(TARGETS) $(dist_libdir)
+	$(INSTALL) -m 644 $(TARGETS) $(dist_libdir)
 ifdef SHARED_LIBRARY
 ifeq ($(OS_ARCH),HP-UX)
 	$(INSTALL) -m 755 $(SHARED_LIBRARY) $(dist_libdir)
 	$(INSTALL) -m 755 $(SHARED_LIBRARY) $(dist_bindir)
 else
-	$(INSTALL) -m 444 $(SHARED_LIBRARY) $(dist_bindir)
+	$(INSTALL) -m 644 $(SHARED_LIBRARY) $(dist_bindir)
 ifdef DEBUG_SYMFILE
-	$(INSTALL) -m 444 $(call DEBUG_SYMFILE,$(SHARED_LIBRARY)) $(dist_libdir)
-	$(INSTALL) -m 444 $(call DEBUG_SYMFILE,$(SHARED_LIBRARY)) $(dist_bindir)
+	$(INSTALL) -m 644 $(call DEBUG_SYMFILE,$(SHARED_LIBRARY)) $(dist_libdir)
+	$(INSTALL) -m 644 $(call DEBUG_SYMFILE,$(SHARED_LIBRARY)) $(dist_bindir)
 endif
 endif
 endif

**Comment by abwillis** [comment]
Running:
make -f client.mk
kicks off the build until it fails (with the above, otherwise it fails quickly):
 emxomfar r plc4_s.lib ./plvrsion.o ./strlen.o ./strcpy.o ./strdup.o ./strcase.o
 ./strcat.o ./strcmp.o ./strchr.o ./strpbrk.o ./strstr.o ./strtok.o ./base64.o ./
 plerror.o ./plgetopt.o
 Creating library file `plc4_s.lib'
 echo.exe plc4_s.lib
 plc4_s.lib
 ../../../config/./nsinstall -m 644 ./plc4_s.lib E:/svncode/mozilla/ffobj/dist/lib
 make.exe[9]: Leaving directory `E:/svncode/mozilla/ffobj/nsprpub/lib/libc/src'
 make.exe[8]: Leaving directory `E:/svncode/mozilla/ffobj/nsprpub/lib/libc'
 make.exe[7]: Leaving directory `E:/svncode/mozilla/ffobj/nsprpub/lib'
 make.exe[6]: Leaving directory `E:/svncode/mozilla/ffobj/nsprpub'
 make.exe[5]: Leaving directory `E:/svncode/mozilla/ffobj/config/nspr'
 make.exe[4]: Leaving directory `E:/svncode/mozilla/ffobj'
 make.exe[3]: *** [export] Error 2
 make.exe[3]: Leaving directory `E:/svncode/mozilla/ffobj'
 make.exe[2]: *** [default] Error 2
 make.exe[2]: Leaving directory `E:/svncode/mozilla/ffobj'
 make.exe[1]: *** [realbuild] Error 2
 make.exe[1]: Leaving directory `E:/svncode/mozilla'
 make.exe: *** [build] Error 2 

I do not see what failed and if I go to the objdir and run make it then builds fine until right at the end:
weakld: error: Unresolved symbol (UNDEF) '__ZN7mozilla23AudioQueueMemoryFunctor1
2MallocSizeOfEPKv'.
weakld: info: The symbol is referenced by:
    E:\svncode\mozilla\ffobj\content\media\MediaDecoderReader.o 

Which again I don't really understand.
http://mxr.mozilla.org/mozilla-esr31/search?string=QueueMemoryFunctor
Shows that there are 3 Audio and 3 Video QueueMemoryFunctor lines.  The Audio and Video ones look the same from what I can see but the Video ones are fine but for some reason the Audio doesn't create correctly.  Tried ac_add_options --disable-fmp4 at Dave Yeo's suggestion but same issue.

**Comment by dryeo** [comment]
Have you tried building by running ../configure && make from the obj 
directory?

**Comment by dmik** [comment]
@abwillis have you tried a direct build, as described here: https://github.com/bitwiseworks/mozilla-os2/wiki/Developers? I use it myself as it's more convenient for me.

**Comment by abwillis** [comment]
Building now, blasted builds take forever it seems now.  I had about 4 of 6 hours done when I tried to run a script to check something else and got a trap 8.  I used to build on a T42 with a P3 and it didn't take as long as this W500 with dual core, the code has really bloated.

**Comment by dmik** [comment]
Yes, they really have too much of everything now.

**Comment by abwillis** [comment]
I get these randomly too, if I go into the failing module and do make it will give the same error but a make clean followed by a make will then go clean:
emxomf: Cannot read input file `E:\svncode\mozilla\ffobj\layout\base\ActiveLayer
Tracker.o'
emxomfld: a.out to omf conversion failed for 'E:\svncode\mozilla\ffobj\layout\ba
se\ActiveLayerTracker.o'.
make.exe[3]: *** [xul.dll] Error 1
make.exe[3]: Leaving directory `E:/svncode/mozilla/ffobj/toolkit/library/build'
make.exe[2]: *** [toolkit/library/build/libs] Error 2
make.exe[2]: Leaving directory `E:/svncode/mozilla/ffobj'
make.exe[1]: *** [libs] Error 2
make.exe[1]: Leaving directory `E:/svncode/mozilla/ffobj'
make.exe: *** [default] Error 2

**Comment by abwillis** [comment]
Did the make in E:\svncode\mozilla\ffobj\layout\base and sure enough, same error when doing make in 
E:/svncode/mozilla/ffobj/toolkit/library/build
so did the make clean in  E:\svncode\mozilla\ffobj\layout\base followed by make and then did the make in:
E:/svncode/mozilla/ffobj/toolkit/library/build
and sure enough got past this error but landed squarely back into:
weakld: error: Unresolved symbol (UNDEF) '__ZN7mozilla23AudioQueueMemoryFunctor12MallocSizeOfEPKv'.
weakld: info: The symbol is referenced by:
    E:\svncode\mozilla\ffobj\content\media\MediaDecoderReader.o
Ignoring unresolved externals reported from weak prelinker.
make.exe[1]: *** [xul.dll] Error 1
make.exe[1]: Leaving directory `E:/svncode/mozilla/ffobj/toolkit/library/build'
make.exe: *** [default] Error 2

**Comment by SilvanScherrer** [comment]
If there are still build issues, please open a new ticket. I close this because 31.8 is too old now.
