### ISSUE TITLE
Navigating to https://hack.chat/ causes Firefox to trap.

### ISSUE THREAD

**Issue by dbanet** [bitwiseworks/mozilla-os2#120]
**Steps to reproduce**:
* Alt-D
* ``https://hack.chat/``
* Enter

**Expected behavior**: a loaded web page, no crash.

**Actual behavior**: crash before the web page loads (no crash on Windows).

**EXCEPTQ report**: https://clbin.com/moXrB

P. S. I have *no* idea what is hack.chat, I'm in no way related to it: it's just some guy on ##math@freenode has posted the link into the channel.

**Comment by StevenLevine** [comment]
Please install the debug symbols and regenerate the .trp file.

FWIW, I recommend using gist to upload .trp files.

**Comment by dryeo** [comment]
@dbanet, did you test with the Windows 31.8.0ESR release?
Seems to crash here when looking for a font

**Comment by dbanet** [comment]
@StevenLevine ``clbin`` is much much more convenient for me as I can paste a file right away at a keystroke from command line or FC/2, which I use to locate the trap file in the first place anyway, so sorry.

@dryeo Mozilla Firefox does not crash on Windows, as I have already said in my first message, citing:

> (no crash on Windows)

If for some reason (mistrust?) a proofpic is still essential, here you go:

![Screenshot.](http://i.imgur.com/vDPGJP9.png)

@StevenLevine have you tried testing it? I cannot come up with any reason I would need to care about the EXCEPTQ report when it is reproducible everywhere (@dryeo confirms).

If it so happens @dmik would not be able to reproduce the trap, I will gladly follow all the steps required to assist in bug fixing and collect all the needed information.

**Comment by dmik** [comment]
I can confirm that it crashes and from what I see in my TRP it has something to do with font processing. This part got a lot of changes in ESR 31 compared to ESR 24 (and even more compared to ESR 17) so it's possible that we still miss something there.

@dbanet However, TRP files from you and others are *still* wanted because it may crash in different locations, you may get another call stack trace and the more info I have the faster I will find the failing point.

**Comment by StevenLevine** [comment]
In <bitwiseworks/mozilla-os2/issues/120/125265111@github.com>, on 07/27/15
   at 09:30 AM, Dmitriy Kuminov <notifications@github.com> said:

>I can confirm that it crashes and from what I see in my TRP it has
>something to do with font processing.

FWIW, the way I interpret the .trp file is that TestCharacterMap() was
called with can null gfxFontFamily object pointer.  If I had to guess it's
a MathML issue and call originated from MathMLTextRunFactory.cpp:624.

Steven

-- 
----------------------------------------------------------------------
"Steven Levine" <steve53@earthlink.net>  Warp/DIY/eComStation etc.
www.scoug.com
----------------------------------------------------------------------

**Comment by dmik** [comment]
Yes, my TRP file shows the same, so it's definitely `gfxFontFamily::TestCharacterMap` failing on a null `this` pointer (judging both from the failing address and instruction which accesses the bit-field). I'm not sure where the call originates from though. Though to me it seems that the call stack is as follows:
```
gfxFontFamily::TestCharacterMap (gfxFont.h#848)
gfxFontGroup::TryAllFamilyMembers (gfxFont.cpp#5401)
gfxFontGroup::FindFontForChar (gfxFont#5440)
...
```
(the `MathMLTextRunFactory.cpp` file doesn't contain any calls to `TestCharacterMap`).

Most likely, we don't properly initialize the `FamilyFace::mFamily` field in `gfxFontGroup`. I will sort it out later.

**Comment by dmik** [comment]
This works well with FF 38.2.1. Seems that switching to Pango cured this for free. Good.
