### ISSUE TITLE
 FF 31.8.0 can't process (locale) add-ons, see #117 

### ISSUE THREAD

**Issue by JoopN** [bitwiseworks/mozilla-os2#122]
Deleted installation of FF31.8.0 and reinstall it again. Tried the installation outlined by Dmitriy. I get this in the log file;

DIVE forced on by MOZ_ACCELERATED=1 - pointer will be hidden
_init_dive:  _load_dive() succeeded
_init_dive:  hDive= 1  scrn= 0x4ab0000  format= BGR4
Changing DIVE from enabled to disabled - 'layers.acceleration.disabled' is TRUE
console.error: 
  Could not write session state file 
  I:\FIREFOX_3180\Mozilla\Firefox\Profiles\9x7wfvrt.default\sessionstore.js
  Message: Unix error 0 during operation move on file I:\FIREFOX_3180\Mozilla\Firefox\Profiles\9x7wfvrt.default\sessionstore.js (Error 0)
1438048091321	addons.repository	WARN	Unknown type id when parsing addon: 5
1438048096712	addons.xpi	WARN	Failed to install E:\var\temp\tmp-czm.xpi from https://addons.mozilla.org/firefox/downloads/file/268076/nederlands_nl_language_pack-31.0-fx.xpi?src=version-history: {"operation":"stat","path":"I:\\FIREFOX_3180\\Mozilla\\Firefox\\Profiles\\9x7wfvrt.default\\extensions\\staged\\langpack-nl@firefox.mozilla.org.xpi","unixErrno":0}

Fresh install, new profile. As its working for you it must be something outside FF, which file (dll) will cause this if its missing or if version is not right?

**Comment by dmik** [comment]
@JoopN reopening doesn't mean creating new issues, please don't do that. I moved your comment to the issue #117.

**Comment by JoopN** [comment]
Sorry, couldn't reopen it. Tried, but did not find any button or hint 
how to proceed.


Op 28-07-15 20:47, Dmitriy Kuminov schreef:
