### ISSUE TITLE
Firefox 31.8 crashes with SYS2070

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/mozilla-os2#124]
The following shows up in my POPUPLOG:

07-28-2015  20:42:30  SYS2070  PID 0053  TID 0001  Slot 0066
G:\APPS\TCPIP\FIREFOX_NEW\FIREFOX.EXE
XUL->STDCPP6.__ZSt24__throw_out_of_range_fmtPKcz
127

I am not finding any TRP files from this failure.

Some background on the install itself:

1) executing the app by running the following *.cmd file

REM **********************************************
REM *** Mozilla / Firefox Specifics  - START   ***
REM **********************************************
SET MOZILLA_HOME=G:\TMP\MOZILLA.ORG\USERPROFILES
SET MOZ_PLUGIN_PATH=G:\TMP\MOZILLA.ORG\USERPROFILES\mozilla\plugins

REM Below causes Firefox not to use OS/2's high resolution timer
rem SET NSPR_OS2_NO_HIRES_TIMER=1

REM Below allows Mozilla to use the FT2LIB <= not sure if still active
REM SET MOZILLA_USE_EXTENDED_FT2LIB=T

REM Below disables Firefox crash reporting using EXCEPTQ
REM SET NSPR_NO_EXCEPTQ=1

REM Below allows Firefox to disable the HARDWARE ACCELERATION
REM SET MOZ_ACCELERATED=0

REM Below causes to disable Remote Workplace Server support
REM SET MOZ_NO_RWS=1

REM Below allows to run 2 instances in parallel: regular & debug
REM SET MOZ_NO_REMOTE=1
REM **********************************************
REM *** Mozilla / Firefox Specifics  - END     ***
REM **********************************************

SET LIBPATHSTRICT=T
CD G:\APPS\TCPIP\FIREFOX_NEW
start FIREFOX.EXE

2) installed by running the WPI file (), so this is not a RPM/YUM install

3) same SYS2070 is produced regardless of whether I have any other Mozilla apps running or not...so it happens even when the NEW version is the only one being started

**Comment by dspiatkowski** [comment]
Additional comment, I had re-booted the machine since posting the initial bug-entry, now I have my 17.0.11 up and running and executing the very same start-up script actually does NOT result in a POPUPLOG entry, rather the 17.0.11 version of the Firefox window appears to be created...???

**Comment by dryeo** [comment]
On 07/28/15 06:08 PM, Dariusz Piatkowski wrote:
> The following shows up in my POPUPLOG:
>
> 07-28-2015 20:42:30 SYS2070 PID 0053 TID 0001 Slot 0066
> G:\APPS\TCPIP\FIREFOX_NEW\FIREFOX.EXE
> XUL->STDCPP6.__ZSt24__throw_out_of_range_fmtPKcz
> 127
>

You have an old version of STDCPP6.DLL in your LIBPATH.

**Comment by dspiatkowski** [comment]
Where can I get it as part of a ZIP file? 

I know the project's policy is NOT to do this...but I can't even open the available RPM files using the ArcView program, when I attempt to do so I get the following error in the VX-REXX console:

SYS1092: The handle could not be duplicated during a pipe operation.

So even though I pulled the STDCPP6 required RPM file as per the Firefox README I still could not extract the required DLL.

**Comment by StevenLevine** [comment]
>Where can I get it as part of a ZIP file? 

>I know the project's policy is NOT to do this...

What are you talking about?  As has been announced on most (if not all) of
the OS/2 support sites:
   http://hobbes.nmsu.edu/download/pub/incoming/firefox-24.8.1.en-us.os2.beta_4_extra_dlls.zip

has most of what you need.

but I can't even open the
>available RPM files using the ArcView program, when I attempt to do so I
>get the following error in the VX-REXX console:

Why are you reporting this here?  Would it not be more useful to report
this to the arcview maintainer?

>So even though I pulled the STDCPP6 required RPM file as per the Firefox
>README I still could not extract the required DLL.

Use unrpm.cmd.  I don't recall were it is documented, but the docs exist
or folks would not know how to use it.  You can download it from

  http://rpm.netlabs.org/bootstrap/unrpm.cmd

along with the apps it uses.

**Comment by SilvanScherrer** [comment]
@dspiatkowski when ArcView is not opening a rpm, you must have something either old or really broken. If I were you I would try to fix this as well.

**Comment by dspiatkowski** [comment]
StevenLevine: Per Dimitri's earlier response to my os2forum post the official policy is to NOT support ZIP distributions...heck, I do not actually find a problem with it, rather have to deal with the way of getting the correct stuff on my machine since I can not do RPM/YUM install yet.

For the record, it is NOT there on Hobbes INCOMING at the moment either...good news is that it was been moved since the original upload back in March...given that it's nearly Aug_2015...does that ZIP file even have accurate versions anymore???

Regarding ArcView...holy smokes...let's take a deep breath and relax a bit...I'm trying to give you guys as detailed of a picture of my system/configuration as possible so that when someone hopefully looks at the ticket they can be much more informed about what's potentially contributing to the problem. Is ArcView even being maintained? I have no idea...the latest version was published by Alex Taylor, is still available from his site for download...but he clearly states that this is now part of the vxapps on Netlabs...

OK, thanks for your input, I will review the unrar.cmd details you provided!

SlivanScherrer: Yes, I suspect something else is causing a problem, but I even traced throught the ArcView with DLLTree to see what was possibly being pulled in and so on...wasn't able to narrow it down yet...but am continuing to troubleshoot.

**Comment by dmik** [comment]
@dspiatkowski the problem with ZIPs (and any other manual method, in fact, like just listing what's needed in a README as we currently do) is that nowadays projects have a LOT of various dependencies and tracking them manually requires too much effort. For you it may look like there is a team of developers working on Firefox for OS/2 so why the heck can't they sort out this stuff. But in fact it's quite the opposite: there is one-two developers working on ALL (well, many) OS/2 projects. An automated package management system serves to solve this exact problem and that's why we went the RPM/YUM way. So please either adopt this way or live with a need to sort out the DLL problems on your own.

The ZIP for Firefox 24 doesn't contain the latest versions of everything and it at least misses the libkai DLL. It's better to always use the latest versions (unless explicitly stated otherwise).

ArcView in eCS 2.2 Beta II is version 2.1 and it works perfectly with RPM archives.

I'm closing this.

**Comment by wztest** [comment]
Search for an older STDCPP6.DLL on your system and remove it or adjust your libpath in config.sys. The runtime dlls in a zip you can find on hobbes and some other places. The url for the previous dll package (doesn't contain all req.as said above): http://hobbes.nmsu.edu/download/pub/os2/apps/internet/www/browser/firefox-24.8.1.en-us.os2.beta_4_extra_dlls.zip  There are maybe newer packages out there - google is your friend.
