### ISSUE TITLE
FF 38.1.0 will not download files from Hobbes....

### ISSUE THREAD

**Issue by babydoc** [bitwiseworks/mozilla-os2#130]
If I go to Hobbes and try to download (not using FTP) a file, nothing happens. When I click on download the screen stays the same and nothing happens. I don't know if this behavior happens at other sites Please suggest another site I can try.

**Comment by dmik** [comment]
This works like a charm. Something is wrong on your system. Most likely, you mixed up some DLLs. Please check the requirements in README.OS2 once again and make sure you do what is described here and report if it helps: https://github.com/bitwiseworks/mozilla-os2/issues/117#issuecomment-126077834.

**Comment by babydoc** [comment]
Dmitriy,

> This works like a charm. Something is wrong on your system. Most likely,
> you mixed up some DLLs. Please check the requirements in README.OS2 once
> again and make sure you do what is described here and report if it
> helps: #117 (comment)
> <https://github.com/bitwiseworks/mozilla-os2/issues/117#issuecomment-126077834>.

There were several older libc06n.dll files that I renamed and now the 
download function works as it should.

Thank you for helping me.

Martin

**Comment by dmik** [comment]
Good. Thanks letting know.
