### ISSUE TITLE
Occasional printing error with FF31.8.0 b5,  but not with FF24.8.1 

### ISSUE THREAD

**Issue by Koest31** [bitwiseworks/mozilla-os2#134]
On some occasions/websites FF31.8.0 b5 fails to print while FF 24.8 1 works properly:

Printing e-mails from the webmail of hccnet.nl  ,https://webmail.hccnet.nl/src/webmail.php>  [PW protected]
Printing from the digital version of the daily "NRC" ( Dutch) <digitaleeditie.nrc.nl/welkom> [PW protected]
Printing from the public transport website "9292 reist met je mee" (Dutch)  <9292.nl> [Public]

A window titled "Printing error" appears with text " An error occurred while printing".
The browser does not crash and otherwise continues to function. No signal light at the printer signalling contact.

As I understand from colleagues there are more websites where this problem occurs.
See also posting at    groups.google.com/forum/#!topic/mozilla.dev.ports.os2/Xy316EkM0x4

Regards,   Jaap Stil.

**Comment by Koest31** [comment]
Addition:    Website "NRC" =  <digitaleeditie.nrc.nl/welkom>

**Comment by Koest31** [comment]
Hmm, while working from FF31.8.0,  I seem to be incapable to integrate the webpage address of the "NRC" in the text.
I am trying here again but with spaces between characters,  <d i g i t a l e e d i t i e . n r c . n l / w e l k o m>

**Comment by Koest31** [comment]
... It appears a forbidden text !   I am baffled !
-----digitaleeditie.nrc.nl/welkom-----

**Comment by dmik** [comment]
Did you deliberately close this issue or it was unintentional? Please clarify.

**Comment by Koest31** [comment]
I am sorry that I have messed up while trying to clarify the printing
problem. It was not the intention to stop the process so "closing"
happened by misunderstanding the terminology of the website, apologies.
Jaap Stil.


is issueOp Di, 25 augustus, 2015 12:01 am schreef Dmitriy Kuminov:

**Comment by Koest31** [comment]
Issue erroneously closed,  reopened.

**Comment by dmik** [comment]
Printing works well in FF45, so this isn't relevant any more.
