### ISSUE TITLE
Crash in seconds after loading http://math.stackexchange.com/

### ISSUE THREAD

**Issue by dbanet** [bitwiseworks/mozilla-os2#139]
On 31ESR (IBM OS/2), the browser crashes at the end of MathJax mathematics rendering on [Mathematics Stack Exchange](http://math.stackexchange.com/) (MSE).

31ESR running on Windows does not have any problems (no crash) with MSE and maths rendering.

The site was working perfectly before [they have switched to MathJax 2.6 beta](http://meta.math.stackexchange.com/questions/21505/mathjax-2-6-beta).
This does not have anything to do with the `CommonHTML` MathJax maths rendering engine which is mentioned on the Meta post, as it is not turned on by default (checked on Windows); the current MathJax maths rendering engine is still `HTML-CSS`, as it was before the update.

I wonder if this has anything to do with custom (downloaded? or separately installed ones? or something `@font-face`-related? or some special kind of fonts? I don't really know, so I will further refer to this as "custom") fonts.

It has never been using custom fonts on OS/2 (as it could not do that as it is not supported at all), but it appears it can do that on other platforms even with the `HTML-CSS` MathJax maths rendering engine (we are not (yet) talking about the `CommonHTML` MathJax maths rendering engine at all) and it at least tries to do something font-related (to check if it is supported at all probably?), as can be seen, for example, on MathB.in: [load some paste containing mathematics](http://mathb.in/43571) (it won't crash; it should still be using an older version (namely, MathJax v2.3), which does not induce any troubles) and immediately start watching the bottom-left corner. You will see some non-related messages appearing (obviously, for logging/status report reasons), which are not shown (not enabled? disabled? is this maybe a special separate feature of MathB.in not directly related to MathJax? something else? I don't know) on MSE, and the last one (or somewhere near to the last one) will be a report that it is not going to use custom fonts because they are not available and will instead use images.

Hence I wonder maybe has some check for custom font support been altered in MathJax 2.6 beta so that it uses some rare mechanisms not patched in the OS/2 port? Or has they at all screwed MathJax up so that it doesn't perform the check and starts doing something font-related (I mean, trying to render using custom fonts) immediately? I hope this is not the case and the latest MathJax would still be useful without custom fonts support. But even if this is the case, it should not crash.

**Comment by dbanet** [comment]
Created [a workaround](http://meta.math.stackexchange.com/a/21529/220258), if someone is also suffering because of this issue.

**Comment by dryeo** [comment]
On 09/26/15 02:15 AM, dbanet wrote:
> Hence I wonder maybe has some check of custom font support been altered
> in MathJax 2.6 beta so that it uses some rare mechanisms not patched in
> the OS/2 port? Or has they at all screwed MathJax up so that it doesn't
> perform the check and starts doing something font-related (I mean,
> trying to render using custom fonts) immediately? I hope this is not the
> case and the latest MathJax would still be useful without custom fonts
> support. But even if this is the case, it should not crash.

It is crashing while looking for a glyph and it shouldn't, instead 
displaying a box with the unicode in it.
I installed the Math-Tex-fonts-otf fonts and it crashed less, then I 
added an old version of the styx fonts I had laying around from doing 
mathml testing when it was first introduced and it mostly works but will 
still eventually crash in gfxFontGroup.
It could also be related to MathML and need a newer Firefox.
You really should have the right fonts installed for any mathml work, 
mathml, styx and the updated Math-Tex-fonts-otf I guess. I know when 
testing with Ilya I needed both styx and the mathml fonts to get close 
to correct rendering but there were always some idiosyncrasies with our 
rendering.
Note to install the otf fonts you first need an updated freetype driver 
for the WPS, https://github.com/altsan/os2-freetype-ifi/releases

**Comment by dbanet** [comment]
MathML is not related as it is not used by the ´HTML-CSS´ MathJax maths
rendering engine.

As I've said, it works perfectly with 31ESR on Windows. No additional fonts
are installed.

MathJax should fallback to images and Firefox should not crash.

**Comment by dryeo** [comment]
Sorry, I missed that you tested with 31ESR on Windows, which will download the needed fonts. And of course it shouldn't crash.
The stack trace does show that it is using MathML, or at least the MathMLTextRunFactory
```
 Labels on the Stack
______________________________________________________________________

   ESP     Address    Module     Obj:Offset    Nearest Public Symbol
 --------  ---------  --------  -------------  -----------------------
 001248AC  115B13FF   XUL       0001:009513FF  between gfxFontEntry::TestCharacterMap + 11F and nsExpirationTracker::ExpirationTrackerObserver::Observe - 31  (both in gfxFont.o)
 001248EC  115B2F87   XUL       0001:00952F87  between gfxFontGroup::FindFontForChar + 127 and nsTArray_base::ShiftData - 619  (both in gfxFont.o)
 0012490C  115A727C   XUL       0001:0094727C  between gfxFontStyle::gfxFontStyle + 13C and gfxFontGroup::gfxFontGroup - 94  (both in gfxFont.o)
 0012494C  12B44FAF   XUL       0001:01EE4FAF  between MathMLTextRunFactory::RebuildTextRun + E4F and js::RootedGeneric::{vtable} - 1101  (both in MathMLTextRunFactory.o)
...
```

**Comment by pkra** [comment]
@dbanet wrote

> MathML is not related as it is not used by the ´HTML-CSS´ MathJax maths

That's not quite correct. You're right that the HTML-CSS renderer does not use MathML elements but MathJax 2.6 now ships an extension (AssistiveMML.js) that embeds raw MathML in the page for accessibility purposes. This happens after the visual rendering is done which would explain why you see this after rendering.

@dryeo let us know if we (on the MathJax end) can do anything to help.

**Comment by dmik** [comment]
Just a side note, the font code in gfx is about to be redone after we get esr38 up and running, it's a long standing task (#65). I'm almost sure the crash you see here is related to the OS/2 font code being not quite in line with the current state of gfx affairs (which changed quite considerably since ff10 when the initial cairo code was added by Rich Walsh I'd say).

**Comment by dryeo** [comment]
On 09/28/15 01:34 AM, Dmitriy Kuminov wrote:
> I'm almost sure the crash you see here is related to the OS/2 font code
> being not quite in line with the current state of gfx affairs (which
> changed quite considerably since ff10 when the initial cairo code was
> added by Rich Walsh I'd say).

Actually Peter added the code back when FF moved to Cairo for rendering, 
FF3.5pre IIRC.

**Comment by dmik** [comment]
Aha, I see. Good to know.

**Comment by dbanet** [comment]
Not reproduced in 38ESR.

**Comment by dmik** [comment]
Very good. Thank you for testing.
