### ISSUE TITLE
pthread NOT FOUND

### ISSUE THREAD

**Issue by PaoloRicardo** [bitwiseworks/mozilla-os2#143]
The link in README.OS2 for http://rpm.netlabs.org/release/00/i386/i386/pthread-20140814-16.oc00.i386.rpm gives a '404 Not Found' message

firefox-31.8.0.en-US.os2.beta_5.zip

**Comment by dbanet** [comment]
http://rpm.netlabs.org/release/00/i386/i386/pthread-20150408-19.oc00.i386.rpm

Installing this would likely also resolve your #144.
02.12.2015 6:34 пользователь "PaoloRicardo" <notifications@github.com>
написал:

**Comment by PaoloRicardo** [comment]
I'm afraid it doesn't. Put the pthr01.dll in my c:\firefox\dll directory but got the same 'Couldn't load xul.dll' message.

**Comment by LewisR** [comment]
What is your LIBPATH? I suspect something else with a conflicting name (perhaps not even pthread) is trying to load and not satisfying a dependency.

If you are adding these dlls to the program directory, make sure that LIBPATHSTRICT is enabled and either the program directory is *first* in LIBPATH or "." is first and you are changing to the program directory to start Firefox.

A tool which can help quite a bit is PMDll:

http://hobbes.nmsu.edu/h-search.php?key=pmdll-2.11.zip

Unzip that somewhere safe, start it, and select xul.dll using the same LIBPATH as you would for Firefox. Find what's not loading.

**Comment by PaoloRicardo** [comment]
My LIBPATH include c:\os2\dll and one I've added c:\firefox\dll.
I have put c:\firefox\dll as the first entry in libpath and set LIBPATHSTRICT=T. I opened an OS/2 window and changed to the firefox program directory. Launching Firefox from the command line gave the same 'Coldn't load xul.dll' message.

**Comment by LewisR** [comment]
Discussion moved to #144

**Comment by dmik** [comment]
This one may be closed then, I suppose.
