### ISSUE TITLE
'Couldn't load xul.dll'

### ISSUE THREAD

**Issue by PaoloRicardo** [bitwiseworks/mozilla-os2#144]
firefox-31.8.0.en-US.os2.beta_5.zip

I put all the .dlls in a c:\firefox\dll directory and added this directory to my libpath. Got the 'couldn't find' message. Put a copy of the kai0.dll in c:\os2\dll but still got the same message.

**Comment by LewisR** [comment]
I should have placed my reply in #143 here.

**Comment by LewisR** [comment]
Moving discussion here from #143...

Are you sure you rebooted after changing LIBPATH? To test without rebooting, use SET BEGINLIBPATH and make your entry there for c:\firefox\dll (FWIW, I think putting these dlls under a program directory is a bad thing, as they are meant to be shared by other programs, but that shuld not matter for these purposes).

Again, run PMDll and see what dll is not being found or is unable to load.

GL

**Comment by PaoloRicardo** [comment]
OK, I loaded PMDLL and selected xul.dll. I got a list of RED entries (DLL cannot be found or loaded).
Called by xu.dll:
	NSPR4.DLL
	NSS3.DLL
	NSSUTIL3.DLL
	MOZALLOC.DLL
	PLC4.DLL
	SMIME3.DLL
	PLDS4.DLL
	MOZSQLT3.DLL
	SSL3.DLL
	
Called by MMAP.DLL, FNTCFG2.DLL, Z.DLL:
	GCC473.DLL

**Comment by PaoloRicardo** [comment]
OK, I've added c:\firefox to the LIBPATH. Now this only leaves:
Called by MMAP.DLL, FNTCFG2.DLL, Z.DLL:
GCC473.DLL.

So I need to find GCC473.DLL. I've done a search/locate but it comes up with nothing.

**Comment by LewisR** [comment]
From the README.OS2:

6. INSTALL 'gcc473.dll' and 'stdcpp6.dll' from
      http://rpm.netlabs.org/release/00/zip/gcc-4_7_3_1-1_oc00.zip.
      If you use WarpIn, you may install a WPI from
      ftp.netlabs.org/pub/gcc/gcc4core-1_2_2.wpi.
      If you use RPM/YUM, just run:
      'yum install libgcc473 libstdc++' from the command line.

**Comment by LewisR** [comment]
The reason you had to add c:\firefox  to your LIBPATH is that "." is not present. I would refcommend adding "." to the front, though some say it should come after some other things (I keep mine in front, though). This way, if there *is* something special needed for a particular app, you should be able to find it. (BTW, you should be able to do away with LIBPATHSTRICT unless you load Thunderbird and/or SeaMonkey and/or Firefox at the same time; I only wanted to test - there should be a mention of this in the README, I think.)

**Comment by PaoloRicardo** [comment]
Lewis: thanks for you help. I missed the bit about "INSTALL 'gcc473.dll' and 'stdcpp6.dll' ".

I'll get that sorted tomorrow. Thanks again.

**Comment by LewisR** [comment]
You bet! Glad to help.

Cheers

**Comment by PaoloRicardo** [comment]
Sorry to add a further question to this.
I downloaded gcc-4_7_3_1-1_oc00.zip. gcc473.dll and stdcpp6.dll are contained in the archive. Do I just have to add these 2 dlls to the c:\os2\dll directory? In other words ignore the rest of the archive and just extract these two?

I also downloaded gcc4core-1_2_2.wpi as an alternative. I tried to use WarpIN to install it but it complains "The following packages are required but not installed on your system: netlabs.org\kLIBC\LIBC 0.6 Runtime\0\6\5\0".

So do I need this runtime as well or will the addition of the 2 dlls above solve the problem?

Thanks

**Comment by PaoloRicardo** [comment]
An update:
Loaded libc-0_6_6-csd6.wpi and gcccore4-1_3_0.wpi. Confirmed that all the dlls had been loaded and LIBPATH is correct.
Launched Firefox and got a SYS2070 message : "The system could not load the application segment: XUL->STDCPP6._Zst24_throw_out_of_range_fmtPKc2 is in error"

**Comment by SilvanScherrer** [comment]
it seems you had a wrong stdcpp6.dll search for duplicates and only use the one from 2nd February 2015.

**Comment by PaoloRicardo** [comment]
I've searched my system - I only have a stdcpp6.dll dated 05.02.2014. Not sure where I'd get the one you mentioned.

**Comment by SilvanScherrer** [comment]
so I wonder where you got the wrong one. afair on hobbes is a firefox helper wpi. it should include all needed dll.
but just to let you know: we strongly recommend to install yum/rpm. as then updates are always working and you have the right dll's.

**Comment by LewisR** [comment]
This was partially my fault. I grabbed the README from the wrong machine, here, and the information I posted was outdated (referring to gcc 4.7.3 vs gcc1.dll from the later package. So sorry for that!

Indeed, gcc4core-1_3_0.wpi has an outdated stdcpp6.dll.

README.OS2 for FF 31.8.0 mentions:

http://rpm.netlabs.org/release/00/i386/i386/libgcc1-4.9.2.1-3.oc00.i386.rpm
http://rpm.netlabs.org/release/00/i386/i386/libstdc++6-4.9.2.1-3.oc00.i386.rpm

The zipfile you'll want - if indeed you decide not to install yum/rpm, against Silvan's recommendation - would be http://rpm.netlabs.org/release/00/zip/gcc-4_9_2_1-3_oc00.zip.

You just need those two dlls.

Again, my apologies for not checking which machine I was using as a reference!

**Comment by SilvanScherrer** [comment]
the gcc4core 1.3.0 wpi was wrong packed it seems. No one ever told us so far :(. We did a new gcc4core 1.3.1 (ftp.netlabs.org/pub/gcc/gcc4core-1_3_1.wpi) this should also work.

**Comment by LewisR** [comment]
Thanks for that, Silvan. I was actually going to look at that when I had a chance. ;-)

**Comment by PaoloRicardo** [comment]
Lewis: thanks. Got there - eventually :-)

I'm happy to accept Sylvan's recommendation. Do I need both rpm and yum 
or just yum?

On 04/12/15 1:36 AM, Lewis Rosenthal wrote:
>
> This was partially my fault. I grabbed the README from the wrong 
> machine, here, and the information I posted was outdated (referring to 
> gcc 4.7.3 vs gcc1.dll from the later package. So sorry for that!
>
> Indeed, gcc4core-1_3_0.wpi has an outdated stdcpp6.dll.
>
> README.OS2 for FF 31.8.0 mentions:
>
> http://rpm.netlabs.org/release/00/i386/i386/libgcc1-4.9.2.1-3.oc00.i386.rpm
> http://rpm.netlabs.org/release/00/i386/i386/libstdc++6-4.9.2.1-3.oc00.i386.rpm
>
> The zipfile you'll want - if indeed you decide not to install yum/rpm, 
> against Silvan's recommendation - would be 
> http://rpm.netlabs.org/release/00/zip/gcc-4_9_2_1-3_oc00.zip.
>
> You just need those two dlls.
>
> Again, my apologies for not checking which machine I was using as a 
> reference!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bitwiseworks/mozilla-os2/issues/144#issuecomment-161657802>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by LewisR** [comment]
You bet.

You'll need both packages. However, if you start with the installation instructions here:

https://trac.netlabs.org/rpm/wiki/RpmInstall

and use the updated bootstrap:

http://rpm.netlabs.org/bootstrap/rpm-yum-bootstrap-1_5-p4.wpi

I'll have to update the wiki page with updated links. Anyway, that should get you started. Arca Noae will be releasing our graphical package manager later this month, and that should make yum even easier.

Good luck, Paolo. Glad we got you to the right files, at least!

-- 
Lewis
Sent from my overclocked HP TouchPadOn Dec 3, 2015 5:46 PM, PaoloRicardo <notifications@github.com> wrote: 
Lewis: thanks. Got there - eventually :-)



I'm happy to accept Sylvan's recommendation. Do I need both rpm and yum 

or just yum?



On 04/12/15 1:36 AM, Lewis Rosenthal wrote:

>

> This was partially my fault. I grabbed the README from the wrong 

> machine, here, and the information I posted was outdated (referring to 

> gcc 4.7.3 vs gcc1.dll from the later package. So sorry for that!

>

> Indeed, gcc4core-1_3_0.wpi has an outdated stdcpp6.dll.

>

> README.OS2 for FF 31.8.0 mentions:

>

> http://rpm.netlabs.org/release/00/i386/i386/libgcc1-4.9.2.1-3.oc00.i386.rpm

> http://rpm.netlabs.org/release/00/i386/i386/libstdc++6-4.9.2.1-3.oc00.i386.rpm

>

> The zipfile you'll want - if indeed you decide not to install yum/rpm, 

> against Silvan's recommendation - would be 

> http://rpm.netlabs.org/release/00/zip/gcc-4_9_2_1-3_oc00.zip.

>

> You just need those two dlls.

>

> Again, my apologies for not checking which machine I was using as a 

> reference!

>

> —

> Reply to this email directly or view it on GitHub 

> <https://github.com/bitwiseworks/mozilla-os2/issues/144#issuecomment-161657802>.

>







---

This email has been checked for viruses by Avast antivirus software.

https://www.avast.com/antivirus




—
Reply to this email directly or view it on GitHub.


  
  



-- 
This email was Anti Virus checked by Astaro Security Gateway. http://www.astaro.com

**Comment by SilvanScherrer** [comment]
I close this, as I think all is fixed and ffox runs. If there are still issues feel free to reopen it.
