### ISSUE TITLE
yum config.sys issues

### ISSUE THREAD

**Issue by PaoloRicardo** [bitwiseworks/mozilla-os2#145]
I'm not sure if this is the right place to post this. If not please indicate where I should post.
According to the readme file with yum-rpm install package, the installation is supposed to make numerous changes to CONFIG.SYS. It didn't on my system

It refers to changes to PATH to include c:\usr\sbin;c:\usr\bin;c:\sbin;c:\bin. Of these only c:\usr\bin is present on my system. However there are a lot of other yum-related directories that have been set up e.g. c:\etc\..., c:\share\...,c:\var\...

When I tried to run yum from the command line ('yum list installed') OS/2 didn't recognise the command. Not surprising since CONFIG.SYS had not been modified. So what do I have to add to CONFIG.SYS to correctly identify the paths that yum should follow?

TIA

**Comment by LewisR** [comment]
If you do find a bug (or would like to continue this one), I suggest you follow the directions here:

https://trac.netlabs.org/rpm#Reportingbugs

I suggest you re-run the bootstrap and follow the instructions to the letter, i.e, open the bootstrap console after installing and run "yum install yum" from there. That should make the proper changes to CONFIG.SYS.

Good luck!

**Comment by dmik** [comment]
As said above, the correct place for reporting rpm/yum related bugs is https://trac.netlabs.org/rpm. Please login there and add a new ticket and we will discuss it there. Thanks.

**Comment by PaoloRicardo** [comment]
Lewis: thanks for the advice. I DID 'follow instructions to the letter'. 
The problem is that in neither the ReadMe.txt/NextStep.txt files nor in 
the running of the Yum Bootstrap Console is there any instruction to 
enter 'yum install yum'.

Anyway I've now installed yum. I presume I can no delete the yum 
bootstrap console folder - just chcking :-)

Regards
Paul

On 04/12/15 5:25 PM, Lewis Rosenthal wrote:
>
> If you do find a bug (or would like to continue this one), I suggest 
> you follow the directions here:
>
> https://trac.netlabs.org/rpm#Reportingbugs
>
> I suggest you re-run the bootstrap and follow the instructions to the 
> letter, i.e, open the bootstrap console after installing and run "yum 
> install yum" from there. That should make the proper changes to 
> CONFIG.SYS.
>
> Good luck!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bitwiseworks/mozilla-os2/issues/145#issuecomment-161889273>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
