### ISSUE TITLE
Review default `font.*` settings

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#146]
OS/2 sets up default Mozilla fonts in `modules/libperf/init/all.js`, as many other platforms do. Currently, it refers to fonts like "Tms Rmn" and "Helv" which are not supported by FreeType (and the default fontconfig configuration knows nothing about these fonts). We should use perhaps "Times New Roman" and "Helvetica" by default which are always available. Or even prefer something like DejaVu (like other linux platforms do) with the mentioned ones as a fallback (since they are always present).

BTW, it also makes sense to alter the default fontconfig configuration so that it also emits correct substitutions for "Tms Rmn" and "Helv" — just in case any app using FreeType/fontconfig will request them for some reason (e.g. by reading the PM style information, etc.).

**Comment by dbanet** [comment]
Just curious, why doesn't it know anything about these fonts, especially when I certainly have those installed?

![tmsrmsnhelv2](https://cloud.githubusercontent.com/assets/5563987/11708593/a86e8fd4-9f21-11e5-82b1-a6457ab276ff.png)

Does that mean it actually does not use any of the fonts installed then? And can this be changed?

**Comment by dmik** [comment]
@dbanet I suggest you to ask FreeType authors about why they don't support OS/2 FON files. It has always been like that and Mozilla since it was switched to cairo and FreeType (and other products using FreeType, no matter directly or through fontconfig) never supported these fonts — it would always do substitution (to bundled Type 1 fonts "Times New Roman" and "Helvetica", respectively).

Judging from your screenshot, it looks like you are using the Innotek Font Engine (or how it was called) which works by intercepting Gpi calls and uses FreeType rasterizing facilities to draw anti-aliased glyphs but this has nothing to do with FON file recognition by FreeType itself.

I think it's not a big problem per se to implement support for FON in FreeType. These font files are not very good glyph quality-wise and can be easily substituted with other fonts in a completely transparent manner so we don't have plans to add such support to FreeType ATM. If you wish to contribute, you are welcome, as usual :) But then better implement support for the OS/2 bitmap font format first as this is surely more needed (there is a bunch of nice bitmap fonts that could be handy in many occasions).

**Comment by dbanet** [comment]
Okay, got it. Thank you for your clarification. I will consider the
possibility of contribution.

**Comment by dmik** [comment]
BTW, the current fontconfig has a bug. Well, it's not a bug, it's the difference between how PM enumerates Type1 fonts and what Freetype expects them to be. PM stores the .OFM files in the registry while Freetype needs .PFB. For this reason, the standard 3 Type1 fonts present on each OS/2 Warp4+ machine (Times New Roman, Helvetica and Courier New). I fixed it in http://trac.netlabs.org/ports/changeset/1540/fontconfig and will release a new RPM soon. I will also add some default "Tms Rmn" and other substitutions to .conf as described above.

**Comment by dmik** [comment]
There is another (and nasty) bug but this time in the Type1 font itself. Its name is actually "Times New Roman " (with a trailing space). And though the font itself is usable via its name without the trailing space (thanks to fontconfig matching heuristics), when one queries a list of installed fonts, this list will contain the space-trialling version so that the UI code can't find a match. This is e.g. a reason why Firefox users could see an empty default font field in the Settings dialog. I will have to fix it as well.

**Comment by dryeo** [comment]
Yes, Peter had to add a workaround for it to be found in mzfntcnfg

**Comment by dmik** [comment]
After having some discussion with others it appears that the best way to go here is to hard-code generic font families for Firefox defaults instead of the real font families. These generic families will be mapped to real fonts by fontconfig. This gives us freedom to change these defaults based on the system language (or user preferences) using system-wide fontconfig settings without rebuilding the application or changing its configuration. This is especially helpful given that there are no well-defined OS/2 system fonts that would look nice and suit all needed languages.

BTW, font selection appears to be broken in Firefox upstream (at least, on platforms using fontconfig/gfxPangoFonts, e.g. under Linux and now OS/2). This is related to requests for fonts missing on the system. In some cases Firefox will use what fontconfig matching (e.g. fc-match) tells it, in other cases it will use the default font set in Options -> Content -> Default font (although fc-match returns a completely different match). I couldn't find any sane logic in that so far... All this is a big mess.

Another problem is when you set `browser.display.use_document_fonts` to 0 (i.e. disable web pages to override your font preferences). In this case, each and every font becomes what you select as the Default font, even "serif" and "sans-serif" are not distinguished (despite that you set real fonts for both on the Advanced... tab). The only font that is different is from the default one is "monospace". Again, no visible logic but somehow this is how Firefox people designed it so we have to live with that for the time being. 

Note that the above problems can also be seen in FF 24 and all further versions (I don't have FF 17 around any more to check it).

BTW, there is a good link where you can check font matching in a browser: http://www.infinality.net/files/font.html. It can show the problems I mention above as well.

**Comment by dmik** [comment]
BTW, I don't feel like I want to fix fontconfig to solve the trailing space problem any more. Fontconfig internally uses FT structures to store font data; changing them behind FreeType may have some side effects. The right place for the fix here is FreeType itself but I'm still not sure we should deal with spaces there; the trailing space may be intentional after all. And also if I put "Times New Roman " in the Firefox preference (i.e. with the trailing space), the UI starts working fine because this is what the list contains.

Another (and perhaps the best) place to fix this is the font file itself. Because this is where the error comes from in the first place.

**Comment by dryeo** [comment]
On 04/19/16 05:00 PM, Dmitriy Kuminov wrote:
> After having some discussion with others it appears that the best way to
> go here is to hard-code generic font families for Firefox defaults
> instead of the real font families. These generic families will be mapped
> to real fonts by fontconfig. This gives us freedom to change these
> defaults based on the system language (or user preferences) using
> system-wide fontconfig settings without rebuilding the application or
> changing its configuration. This is especially helpful given that there
> are no well-defined OS/2 system fonts that would look nice and suit all
> needed languages.

Another option, or perhaps better described as an extension to this, is 
to make a couple of font.conf files available for users to install in 
%HOME%. Infinality had (has) a couple of examples so users could go with 
the MS core fonts, or IIRC a couple of Linux (Mac?) options.
I've been meaning to revisit the Infinality options though haven't since 
their patches were put in Freetype.
I can't find them at Infinality, here's one alternate, 
https://wiki.archlinux.org/index.php/Infinality

**Comment by dmik** [comment]
I tested substituting generic names with `local.conf` in fontconfig, it works perfectly well. So I committed this change. Note that this commit also removes some redundant and obsolete preferences (like `font.default`).

Here's a sample `local.conf` file that one needs to place to `/@unixroot/etc/fonts/` in order to set the preferred defaults for `serif`, `sans-serif` and `monospace` to be used in Firefox and in any other application using fontconfig (there is no need to reboot or anything but a restart of Firefox may be required if reloading the page doesn't help):
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <alias binding="same">
        <family>serif</family>
        <prefer><family>MY_SERIF_FONT</family></prefer>
    </alias>
    <alias binding="same">
        <family>sans-serif</family>
        <prefer><family>MY_SANS_FONT</family></prefer>
    </alias>
    <alias binding="same">
        <family>monospace</family>
        <prefer><family>MY_MONOSPACE_FONT</family></prefer>
    </alias>
</fontconfig>
```

**Comment by dmik** [comment]
It's also worth mentioning that I modified the font test page from the above comment to contain Lorem Ipsum text instead of random characters, it is available here: https://github.com/bitwiseworks/browser-font-test. It can be checked out and opened locally in the browser via "File Open".

**Comment by dmik** [comment]
The new fontconfig RPM is released. I updated fontconfig to the newest version 2.11.95 that has some cache improvements. Also, I removed the trailing space with just a special .conf file, no fontconfig/freetype source code fix is needed (this conf is active by default). Also I made a mapping of Tms Rmn to Times New Roman, Helv to Helvetica and Times New Roman MT 30 to Times New Roman WT J (since these fonts are not supported but Freetype but may be requested by applications). Also this version of fontconfig changes the hinting style from "full" to "slight", the difference is below.

Full hinting (was):
![2016-04-23 1 55 09](https://cloud.githubusercontent.com/assets/900726/14756868/ecf576e4-08fe-11e6-9295-4a103cc9539e.png)

Slight hinting (now):
![2016-04-23 1 54 37](https://cloud.githubusercontent.com/assets/900726/14756864/e05dda3e-08fe-11e6-9b2e-e3cc17d521e0.png)

I personally prefer the second variant as the font looks more balanced and generally more readable. If one needs it otherwise, it may be easily reverted to full rendering by deleting the symlink `/@unixroot/etc/fonts/conf.d/10-hinting-slight.conf` (later there will be a GUI for that, for sure). It can then be easily restored by executing the following command: `ln -s /@unixroot/usr/share/fontconfig/conf.avail/10-hinting-slight.conf /@unixroot/etc/fonts/conf.d/10-hinting-slight.conf`.

Note that now Firefox will properly select Times New Roman for serif, Helvetica for sans-serif and Courier for monospace if only these standard Type 1 fonts are installed on the system.

I'm very satisfied with the current state of fonts in Firefox. This issue may be closed.

**Comment by dmik** [comment]
Note that we currently don't support sub pixels and lcd filtering (either in Freetype or in Cairo, this needs some investigation). Once we make that work, fonts will look even better (less blurry etc). But this is beyond this ticket, obviously.
