### ISSUE TITLE
Align with external cairo build

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#147]
Dropping gfxOS2Font and friends (see #65) resulted into porting Pango (1.28.4) to OS/2 and linking XUL against it. However, Pango itself needs Cairo, as well as Mozilla. For this reason, we also had to port a separate Cairo build (1.12.0). But it's rather strange to use Cairo provided by Mozilla (which is quite old, 1.9.4) and Cairo needed for Pango, and all in the same XUL DLL. More over, Mozilla supports building against external Cairo out of the box. This ticket is to achieve this task.

**Comment by dmik** [comment]
Firefox actually already builds this way (after a few cosmetic changes, not committed yet). However, running it results into the following crash:
{{{
DIVE is disabled - Panorama's shadow-buffer is enabled
console.error:
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
Assertion failed: CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count), file ../../trunk/src/cairo-surface.c, line 840

Killed by SIGABRT
pid=0xe962 ppid=0xe95f tid=0x0001 slot=0x0097 pri=0x0200 mc=0x0001 ps=0x0010
D:\CODING\MOZILLA\MASTER-BUILD\DIST\BIN\FIREFOX.EXE
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.
}}}

This is most likely because Cairo 1.12.0 had some significant changes compared to 1.9.4. Note that we applied all OS/2 patches that are present the Mozilla tree to our separate Cairo repository (with respective modifications, see http://trac.netlabs.org/ports/ticket/87#comment:16 for details). But it seems that some places still need some alignment.

**Comment by dmik** [comment]
This crash was a Cairo bug, fixed in http://trac.netlabs.org/ports/changeset/1284. Now Firefox runs! It generally works but I see some visual oddities that might be related to the new Cairo. This is how the main toolbar looks in the build with the old (Mozilla owned) Cairo 1.9.4:

![2016-02-05 20 59 08](https://cloud.githubusercontent.com/assets/900726/12854550/5c808c6a-cc4b-11e5-91df-f3c8ec5ed24b.png)

And this is the look of the external Cairo 1.12.0 build:

![2016-02-05 21 00 44](https://cloud.githubusercontent.com/assets/900726/12854584/95720030-cc4b-11e5-8aa6-171d5d8df6d8.png)

You may notice weird grayish background under the Addres bar and under tool buttons to the right (it appears once you hover your mouse over the button). This may be related to the new cairo compositor that appeared in 1.12 (and that I had to align OS/2 patches for, see http://trac.netlabs.org/ports/ticket/87). This needs some closer look.

**Comment by dmik** [comment]
I've committed small code fixes to make gfx build with the new cairo and also temporarily disabled native printing support because cairo lacks the respective patches so far. We will investigate how to best implement printing and then decide what to do. One of the options is to switch to CUPS completely (printing to native drivers is known to have problems, see #75, #134).

**Comment by LewisR** [comment]
> One of the options is to switch to CUPS completely

I would strongly urge against this. There are a good number of systems in need of newer browser builds but which lack CUPS. Making CUPS a requirement adds an entirely new layer of complexity to the installation, and will no doubt result in a number of additional support requests.

While CUPS does appear to side-step the whole GPI problem, the solution is to fix GPI (or whatever is causing GPI so much difficulty (small buffers, unexpected input, etc.). Fixing GPI is a separate conversation, of course, outside the scope of Firefox.

**Comment by dmik** [comment]
Well, this is a serious discussion anyway and besides the scope of this issue perhaps. Basically, these systems will just need to install `yum` and friends. This may be a big task per se but once done, having CUPS and everything is a matter of a single command. The thing is that CUPS beats native GPI in each and every way. I can't imagine a situation where using GPI printing could give the user a benefit (except avoidance of the `yum` installation burden).

**Comment by dmik** [comment]
Closing this issue as the printer one got it's own ticket.
