### ISSUE TITLE
Legacy encodings in 38esr

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#149]
I found out that Firefox 38 doesn't support CP850 (DOS latin charset) and CP864 (DOS arabic charset). In this version, they restricted encodings to what is specified by this document: http://encoding.spec.whatwg.org/#encodings and it doesn't list the above two charsets. As a result, the OS/2 version of `WideCharToMultiByte` and `MultiByteToWideChar` used everywhere in Firefox to encode and decode text fails by crashing in XUL.DLL due to a null pointer reference (because `OS2Uni::GetUconvObject` returns `nullptr`). This is reproducible on any machine with CODEPAGE=850,437 in CONFIG.SYS (i.e. all Western European eCS installations).

We can replace a crash with a silent return but this will completely break Firefox functionality anyway. We need to find a way to restore support for these charsets.

**Comment by dryeo** [comment]
Wonder if iso-8859-15 could be aliased to 850?
IIRC Arabic, Hebrew and other right to left encodings were always 
somewhat broken on our port.
At least my 38esr crash is explained

**Comment by dmik** [comment]
I could easily map cp580 to iso-8859-15 (or to anything else from the list) but the problem is that the layout of cp850 doesn't match iso-8859-15 at all. I couldn't find any match among the supported encodings so far.

**Comment by dmik** [comment]
From what I see, `WideCharToMultiByte` and `MultiByteToWideChar` are used mainly when interacting with PM: window titles, standard file selection dialogs and so on. This means that they don't affect how content is displayed which seems to be driven by the `intl/uconv` component. This is really not wise, I don't understand why one should have two engines for the same thing. But it's Firefox style...

**Comment by dmik** [comment]
These are actually not two engines, there is only one engine to do conversion: `intl/uconv`. There is, however, a list of "allowed" encodings, i.e. encodings recognized by the `EncodingUtils` class (this is new in 38esr). This list doesn't represent all encodings that `uconv` supports (and the unsupported ones may be instantiated directly via respective XPCOM component's object creation requests — this is what the content renderer uses, I believe). But since our OS/2 widget charset conversion functions use `EncodingUtils` rather instantiate conversion objects directly, we have this restriction too.

So I fixed the problem in 40635a5 by simply enhancing the list of supported encodings in `EncodingUtils` with `IBM850` and `IBM864`. We may add more encodings if needed. 

This could also be fixed by making `WideCharToMultiByte` and `MultiByteToWideChar` instantiate conversion objects directly rather than use `EncodingUtils` but I think making `EncodingUtils` support these two charsets is better since it may be used in some other vital cases somewhere (like for some file name conversion etc.).
