### ISSUE TITLE
Background repaint issue with dynamic menu

### ISSUE THREAD

**Issue by ydario** [bitwiseworks/mozilla-os2#151]
The background is not restored when a dynamic menu is shown. Just try http://www.isisobici.gov.it on the top blue menu bar.

**Comment by dmik** [comment]
I confirm. Dismissing the in-site menu leaves a gray background instead of the white one. Looks very same as the issue with the Firefox own tool bar elements (see #147).

**Comment by dmik** [comment]
Couldn't find any obvious hint so far. t'm going to update cairo to 1.12.18 because there is a chance that this is an upstream problem that is gone away (I see some reference to compositor in changelogs).

**Comment by dmik** [comment]
Cairo 1.12.18 completely fixes all background repaint issues including this one (see http://trac.netlabs.org/ports/ticket/87#comment:20). So doing `yum update cairo` once a new RPM is there will cure the problem for every one w/o the need to rebuild Firefox.
