### ISSUE TITLE
Drawing glitches and (probably) font issues

### ISSUE THREAD

**Issue by dbanet** [bitwiseworks/mozilla-os2#156]
I think #147 still applies for me:
![scr1](https://cloud.githubusercontent.com/assets/5563987/13212563/3745a902-d953-11e5-8bf5-fb6d73da56e5.png)

I also suspect there is something wrong with the fonts. They are too blurry, as for me, like there is a 110% zoom.
![src2](https://cloud.githubusercontent.com/assets/5563987/13212578/6258ccc8-d953-11e5-80ed-bebbed46e775.png)
![scr4](https://cloud.githubusercontent.com/assets/5563987/13212580/626bb900-d953-11e5-8652-a55b8d369bfe.png)
![scr5](https://cloud.githubusercontent.com/assets/5563987/13212628/afeccc96-d953-11e5-967b-7b28a772988e.png)
![scr6](https://cloud.githubusercontent.com/assets/5563987/13212627/afd408b4-d953-11e5-90c4-ba0a656dbe89.png)

**Comment by SilvanScherrer** [comment]
please do us all a favor and don't mix several issue in one ticket and also try to see if already similar issues are reported. The first issue you mention is the same as in #151.

**Comment by dbanet** [comment]
Whatever.

**Comment by dmik** [comment]
Yes, this is a duplicate, as we already have #151 for painting issues.

@dbanet What about fonts, please open a new issue and be more specific (i.e. provide side by side screenshots of what it was and what it is now). I don't see what's wrong on your picture above.
