### ISSUE TITLE
Saved passwords are not shown

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/mozilla-os2#157]
The saved passwords are not shown in Tools -> Options -> Security -> Show Passwords
The dialogue just stays empty.

**Comment by dryeo** [comment]
They've made some changes as about:data just returns a bad address error and doesn't show up under about:about. Still works in SM, which is still using the old data manager at about:data, but not in Thunderbird where they seem to have updated to the new data manager.

**Comment by dmik** [comment]
I confirm that. This is somehow related to moving preferences from a regular dialog window to a browser tab (`about:preferences`).

@dryeo `about:data` is already absent in 31.8 (where preferences has still the old flavor and where saved passwords are shown fine) so I don't think it's related.

**Comment by LewisR** [comment]
I normally use the Saved Password manager extension, which works with newer FF on other platforms. However, after upgrading my FF31 profile to FF38 on OS/2, that, too, is blank, and saving new passwords fails (no failure message, but no new login credentials created).

I have not tested with a clean profile, as yet, though.

**Comment by dmik** [comment]
Okay, the problem is that the `Intl` JS component (`js/src/builtin/Intl.js`) is for some reason not available on OS/2. For this reason, `passwordManager.js` fails and nothing is displayed.

**Comment by dmik** [comment]
Okay, this is really simple. The 'Intl' API was disabled on OS/2 because it's not yet ported. See #101 for details. Once it is enabled again, all should work. Hence I'm switching to #101 now.

**Comment by dmik** [comment]
Making ICU available on OS/2 and rebuilding firefox with `Intl` JS API enabled fixes the problem, I can now see saved passwords. Closing this, see #101 for further details about ICU/Intl.
