### ISSUE TITLE
Update to latest 38 release

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#158]
There is at least 38.6.1 at the time of writing (http://hg.mozilla.org/releases/mozilla-esr38/) and we should update.

**Comment by dryeo** [comment]
On 02/24/16 01:41 AM, Dmitriy Kuminov wrote:
> There is at least 38.6.1 at the time of writing
> (http://hg.mozilla.org/releases/mozilla-esr38/) and we should update.
>

38.7.0 is in smoke testing and due out on Mar 7th

**Comment by dmik** [comment]
Okay, thank you for noticing. But I still want to update to 38.6.1 to give it some testing. Updating to 38.7.0 should be easy enough when it's ready. And I'm half way done with the update already.

**Comment by dmik** [comment]
Updated to 38.6.1 in b96ed323148763a69ed7a983785450687ce33d9f and built. No issues so far. I will leave this open until 38.7.0 comes out (or until we release beta 7, which ever comes first).

**Comment by dmik** [comment]
Time to update FF to the latest release. There is Firefox 38.8.0 already (2 weeks old). I will use it.

**Comment by dmik** [comment]
38.8.0 is successfully merged to master.

**Comment by dmik** [comment]
Built it, appears to work with no visual problems.

**Comment by SilvanScherrer** [comment]
Beta7 released.
