### ISSUE TITLE
Add gstreamer support to support HTML5 video

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#16]
Adding gstreamer support will allow using libavcodec to play H264 videos. See https://bugzilla.mozilla.org/show_bug.cgi?id=422540 for details.

**Comment by SilvanScherrer** [comment]
this is also part of #110, #67 and #102

**Comment by dryeo** [comment]
Gstreamer itself will need a fair amount of porting, including an audio plugin and video plugin to be generally useful. At this point Mozilla supports the 1.x gstreamer as well as the .10.x which is no longer being developed and different enough from 1.x that it is not worth considering.
Attempting to run configure on 1.0 dies with
   configure: error: This package requires GLib >= 2.32.0 to compile.
0.10.36 does build without too much hassle. Of course it needs code to find and load the plugins, handle the plugin registry (Windows keeps it in memory due to worries about IO between the DLLS) and probably various pipe fixes.

**Comment by dmik** [comment]
Well, I don't think that we should go any g* way now. It drags in a lot of g* stuff and glib in the first place. It's a big project per se, it may be worth doing (to eventually have an alternative to Qt and many other things) but certainly not within our Mozilla effort.

I checked it now (e.g. here www.quirksmode.org/html5/tests/video.html) and it seems indeed that we don't support H.264 at the moment (WebM and Ogg/Theora work great from that page). The fun thing is that Safari under OS X supports H.264 (using system QuickTime I believe) but doesn't want to play WebM and Ogg/Theora. Both Firefox and Chrome play all three formats under OS X though.

We should find another way to play H.264. Libavcodec is part of ffmpeg IIRC and we already have a working ffmpeg port. Don't we?

**Comment by dryeo** [comment]
On 07/03/15 03:23 AM, Dmitriy Kuminov wrote:
> We should find another way to play H.264. Libavcodec is part of ffmpeg
> IIRC and we already have a working ffmpeg port. Don't we?

They're using libav (http://libav.org) with headers from version 0.8.9 
(0.8.17 should work) which also is a working port. Libav forked from 
FFmpeg and included the Debian and Gentoo FFmpeg maintainers so most all 
Linux distributions currently ship with libav.
The only porting would need to be 
content/media/fmp4/ffmpeg/FFmpegRuntimeLinker.cpp and should give MP4 
(h264+AAC) support.

**Comment by dmik** [comment]
Thanks, Dave.

**Comment by dryeo** [comment]
0.8.x has one assembly file that is not NASM friendly. Of course it is macros that nest more macros, investigating.

**Comment by dryeo** [comment]
Missing trailing / in the includes.
I can make the binaries, dlls available for 0.8.17 if any interest.

**Comment by dmik** [comment]
Great, Dave! I will put my hands on that ASAP.

**Comment by dryeo** [comment]
Binaries are at https://bitbucket.org/dryeo/libav/downloads/libav_v0.8.17_nasm.7z, source is there and at https://github.com/OS2World/libav/tree/v0.8.17_nasm (couldn't upload binaries there) which Martin will happily give commit access to..
I built with 
   ../libav/configure --disable-doc --disable-debug --prefix=r:/tmp/libav --disable-static --enable-shared --extra-libs=-lmmap
Make install is somewhat broken as it installs the long named DLLs as well.
Lots of configure options available in the hand built configure script. Note that this is an old release.

**Comment by dmik** [comment]
With FFMPEG/libav, we already support HTML5 video in many formats. And we are not going to port gstreamer to OS/2 any time soon (less and less need; e.g. MP3 can be played via ffmpeg in FF44+, see #67). I'm closing this as "won't fix".
