### ISSUE TITLE
D'n'D link into bookmark menu does not work anymore

### ISSUE THREAD

**Issue by herwigb** [bitwiseworks/mozilla-os2#162]
dragging a link from the address bar to the bookmark menu does not work anymore in FF38 (testbuild and beta)

**Comment by herwigb** [comment]
It seems it is also impossible to delete an item from the bookmarks menu. The menu appears, one can choose "delete" but nothing happens.

**Comment by SilvanScherrer** [comment]
I just tried that with 38.6.1 and for me all worked. Could you also try?

**Comment by herwigb** [comment]
Just a notice: I am using FF Sync feature here.

**Comment by herwigb** [comment]
When I retried with a new profile both, D'n'D and delete worked. However, this new profile is 2 days old now and I just noticed that D'n'D and delete do not work anymore... Needless to say, it works normally on a 38.61esr for Windows...

**Comment by dryeo** [comment]
Does moving places.sqlite out of your profile (with FF closed) and 
restarting FF to allow a new places.sqlite to be created allow D'n'D to 
work again?

**Comment by herwigb** [comment]
dryeo: You are right, just tried.

**Comment by SilvanScherrer** [comment]
I bet those are not working again after a sync. Could you verify?

**Comment by herwigb** [comment]
Just synced, still works...

**Comment by herwigb** [comment]
This works with  45.9
