### ISSUE TITLE
Unable to load xul.dll

### ISSUE THREAD

**Issue by michaelsnyder** [bitwiseworks/mozilla-os2#163]
I've updated everything that the Arca Noae package manager suggests to update, and unzipped Beta 6 to a new directory.  When I attempt to start it with a program object or by changing to the directory in a window and typing firefox.exe or firefox!.exe, I get a popup window that says, "unable to load xul.dll."

What to do?

**Comment by dmik** [comment]
Did you install all prerequisites listed in README.OS2?

**Comment by LewisR** [comment]
The Quick Install feature of Arca Noae Package Manager should help in this regard, Michael. Just copy and paste them into the quick install dialog. There are likely more modules listed there than what you had installed previously and then updated, so you're probably just missing one or more of them.

**Comment by michaelsnyder** [comment]
Thanks for the tip about the quick install dialog.  I had the prerequisites installed, but some of them were in \ecs\dll.  They do not seem to get updated there.  After I deleted them from there and put them in \usr\lib of the unixroot directory, they updated and the program loads.  Can't say that I like unix stuff very much.  Thanks for the help.

**Comment by dmik** [comment]
@michaelsnyder Arca Noae package manager doesn't manage DLLs in `\ecs\dll` and there was no need to move them from there to `\usr\lib` — it is enough to make sure `\usr\lib` goes before `\ecs\dll` in your LIBPATH (and Arca Noae package manager offers you to do so at each startup). More over, you should **NOT** put anything to `\usr\lib` by hand — ths is not expected and may cause weird behavior on your system, and this is against the whole idea of ANPM that is there to maintain this directory (and LIBPATH) for you. If you follow this approach, everything will be ok. (Don't forget that sometimes you need to reboot your system to have new DLLs loaded — at a time of the update the old versions can be locked by running programs or even by PM and they will be picked up by newly started programs even if they were physically updated on disk — this is how OS/2 works and there is not much ANPM or RPM/YUM which stands behind it can do about that).
