### ISSUE TITLE
Trap loading Firefox 38.2.1

### ISSUE THREAD

**Issue by Rahere2** [bitwiseworks/mozilla-os2#166]
Trap in XUL.DLL with exception C0000005 - access violation attempting to read from 00000018 (not a valid address).
[0039_01.pdf](https://github.com/bitwiseworks/mozilla-os2/files/182080/0039_01.pdf)

**Comment by SilvanScherrer** [comment]
first of all adding a trap report w/o debug symbols is a bit useless. And 2nd when does it happen? Accessing which URL?

**Comment by Rahere2** [comment]
How do I provide you with debug symbols?

The trap occurs on startup - Firefox will not load. My startup page is http://ecomstation.com/index.phtml. FF 31.8 loads perfectly.

I have tried with DLLBASING on and off - no difference. I have tried loading xul.dll high without effect. I have downloaded all the recommended DLLs from http://os2news.warpstock.org/Warpzilla.html (LibC, gccCore, fontconfig and cairo/pango/pixman). All the DLLs are in the C:\ECS\DLL folder which is referenced at the begining of the libpath. All other copies of the mozilla-required DLLs have been removed from the libpath apart from those inherently present in the Firefox directory.
[config.txt](https://github.com/bitwiseworks/mozilla-os2/files/183763/config.txt)

 Disabling the Flash plugin does not help - I have not tried with any of the other plugins.

I did come across similar reports on the web but they were all from far-eastern countries and the google translations were not very helpful.

**Comment by SilvanScherrer** [comment]
https://github.com/bitwiseworks/mozilla-os2/releases/tag/FIREFOX_38_2_1esr_RELEASE_OS2_Beta_6
has a link to the dbg symbols.
I wonder if you followed the fontconfig part really. As you seem to have it installed by hand and not rpm, you need to take care of some env variables. I hope this is described at the Warpzilla page.

**Comment by Rahere2** [comment]
Have installed symbol files and re-created the .trp file.

I believe I have followed the installation process correctly but am unsure what you are refering to with the environmental variables.

I note that fonts.conf should be in my unixroot\etc directory but it is not (my unixroot is G:\programs\clamav; boot drive is C:\) - is this a problem?

I get the same result and trap file 
[005A_01.txt](https://github.com/bitwiseworks/mozilla-os2/files/183954/005A_01.txt)
with Thunderbird 38.6

**Comment by SilvanScherrer** [comment]
bootdrive and unixroot can be on different drives. But as long as you don't have a fonts.conf file ffox will not work. fontconfig really needs this file. At the Warpzilla page should be some references how to install fontconfig by hand.
We strongly don't recommend it. rpm just does the job a lot better. And with ANPM (Arca Noae Package Manager) it has a nice gui.

**Comment by Rahere2** [comment]
Progress, thanks to your good self. Have created the directories needed for fontconfig and no longer get traps with xul.dll. Also, Thunderbird 38.6 now loads and performs fine (so far). But FF will still not load properly. It now produces an on-screen message "XML parsing error:undefined entry. Location: chrome://mozapps/content/extensions/update.xul <wizard id="updateWizard" ^" Any ideas?

**Comment by SilvanScherrer** [comment]
did you install to a new directory? do you run firefox while tb is running?

**Comment by Rahere2** [comment]
Yes. I renamed my firefox directory "OldFirefox" and installed 38.2 into a new Firefox dir (I did similarly with Thunderbird). I then reset the Internet I
[0037_13.txt](https://github.com/bitwiseworks/mozilla-os2/files/185752/0037_13.txt)
ntegration.

I have tried moving the existing Home\Default\Mozilla directory to the drive root and starting the new Firefox in case there was a problem there. FF would not run but now gave me a different trap (attached) instead of the on-screen error message. It did however recreate the default\mozilla\firefox directory. On deleting the new default\mozilla direcory and replacing it with the original, I got the same on-screen message, so at least the failure is consistent!

I normally run TB and FF together with no problem using Run! but TB 38.6 will not run alongside FF 38.2.

**Comment by dryeo** [comment]
On 03/23/16 03:12 AM, Rahere2 wrote:
> I normally run TB and FF together with no problem using Run! but TB 38.6
> will not run alongside FF 38.2.

What is your RUN! command?
Try using firefox!lg.exe and thunderbird!lg.exe

**Comment by Rahere2** [comment]
Thank you. FF still does not run, but now gives me the attached
[FIREFOX!.txt](https://github.com/bitwiseworks/mozilla-os2/files/187849/FIREFOX.txt)

 log message

**Comment by SilvanScherrer** [comment]
what addons did you have installed? did you try with a clean/new profile?

**Comment by Rahere2** [comment]
Addons are icedtea 1.3.0.0, mplayer 1.0.0.1, proxy plugin 1.0.0.1, shockwave flash 0.4.2.0 and warpvision 1.0.0.1. I tried disabling flash (but not the others) but it did not have any effect. 

I moved my mozilla directory from home/default and re-ran FF 38.2. It recreated the mozilla/firefox dir but would still not run.

**Comment by dryeo** [comment]
Try starting in safe mode,
firefox!lg.exe -safe-mode

**Comment by Rahere2** [comment]
Tried safe mode - the log from FF! changed to only say that DIVE could not be enabled, but FF still would not load. I also tried moving all of my plugins out of the PATH but that made no difference.

I have installed ECS2.2 on a separate drive and tried running FF 38.2 after instatting all the DLLs and fonts.conf with the same result.

I note that my config.sys in both ECS installations SET's ETC to C:\MPTN\ETC. Could this be causing a problem with fonts.conf which is at present in G:\ETC\FONTS (Unixroot is G:\)?

**Comment by dryeo** [comment]
On 03/26/16 03:21 AM, Rahere2 wrote:
> Tried safe mode - the log from FF! changed to only say that DIVE could
> not be enabled, but FF still would not load. I also tried moving all of
> my plugins out of the PATH but that made no difference.

OK, was wondering if it was SNAP related. BTW, what hardware are you using?

>
> I have installed ECS2.2 on a separate drive and tried running FF 38.2
> after instatting all the DLLs and fonts.conf with the same result.

If you're using eCS2.2, then the RPM/YUM environment is set in your 
environment. You should really use it to install all the needed DLLs and 
put @UNIXROOT\usr\lib (change @UNIXROOT to the drive letter) at the 
front of your LIBPATH as it seems something isn't installed quite right.
The Arca Noae Package Manager makes it nice to do.

>
> I note that my config.sys in both ECS installations SET's ETC to
> C:\MPTN\ETC. Could this be causing a problem with fonts.conf which is at
> present in G:\ETC\FONTS (Unixroot is G:)?
>

No, that shouldn't matter.
Try running fc-list.exe (from the fontconfig package). You should get a 
list of your installed fonts, perhaps after a minute of high CPU. If not 
something is broken in your Fontconfig setup.
Dave

**Comment by Rahere2** [comment]
Thank you for pointing me in the right direction - the problem lay in my not having (unixroot)\usr\lib in my libpath. 38.2 now loads without problem (so far!)

It uses my old bookmarks and cookies but my saved logins and passwords are defeating it, even though I can see them clearly with sqlitebrowser.exe. Is this a recognised bug or do I need to change anything?

**Comment by dryeo** [comment]
On 03/27/16 04:04 AM, Rahere2 wrote:
> It uses my old bookmarks and cookies but my saved logins and passwords
> are defeating it, even though I can see them clearly with
> sqlitebrowser.exe. Is this a recognised bug or do I need to change anything?

Yes, it is a known bug that is now fixed, see #157 and #101
