### ISSUE TITLE
Firefox 38 OS/2 crashes when starting before drawing window

### ISSUE THREAD

**Issue by MartinVieregg** [bitwiseworks/mozilla-os2#169]
I cannot start Firefox 38. I have got another machine where it works fine. I have copied all dlls (incl. YUM directories) to the new computer, but I get the attachted error messages when starting firefox.exe with -console parameter.

![firefox38-console-output](https://cloud.githubusercontent.com/assets/18749886/14935138/7d99dafa-0ec7-11e6-9742-58f132bf70af.gif)

**Comment by dbanet** [comment]
Most likely, user error.

Read the corresponding manual page on how to install fontconfig.

**Comment by dmik** [comment]
It seems that you miss `/@uniroot/etc/fonts.conf` and friends. Generally, RPM/YUM is NOT designed to be copied over on another machine. Please either copy the whole contents of your OS/2 boot drive or install RPM/YUM from the bootstrap archive (if it's not already there) and install all necessary packages with yum.

**Comment by MartinVieregg** [comment]
I have solved the problem. Two things were missing: the /etc directory and two entries in the config.sys:
SET UNIXROOT=H:
SET TERM=os2

Now it works.
