### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/mozilla-os2#174]
;-)

Please correct reference to "Arca Nova Package Manager" to read "Arca Noae Package Manager" on the beta 7 wiki page. We don't want people to think that there is a competitor in the OS/2 space...!

Nice build, Dmitriy. I ran the Arca Noae Package Manager Quick Install to paste in the prerequisites, and FF came right up.

**Comment by SilvanScherrer** [comment]
This is exactly what I meant with: prove read our documentation :) I fixed it now.

**Comment by dmik** [comment]
Ups. Pardon me. Fixed this in README.OS2 as well (bf7ee1e4fecaa5e75a6073b29a77edfbbcb1868b). Though the "New Boat" is also a nice name for a company :)
