### ISSUE TITLE
Refresh firefox question always appears

### ISSUE THREAD

**Issue by dazarewicz** [bitwiseworks/mozilla-os2#177]
Even though I use Firefox every day, every time I open Firefox now, a question appears in the footer that says: "It looks like you haven't started Firefox in a while. Do you want to clean it up for a fresh, like-new experience? And by the way, welcome back!"

**Comment by dmik** [comment]
I have it too, this needs some research as I'm not 100% sure it's a bug, it may be some bug-o-feature that somehow measures your profile's "health". Here it helps if I do what it asks and let it refresh my profile (the old profile is stored in a folder on the Desktop but you better back it up manually as well before pressing the button, just in case — my profiles are test ones anyway so I don't care if I lose anything during this operation).

**Comment by LewisR** [comment]
Hi...

This is a known (sort of) issue, and does not only affect us (though I was at a loss to find a bug for it). Try clearing history, cache, & cookies. It seems like the timer is keying on something in the history db, and this isn't getting properly upgraded when moving to the new version (just a WAG; I haven't looked at it closely, as clearing the above seems to have resolved it on four machines for me, under various OSes).

**Comment by LewisR** [comment]
Some more pointed searching led me a workaround (if the above does not do it) as described here: http://miroslav.suchy.cz/blog/archives/2014/05/13/how_to_disable_reset_prompt_in_firefox/index.html

and which really involves creating a boolean in prefs.js:

browser.disableResetPrompt

and restarting.

It looks like last rest time is to be stored in times.json, but I'm not clear when that started, nor have I checked to see what happens if times.json does not exist in the profile (i.e., is the assumption made that the profile has not been used in 60 days, triggering the nag?).

I have a few more references for this, now, so the next time I see it while testing, I'll take a closer look for a real fix before working around it.

**Comment by dazarewicz** [comment]
Thanks, setting that boolean took care of it. That's good enough for me.  I didn't really want to "refresh" as that would remove things that I really wanted to keep, and don't have the time to re-setup.

**Comment by LewisR** [comment]
There are lots of bug comments in the Mozilla Bugzilla from us regular users who find the idea of using an elephant gun on a live profile abhorrent. I'm thankful that the SeaMonkey guys seem to be remaining level-headed with stuff like this.

Glad that worked. I'll drop Steve W a note about adding that as a tip to his page.

**Comment by dryeo** [comment]
Remove the parent.lock file in your profile to fix.

**Comment by dazarewicz** [comment]
Removeing parent.lock also worked. Thanks.

I guess this doesn't really need to be a ticket, then.

**Comment by LewisR** [comment]
Yes, parent.lock was it. I just saw this happening again, and was investigating. That's the real fix. Thanks, Dave.

**Comment by dmik** [comment]
Okay, I'm closing this as not an OS/2-related bug.

**Comment by SilvanScherrer** [comment]
Firefox can offer to reset a user's profile if it hasn't been used for 60 days.

You can create a new Boolean pref with the name browser.disableResetPrompt and set its value to true to disable this notification.

Type about:config in the location (address) bar and press the Enter key to open the about:config page like you open a website by typing the URL in the location bar.

    if you see a warning message then you can confirm that you want to access the about:config page. 

A new preference can be created via the right-click context menu (New -> Boolean).
