### ISSUE TITLE
Cannot drag and drop (D'n'D) contact from one address book to another under SM 2.35a2

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/mozilla-os2#178]
[If this is not the right place to open SM or TB-specific issues, please advise.]

After upgrading (I did not test 2.35a1, as it would not start for me) from the previous build (2.28), I find that I can no longer drag and drop contacts between address books (invalid pointer is shown). I have confirmed that the .mab is not flagged hidden (known xplat issue), and that otherwise, reading/writing to both address books works as expected.

I also tested with a clean profile, no extensions, and no entries in either address book, by creating a single entry. It would not drag, though under 2.28, it did.

**Comment by dryeo** [comment]
Confirmed with a newer build. Error console says,
Timestamp: 06/06/16 02:19:07 PM
Error: ReferenceError: kAllDirectoryRoot is not defined
Source File: chrome://messenger/content/addressbook/abDragDrop.js
Line: 103

I'll investigate

**Comment by LewisR** [comment]
Sorry for not including the error console output, Dave.

**Comment by dryeo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1202553
With the fix being http://hg.mozilla.org/comm-central/rev/66e1d27612ea
I'll add this fix for the next build. I guess I should check Bugzilla 
more, SM was really suffering for a while between hardware issues and 
lack of developers.

**Comment by LewisR** [comment]
Thanks, Dave.

Suffering vs "thankfully not swapping out huge portions of code" are not necessarily synonymous. ;-)

**Comment by dryeo** [comment]
Seems to be working here now that Suite has the right declaration.
This issue can be closed.

**Comment by SilvanScherrer** [comment]
Closed per request from Dave
