### ISSUE TITLE
Unresponsive script when opening gmail.com from Mozilla OS2 browsers

### ISSUE THREAD

**Issue by edovila** [bitwiseworks/mozilla-os2#179]
Since about a month ago, when starting gmail from any OS2 browser, including Firefox 38.8 the CPU goes to 100% and after a while you may get the attached message:

This happens in different computers and versions of OS2, including MCP2 and ECS 2.2.

Running Windows XP or Vista Firefox runs OK.

Though this is probably caused by Google changing its code, it is desirable that Mozilla OS2 versions perform as well as those of Windows.

Eduardo Vila Echagüe
![gmailscript](https://cloud.githubusercontent.com/assets/19859292/15968751/145122fc-2efb-11e6-978b-fc2e1c0ad394.gif)

**Comment by herwigb** [comment]
I am using Firefox 38.8 on OS/2 with GMail on a daily basis and I do not see this.
Have you tried with a new profile or all addons disabled?

**Comment by dryeo** [comment]
Try safe mode, Help-->Restart with Add-ons Disabled or such.
As a workaround you can always try the basic view (load basic HTML) 
which I usually use for bandwidth reasons.

**Comment by ydario** [comment]
I have the same issue, but usually after 5-10 seconds the CPU loads gets normal and I can start typing.

**Comment by dmik** [comment]
I believe that this issue is a bit different than what we have in FF 45. I haven't seen Unresponsive script errors since very long here, neither with FF 38, nor with FF 45.  created a new issue for it (#248) and closing this one as I guess it has gone.
