### ISSUE TITLE
Places.sqlite is not finalized on Firefox close

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/mozilla-os2#181]
Since FFv4, we've used a write ahead log to speed up atomic operations on places.sqlite,rather then a journal, namely places.sqlite-wal, see https://www.sqlite.org/wal.html. Upon closing Firefox (and other Mozilla apps) this should be finalized, eg places.sqlite-wal should be committed to places.sqlite. This stopped working with FFv31, whereas shutdown used to peak the CPU for a couple of seconds with a bunch of disk io before all memory was released and shutdown was completed, with FFv31 and v38, shutdown happens very fast and the places.sqlite-wal file is left in the profile.
Whether from this exact problem or a related problem, one result is that session restore is not as accurate as it was before FFv31. Pages that should be cached are reloaded and often rather then starting from close to the point in the page that was displayed on shutdown, the page is displayed at the top of the page. This is perhaps most obvious on a crappy connection such as my dial-up.
Another observation is that Sqlitebrowser will not open a current places.sqlite but if you use FFv24 or older to access your profile and then shutdown the browser, sqlitebrowser will then access it.

**Comment by dryeo** [comment]
Finalizing seems to be back to working with 45ESR. At least I haven't seen a wal file after shutting down Firefox or SeaMonkey and there is CPU activity when closing the app.
I'll close this for now.

**Comment by dmik** [comment]
Good to know that.
