### ISSUE TITLE
Trap while scrolling web page with 38.8.0 Beta 7

### ISSUE THREAD

**Issue by michaelsnyder** [bitwiseworks/mozilla-os2#183]
New profile created about a week ago.  No flash installed.  Everything that can be updated with Arca Noae Package Manager was updated just before computer was rebooted.  This page loads, but when I scroll to read it, Firefox quits.
http://patriotupdate.com/major-newspaper-suggests-trump-coup-assassination/

[0044_01.txt](https://github.com/bitwiseworks/mozilla-os2/files/376178/0044_01.txt)

**Comment by LewisR** [comment]
Hi, Michael...

Quick suggestion: Update your Exceptq build to the latest. While this is available via RPM, the latest is at warpcave.com (we should build the newer package for the repo).

FWIW, I am not seeing a crash under SeaMonkey 2.35b7, using SNAP and with no dlls loading high. I have not tried this under FF, yet. (Like you, no Flash - anywhere.)

Are other pages on patriotupdate.com loading and scrolling for you? Any problem dismissing the popups after waiting through the timeout? I wonder if this is somehow related to the adverts on the right of the page (are you using any type of blocking?). Tried it in safe mode, just for kicks?

**Comment by michaelsnyder** [comment]
Here's another one today.  Firefox disappeared while scrolling, but left this trap file.  Page was:  http://money.cnn.com/2016/07/29/news/economy/venezuela-decree-farm-labor/
This seems to happen when you attempt to scroll the page while it is still loading something, usually a video that you might not even know is on the page.  The video on this page is obvious, but some aren't.  If I wait until the page has loaded everything on the page, it does not trap.  This report says that the trap was in xul.dll, but a previous one this morning on a different page said that it was in libc066.dll.  This is a nuisance because you can't always see that the page has not completely loaded before you try to read it unless you monitor the information on the lower left-hand corner to see whether anything is loading before you try to scroll.
[20160730.TXT](https://github.com/bitwiseworks/mozilla-os2/files/391889/20160730.TXT)

**Comment by StevenLevine** [comment]
The .trp file makes it pretty clear how the exception occurred.  The js garbage collector is attempting to access a null pointer or more accurately a partially initialized object.  This may actually be a cross-platform defect.  That others can not easily replicate the exception is not unexpected.  It's clearly timing related.
0x1000 is probably ArenaSize and the code is attempting to update some sort of in-use count.
My current guess is that the trap is at:
jsgc.cpp:1061
    aheader->zone->usage.removeGCArena();
and that zone is null.
The .trp file content does not look quite right.  I recommend you go to http://www.warpcave.com/betas and install http://www.warpcave.com/betas/exceptq-7.11.3-shl-2016-07-27.zip.  Your exceptq is somewhat antique and the newer releases fix some issues with decoding .dbg file content. 
 Also, when you see a line like:
 029CFF48  1F790711   LIBC066   0001:00050711
which is missing Nearest Public Symbol information, you should try to find the matching .xqs, .sym or .dbg file for the module.   The developers will appreciate this.
 For libc066.dll, you need
  http://www.warpcave.com/symbols/libc066_xqs-sym-20141026.zip
Install the .xqs file in the director where you have libc066.dll installed.  You do not need to install the .sym file.

**Comment by LewisR** [comment]
With YUM and/or ANPM installed (you mentioned that you used ANPM to update all dependencies to the latest versions, Michael), you may install the libc-debug package from the Netlabs stable repository.

**Comment by michaelsnyder** [comment]
On 07/30/16 at 10:44 AM, Lewis Rosenthal <notifications@github.com> said:


>With YUM and/or ANPM installed (you mentioned that you used ANPM to
>update all dependencies to the latest versions, Michael), you may install
>the libc-debug package from the Netlabs stable repository.

OK.  Thanks.  Maybe the next .trp file will be more informative.

-- 
_________________________________________________________________________
"Politics is the art of looking for trouble, finding it everywhere, diagnosing it incorrectly and applying the wrong remedies. - Groucho Marx
"Islamophobia: that last look of fear in your eyes just before your head comes off." - Donna Driscoll November 16, 2015

Mike Snyder
msnyder1@cfl.rr.com

**Comment by michaelsnyder** [comment]
On 07/30/16 at 09:47 AM, StevenLevine <notifications@github.com> said:


>The .trp file makes it pretty clear how the exception occurred.  The js
>garbage collector is attempting to access a null pointer or more
>accurately a partially initialized object.  This may actually be a
>cross-platform defect.  That others can not easily replicate the
>exception is not unexpected.  It's clearly timing related. 0x1000 is
>probably ArenaSize and the code is attempting to update some sort of
>in-use count. My current guess is that the trap is at:
>jsgc.cpp:1061
>    aheader->zone->usage.removeGCArena();
>and that zone is null.
>The .trp file content does not look quite right.  I recommend you go to
>http://www.warpcave.com/betas and install
>http://www.warpcave.com/betas/exceptq-7.11.3-shl-2016-07-27.zip.  Your
>exceptq is somewhat antique and the newer releases fix some issues with
>decoding .dbg file content. 
> Also, when you see a line like:
> 029CFF48  1F790711   LIBC066   0001:00050711
>which is missing Nearest Public Symbol information, you should try to
>find the matching .xqs, .sym or .dbg file for the module.   The
>developers will appreciate this.
> For libc066.dll, you need
>  http://www.warpcave.com/symbols/libc066_xqs-sym-20141026.zip Install
>the .xqs file in the director where you have libc066.dll installed.  You
>do not need to install the .sym file.

What a helpful reply, as usual!  I got the .xqs file in the right place,
but I installed exceptq with the ANPM.  I've no idea where it put all of
the pieces.  BTW, apparently whatever it accesses when it installs exceptq
is not up to date. ANPM reports that 7.11-9 is the current version.  Could
someone fix that for those who depend on ANPM, Warpin, etc. to help us?

Thanks, Steven.

-- 
_________________________________________________________________________
"Politics is the art of looking for trouble, finding it everywhere, diagnosing it incorrectly and applying the wrong remedies. - Groucho Marx
"Islamophobia: that last look of fear in your eyes just before your head comes off." - Donna Driscoll November 16, 2015

Mike Snyder
msnyder1@cfl.rr.com

**Comment by dryeo** [comment]
On 07/30/16 05:25 PM, michaelsnyder wrote:
> but I installed exceptq with the ANPM. I've no idea where it put all of
> the pieces.

Simplest is to unlock @UNIXROOT\usr\lib\exceptq.dll and then copy and 
overwrite distorm.dll, distorm.xqs, exceptq.dll and exceptq.xqs in 
@UNIXROOT\usr\lib. They'll get updated or more likely replaced with the 
same versions next time there is an updated exceptq package available.

**Comment by LewisR** [comment]
>BTW, apparently whatever it accesses when it installs exceptq is not up to date. ANPM reports that 7.11-9 is the current version. Could someone fix that for those who depend on ANPM, Warpin, etc. to help us?

Ask, and ye shall receive (well, almost):

http://trac.netlabs.org/rpm/ticket/194

In all fairness, while the package at netlabs-rel isn't all that current, Steve just packaged 7.11.3 (based upon the date), so we can't be too hard on our friends who run the build bot. ;-)

**Comment by StevenLevine** [comment]
I happened to be discussing some of the finer points of FORK_EXCEPTQ with
Dmitriy and Silvan last night and mentioned 7.11.3.  Thanks for the
ticket.

**Comment by LewisR** [comment]
If there's no ticket, then nothing's missing. ;-) This is essentially how we've gone so long since the last RPM release.

**Comment by SilvanScherrer** [comment]
Please try with latest Firefox 45.

**Comment by dmik** [comment]
I don't see this problem with FF 45, so chances are great that it has gone by fixing something upstream or with the new FFmpeg integration (there is a lot of video decoder debug output, if enabled, while scrolling through the reporter's pages). I will close it and the reporter is free to reopen if it happens again.
