### ISSUE TITLE
Broken Japanese text display on EUC-JP encoded pages

### ISSUE THREAD

**Issue by altsan** [bitwiseworks/mozilla-os2#185]
After upgrading from Firefox 31.8.0 to 38.8.0, display of Japanese characters on EUC-JP encoded web pages no longer functions properly. 

Specifically, several characters including the CJK period and the long-vowel kana are replaced with substitution marks.  I have tried several different Japanese fonts and all exhibit this problem on 38.8.0 (whereas 31.8.0 displays correctly using the same configuration).

Here is what the website os2.jp looks like in Firefox 38.8.0:
![firefox38-os2jp](https://cloud.githubusercontent.com/assets/5803995/17461120/608c7b10-5cbb-11e6-9c45-e173d5673b0a.png)

For comparison, here is the same site in Firefox 31.8.0, taken from the same system, using the same profile:
![firefox31-os2jp](https://cloud.githubusercontent.com/assets/5803995/17461119/6089e9ae-5cbb-11e6-9805-5619ed0a19e5.png)

**Comment by dmik** [comment]
I can confirm that.

**Comment by altsan** [comment]
I've discovered that this problem also occurs with ISO-2022-JP encoding. This is rather more of a problem, because I need to read quite a lot of correspondence and other documents in ISO-2022-JP...

**Comment by ak120** [comment]
It's broken for all native OS/2 encodings at least since 38.0. And not only at OS/2 platform.

**Comment by dmik** [comment]
Yes, they've been removing "outdated" encodings recently (this includes cp850, some Japanese, some Chinese/Taiwan etc) and I already had several rounds of restoring them. May be it broke again after some update. I will look at it later.

As far as I recall, these encodings are not part of some Web standard or so, that's why they are being removed upstream. I need to re-check that again.

**Comment by altsan** [comment]
That seems very strange if so.  These are standardized encodings of very long standing, especially EUC-JP which historically is the standard encoding for Japanese on Unix systems (other than Unicode encodings). Both EUC-JP and ISO-2022-JP are almost certainly more widely used than UTF-8 on both Japanese web sites, and in email.

**Comment by ak120** [comment]
I don't know what dmik means by "Web standard". Maybe he can give a hint where to find it in official standard documents from DIN or ISO? I don't know about Государственный Стандарт? Btw. web content can be in very different formats. Not only HTML documents with specific charsets. What's about MIME in e-mail messages for example. With the latest firefox beta it's no longer possible to read correctly a simple text file from an OS/2 web server. And for opening a local text file Netscape is still more useful and 100 times faster.

**Comment by dmik** [comment]
@ak120 you are a really strange person :) Don't blame me please, blame Firefox developers. And also read https://github.com/bitwiseworks/mozilla-os2/issues/149. In particular, Firefox guys refer to this document: https://encoding.spec.whatwg.org/#encodings (this document also mentions ISO-2022-JP in many places). I believe I found this information by backtracking to the respective Mozilla bug when analysing removal of the encodings in question in the upstream repository.

**Comment by ak120** [comment]
I don't blame anybody and also read your postings. The referred documentation seems to be some random text from the web definitely not issued by a standardisation gremium. The main problem that remains: All user-interface controls for selecting IBM850 or similar stuff are missing now. about:config in combination with profile acrobatics is not an user-friendly way. For firefox it may be not a big issue, it becomes worse in Seamonkey or Thunderbird, where it's no longer possible to define a appropriate charset for each newsserver or mailserver. Also fallback charset option offers only a small choice. I noted before that the same problems occure with Windows mozilla applications (later than Seamonkey 2.9.1 or similar Firefoxes). Also the annoying double-click for word selection with trailing space is still existing on both platforms. Спасибо!

**Comment by altsan** [comment]
OK, I think ak120 is talking more about the issue described in #149. 

This ticket was opened to address broken decoding for certain charsets which _are_ still nominally supported.

**Comment by ak120** [comment]
Of course I cannot deny that #149 is part of the problem. But it's simply not everything. I already opened a ticket at Dave's bitbucket repo for the seamonkey stuff long time ago. For me there are just two simple questions:
1. Which list of character encodings is supported?
2. Is every supported character encoding selectable via UI?
That the character mapping suggestions from the link which Dmitri has provided cannot work in all cases is another topic.

As sm uses the same codebase, here only for illustration.
![moz-charset-m](https://cloud.githubusercontent.com/assets/17602609/23761443/1e1bf838-04f3-11e7-9e98-9710cb0bd9ca.gif)
selectable from menubar
![moz-charset](https://cloud.githubusercontent.com/assets/17602609/23761481/36b3d212-04f3-11e7-97c5-e21c6604430b.gif)
selectable from settings

**Comment by altsan** [comment]
I have tested with Firefox 45.9.0-2 (rpm version).  EUC text display is still broken as described here.

**Comment by altsan** [comment]
It occurs to me that in EUC-JP encoding, all the broken punctuation characters have a leading byte of 0xA1.

It also occurs to me that ISO-2022-JP (which I can confirm is also still broken) is probably implemented by using EUC-JP plus a translation function, since that's by far the simplest way to do it - and that's probably why it, too, is broken.

**Comment by altsan** [comment]
More accurately, ISO-2022-JP and EUC-JP both use the same translation table for JIS-X-0208 (the Japanese character set standard), since both map directly onto it.

**Comment by altsan** [comment]
I've examined the code in intl/uconv/ucvja and I believe I've discovered where the error lies.

In nsJapanesetoUnicode.cpp, the conversion algorithm for EUC-JP converts A1xx to position 8648+xx  in the gJapaneseMap[] table (in japanese.map). 

For some reason, between commit 1fd092e (Firefox 31.6, which was the last version where EUC-JP display worked properly) and 0342010 (current head), gJapaneseMap[] array entries from 8648 to 9211 have gone missing from the file.  (Running a graphical diff on the two versions instantly reveals this.)  So in practise, any lookup pointing to an offset in this range will end up going to the wrong place.  (Since both EUC-JP and ISO-2022-JP use this table, both encodings are affected.)

I suspect this difference in the file header comments contains a clue:
Current head:  /* generated by jamap.pl CP932.TXT JIS0212.TXT */
Commit 1fd092e: /* generated by jamap.pl CP932.TXT IBM943.TXT JIS0212.TXT */

It looks as though the IBM943.TXT input file was inadvertently omitted from the command that generated japanese.map.

**Comment by dmik** [comment]
@altsan Good finding! Most likely, its a merge regression. I was doing quite a complex merge in between where they a) ripped out all OS/2 code and b) changed uconv logic dramatically. I will try to look at that before GA2. You may also try to build FF yourself if you are eager :)

**Comment by dmik** [comment]
The thing is that when restoring the IBM934 stuff in 0342010c and alike, I didn't rollback the rest of the changes made to `japanese.map` when this stuff was removed by Mozilla in https://hg.mozilla.org/releases/mozilla-esr38/rev/52b0ec2f0522. Now I restored this file completely from the commit 1fd092e8 that precedes merging of esr38 (which makes it as it was in esr31) and all goes fine here with the os2.jp web-site — it looks like it did in esr31 at least.

@altsan could you please test that? The new XUL is uploaded as http://rpm.netlabs.org/test/x_t5_2.7z (you also need http://rpm.netlabs.org/test/ff45_9_0_t5.7z and put this XUL on top of it; and all-new LIBC/LIBCx etc from `neltabs-rel` RPMs).

**Comment by altsan** [comment]
Installed and tested with: 
- os2.jp site (EUC-JP encoded)
- a text file (EUC-JP encoded)
- an email message (ISO-2022-JP encoded)
All of which exhibited the problem under existing builds.

All of them now display correctly.  I think we have a winner. :)

Thank you!

**Comment by dmik** [comment]
Ok, case closed then :)
