### ISSUE TITLE
Thunderbird 38.8.0 unable to connect, following update from 17.

### ISSUE THREAD

**Issue by HDRW** [bitwiseworks/mozilla-os2#186]
I set up TB 38.8.0, with Mozilla_Home set to the same location as I've been using with version 17.
This is running under eCS 2.0.

A couple of error messages appear in the Error Console immediately:

Timestamp: 13/08/16 17:02:06
Error: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIIOService2.manageOfflineStatus]
Source File: resource://gre/components/offlineStartup.js
Line: 66

Timestamp: 13/08/16 17:02:20
Error: TypeError: tab is undefined
Source File: chrome://messenger/content/tabmail.xml
Line: 1067

and the following happens whenever I try to retrieve messages:
Timestamp: 13/08/16 17:02:28
Error: An error occurred during a connection to mail.arcanoae.com:993.

The server certificate included a public key that was too weak.

(Error code: ssl_error_weak_server_cert_key)

Since the first two are transient I have ignored them for now.
Researching the third, I have tried to set to FALSE various of the ssl3 options (initially just the ones suggested by others online, but eventually all the 128 bit ones), but with no success.

Is there a magic setting that needs changing?
Cheers,
Howard

**Comment by dryeo** [comment]
You need to read the README.OS2 for the new prerequisites. If you don't 
use the recommended YUM/RPM to install the prerequisites, go to 
http://os2news.warpstock.org/Warpzilla.html

**Comment by SilvanScherrer** [comment]
hmm long time since a update on that. I believe it was a user error. @HDRW could you verify please?

**Comment by HDRW** [comment]
I never did get this working - I had to use TB 17 or I couldn't get in.  Now I no longer need to use ThunderBird, my problem no longer exists.  If nobody else has the same problem, it can probably be closed.

**Comment by SilvanScherrer** [comment]
closing it as not needed anymore
