### ISSUE TITLE
Crash when loading FireFox 38.8

### ISSUE THREAD

**Issue by Rahere2** [bitwiseworks/mozilla-os2#194]
31.8 loads perfectly but 38.8 starts to load (to the point when I would expect the window to open) and then crashes. All dependencies installed with YUM. Unixroot set. Using ECS 2.2 beta with Acpi 3.22.03 and APIC set.. Panorama driver (shadow buffer not enabled). Exceptq always produces same report (attached). I have also attached config.sys.
[0035_01.pdf](https://github.com/bitwiseworks/mozilla-os2/files/750289/0035_01.pdf)
[config.pdf](https://github.com/bitwiseworks/mozilla-os2/files/750290/config.pdf)

**Comment by SilvanScherrer** [comment]
First of all you have a old exceptq. Please update with yum install exceptq. Then you should install the debug symbols from https://github.com/bitwiseworks/mozilla-os2/releases/tag/FIREFOX_38_8_0esr_RELEASE_OS2_Beta_7

**Comment by Rahere2** [comment]
Dear Silvan

Thanks for the speedy response and helpful guidance.

Problem has been sorted - no fonts.conf in C:\etc\fonts.

Many thanks

John Krapez

Do I reply to my submission on the bug-checker or do you?
