### ISSUE TITLE
Missing Graphic

### ISSUE THREAD

**Issue by compi7** [bitwiseworks/mozilla-os2#195]
On this page
http://meteoexploration.com/forecasts/Sierra-NevadaES/index.php?lang=en&si=Metric
is a 7 day weather forecast graphic which is not visible  in FF 38, but under win7 and FF50 it is.

**Comment by LewisR** [comment]
Hmmm... This loads fine for me under:

`Mozilla/5.0 (OS/2; Warp 4.5; rv:38.0) Gecko/20100101 Firefox/38.0 SeaMonkey/2.35 ID:20160617210117`

I'll have to try under FF 38. In fact, the images (on the other tabs, as well, including the webcam map) all load just fine, and this is on a ThinkPad T43 with 2GB RAM and running a bit low on shared memory (22? tabs open). Are you running any kind of ad blocker? Have you tried accessing the page in safe mode, just to be sure that you don't have an errant extension?

**Comment by compi7** [comment]
I disabled the ad blocker for that page and now I have a funny result. 
See the pictures.
What do you mean by accessing the page in safe mode ?

**Comment by dryeo** [comment]
On 02/04/17 10:38 PM, compi7 wrote:
> What do you mean by accessing the page in safe mode ?

Go to Help-->Restart with Add-ons Disabled.

**Comment by compi7** [comment]
Thank you!
The result is the same whether you start in Safe Mode with Adblock Plus 
totally disabled or Adblock Plus just disabled for that page. The 
graphic is on the right hand side, you have to scroll right to see it.

**Comment by SilvanScherrer** [comment]
I just tried and I see the forecast. The only strange thing is, it's a bit far right. I had to use the footer scrolbar to see it.

**Comment by SilvanScherrer** [comment]
the page completely changed. So is it still an issue? At least I could not find any problems with the upcoming FFox45.

**Comment by dmik** [comment]
I don't see any problem with ESR 45 either. I will close this now and the reporter is welcome to reopen if the problem still exists for him when ESR 45 is released.
