### ISSUE TITLE
Remove MOZILLA_HOME and MOZ_PLUGIN_PATH from requirements

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#205]
These are really very old environment variables back from the days when Mozilla apps were distributed as ZIPs. Now we have RPM and such and Mozilla home should reside in HOME by default and Mozilla plugins should be searched in specific /@unixroot/usr/lib dirs.

We may keep support for these variables in as an optional way to override the defaults for compatibility with older installations but the defaults should be changed as described above (so that the user doesn't need these vars in the environment to get a correctly working Firefox).

**Comment by dryeo** [comment]
This would break every existing OS/2 installation and many upgraded 
installations. Forcing people to move their profiles, a non-trivial 
task, is a non-starter.
I'd suggest using %HOME% for new installs.
Plugins should still be searched for in the usual places, as well as 
%HOME%\mozprofiles\plugins with the lib directories searched first as 
various plugins are automatically installed in %MOZ_PLUGIN_PATH%
There is also the problem of downleveling the browser for testing 
purpose, etc.
People using SeaMonkey or Thunderbird can have very large profiles due 
to mail. My Thunderbird profile is 1.7GBs and my Mozprofiles directory 
is 2.5GB and exists on its own partition.

**Comment by dmik** [comment]
Dave, looks like you didn't read it carefully. The support for these variables is going to remain for compatibility reasons. Regarding plugins, it's more complex. A full source code analysis is required to make a decision. But again, the old variable will be considered too. New plugins will surely be also RPMized, so won't go to MOZ_PLUGIN_PATH anymore. Needless to say that plugins as we now them (NP-format DLLs and such) are going to bite the dust very soon (with or after FF 55 IIRC) making cross-browser plugins (Chrome and alike) the only supported extension mechanism.

Downleveling per se is not an issue for us at all, we don't officially support it (and will never do, I'm afraid). So it's up to the user to sort such kind of things out. But we will

**Comment by dryeo** [comment]
The title of the issue is, or was "Get rid of MOZILLA_HOME and 
MOZ_PLUGIN_PATH from requirements" which I may have misread, missing the 
requirements part and your second paragraph did start with "We may keep 
support...". Happy that you will keep them.
Plugin search is pretty basic, check %MOZ_PLUGIN_PATH%, 
%MOZPROFILES%\plugins and last program_directory\plugins for a plugin.
NP type plugins are still supported on the 52ESR branch, only Flash on 
52+. After 52, Rust is a hard requirement and porting it would be 
non-trivial as it depends on CLANG and the development seems very broken.
The one plugin I still use, awgets npawgbin.dll, is open source and the 
installer is just a rexx script, so easy enough to modify.
As for downleveling, handy for checking the behaviour of the current 
version vs last version, important here as I try to figure out which 
patches to back port to the never released SM 2.42.

**Comment by SilvanScherrer** [comment]
@dryeo I'm not sure if it's worth to downlevel anything atm. We are already considering to go straight to 52 the next days. Which should not take too much time. But all depends also a bit on how fast we solve this python issue from #142

**Comment by dmik** [comment]
@dryeo Sure, having several versions is handy for testing and such but you can always take a ZIP. But officially we only support one version - the latest. For obvious reasons.

**Comment by dmik** [comment]
In 7674a41f1a59557f0a3ab2359b4668b60ba4ae0a I made firefox.exe set BEGNLIBPATH/LIBPATHSTRICT before loading XUL.DLL so now it starts isolated and will launch by full path from any dir w/o the need for run! or a cmd wrapper. Later I will make it search XUL.DLL in UNIROOT locations in addition to the firefox.exe dir (which is the legacy behavior).

**Comment by SilvanScherrer** [comment]
see also #148 for the HOME env var discussion.

**Comment by dmik** [comment]
BTW, MOZ_PLUGIN_PATH is a cross-platform setting intended to override application-, user- and system-level plugin directories so it should be kept in place. Instead, I will add support for a system-level plugins directory on OS/2. It will be `/@unixroot/usr/mozilla/plugins`, similar to other systems. And this is where plugin RPMs should install them.

**Comment by dmik** [comment]
With the two commits above, this issue may be considered as fixed. Now we support pure RPM/UNIXROOT installs without MOZILLA_HOME (HOME will be used instead) and/or MOZ_PLUGIN_PATH (`/@unixroot/usr/mozilla/plugins` will be used instead).
