### ISSUE TITLE
Firefox45ESR: https (ssl) issues

### ISSUE THREAD

**Issue by wztest** [bitwiseworks/mozilla-os2#206]
Firefox starts ok and there nothing in the console error log that it can't init the security sub system and thus https isn't working = unknown protocol. "Check to make sure your system has the Personal Security Manager installed."
All dlls are in place and there is nothing missing, related files are from 23th of February 2017. And these kind of dlls were part of Firefox in older releases.

**Comment by SilvanScherrer** [comment]
something is probably wrong on your system, but what. How did you install the requirements? By rpm?

**Comment by wztest** [comment]
yes question is why :-) Ii just checked some more things and its maybe related to the nss package (nss-3_23_0-4_oc00.zip) because nss3.dll can't load correctly but others are fine. Will try to get a fresh setup on another system running and check again.

**Comment by SilvanScherrer** [comment]
do you get a message why nss3.dll can't be loaded? Or what exactly messages you get/see?

**Comment by wztest** [comment]
Yes, it was a load error, this is now gone when I installed dependent nss files again. All is ok when testing with chkdll32. Firefox itself also tells that it somehow could load NSS:
<img width="342" alt="nss_lib_info" src="https://cloud.githubusercontent.com/assets/6126421/26457780/4292d0f8-4169-11e7-8690-d63cc3123391.png">

Must be something else then, still getting this when trying to open https sites:

Unexpected response from server
Firefox doesn't know how to communicate with the server.
    Check to make sure your system has the Personal Security Manager installed.
    This might be due to a non-standard configuration on the server.

**Comment by wztest** [comment]
This might has something todo with the profile, when i open the cert manager is completely emty.
It is like always a fresh profile created inside the firefox program dir. When i go there it looks a little bit emty:

blocklist.xml
Cache
cache2
compatibility.ini
content-prefs.sqlite
cookies.sqlite
datareporting
gmp
mimeTypes.rdf
OfflineCache
parent.lock
permissions.sqlite
places.sqlite
prefs.js
search.json.mozlz4
sessionCheckpoints.json
startupCache
times.json
xulstore.json
_CACHE_CLEAN_

**Comment by dryeo** [comment]
On 05/25/17 10:21 AM, wztest wrote:
> This might has something todo with the profile, when i open the cert
> manager is completely emty.

Have you tried a new profile? Many problems are actually profile 
problems and should always test with a new profile

**Comment by wztest** [comment]
New install = new profile. I created a new profile just yesterday without a change. What is also strange is that importing certs don't work either, no error message nothing.

**Comment by SilvanScherrer** [comment]
as it seems you use a zip based installation for the requirements, where did you but the dll? How do you start firefox? With Run or firefox.exe? What other apps are running while you try firefox? could you try on a fresh install with rpm based installation? Or do you have ArcaOS to try?

**Comment by wztest** [comment]
@SilvanScherrer 
Dlls are in \os2\dll and i start firefox with a .cmd file that will disable the highres timer and set beginlibpath to the dir where firefox.exe is started from.
I have another system with yum, but there yum is the problem: table packages not found

**Comment by SilvanScherrer** [comment]
I really think your setup is broken or such. Within some days we will have a new ffx45 out with fixes. Lets try again then, as there was a BEGINLIBPATH fix. In the meantime please try to fix your yum/rpm env. Best would be to open a ticket at netlabs about whats broken. So we might give you hints about how to fix it.

**Comment by wztest** [comment]
@SilvanScherrer  Will look forward in case some update for the current FF45 are ready. There is an issue yes but FF38 runs without a problem. About yum, will do a cleanup and then check again when it is still not ok will open a ticket.

**Comment by SilvanScherrer** [comment]
any news on that?

**Comment by SilvanScherrer** [comment]
as there is no news on that since a month and we strongly believe it's a user error, I close the issue. Feel free to reopen, if you have new informations to add.
