### ISSUE TITLE
Arca Noae: hunspell unknown; libjpeg-turbo uknown

### ISSUE THREAD

**Issue by waltgregg** [bitwiseworks/mozilla-os2#209]
Dmitriy: This isn't exactly an 'issue' but there seems to be no other feedback method.  I'm trying to get FF45 for OS/2 that you released yesterday running.  But I'm 61 and this stuff is at the outer limits of my competence.  And there are bits of installation that aren't working for me. 

When you put put out FF38 I learned to install and use Arca Noae package manager (ANPM).  I've had pretty good luck with FF38.  But there are glitches with installing FF45 on my ECS 2.1. 

First, ANPM did not list any 'hunspell'.  It did list some 'hunspell-en' dictionaries , but they won't install for want of hunspell itself.  I never even heard of hunspell and have no idea where to get it.  It's not listed in Hobbes.NMSU.EDU. 

Second, ANPM did not list any 'libjpeg-turbo'.  Here I did find a 'libjpeg-turbo-1.4.2' on Hobbes.NMSU.EDU.  That lists a bunch of ANPM updates which I was able to do.  But it doesn't say what to do next.  I just copied 'jpeg8.dll' and 'turbojp0.dll' to my %unixroot%\usr\lib directory in the faint hope that this might satisfy Firefox. But no luck finding out, because Firefox can't find hunspel0. 

I'd really like to try your recent FF45 release.  But it's just a wee bit beyond me, it seems.  Any advice would be appreciated. Thanks.--  Walt. (I'll check back here if I can find this place again, but an email to my name at domain gregg.juneau.ak.us would be even better.  Bye! )

**Comment by SilvanScherrer** [comment]
This is because you most probably didn't have the experimental repository enabled.
We now moved those 2 rpm to the release repository and in some minutes they should be available.
And don't use the older libjpeg-turbo. Please use the rpm one.

If it still is not working after installing them reopen the issue please.
