### ISSUE TITLE
Loss of control with full screen HTML5 video (YouTube) FF 45.5

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/mozilla-os2#211]
Opened YouTube video (no Flash installed). Audio played as expected. Video played as expected in window. However, upon selecting the option to expand the video to fullscreen, window started to expand then video stopped (audio continued to play). Pressing Esc did not return to windowed mode. Ctrl-Esc and returning to the desktop got back to a browser window which could be closed, but otherwise would not accept input.

This works fine under 38.8.

ArcaOS 5.0 fresh install, with all prerequisites met.

**Comment by dmik** [comment]
This is fixed by 9e6237b as well.
