### ISSUE TITLE
Update to ESR 45.9.0

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#217]
This is the latest ESR 45 version with fixes etc. Makes sense to bring it in since we need to do an RPM release anyway (see #142).

The URL of the release: https://hg.mozilla.org/releases/mozilla-esr45/rev/FIREFOX_45_9_0esr_RELEASE.

**Comment by dmik** [comment]
Done in 0cd84da1b7a90c5547945f32476998a7b4e2f0b4. There is one major change that needs our attention: changes in ExecutableAllocator.cpp. It used to be platform-dependent where we used DosAllocMem directly on OS/2 but now this part is dropped and the new code uses ProcessExecutableMemory which by default takes the Linux path on OS/2 which leads to using mmap for allocation. This isn't necessarily bad, actually there is an idea of use as much of Posix stuff as possible instead of using OS/2 APIs directly (because we provide a lot of useful workarounds in our Posix implementations which are basically duplicated in Mozilla anyway). But I need to check if the way how they use mmap is supported by LIBCx.

**Comment by dmik** [comment]
The new code uses `MozTaggedAnonymousMmap` on Linux to allocate executable memory for JS. While this function just redirects to `mmap` on OS/2 as well as on Linux, `MozTaggedAnonymousMmap` itself is not used (yet) in the code that actually gets compiled on OS/2.

After studying various places in Mozilla where memory allocation occurs (there are still many, just search for DosAllocMem) I decided that I don't want switching Mozilla to using mmap on OS/2 at this point. There are places that use some unimplemented or partly implemented functionality (like memory ,allocation at a predefined address) for which OS/2 native code using DosAllocMem directly is already in place and it looks complex enough to be blindly replaced with mmap w/o understanding what are the consequences.

Better we will have a complete switch to mmap in all places at once, with proper analyzing/testing, at some later stage, as a separate task. For now, I will just use DosAllocMem directly like ExecutableAllocatorOS2.cpp used to do.

**Comment by wztest** [comment]
Good choice to leave this big change for later when all is working ok with the new release.

**Comment by dmik** [comment]
FF 45.9.0 is successfully built and appears to work.
