### ISSUE TITLE
FF 45.5.x ESR shows incorrect memory usage in about:memory

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/mozilla-os2#221]
I do not believe this is a critical-path issue, however since we typically struggle with application memory issues on our OS/2 platform I thought I would provide some details on what I am seeing since I do not know to what extent FF itself is relying on some of this info for functions like Garbage Collection, etc.

In short, when invoking the 'about:memory' function in the browser what comes back is a built-in memory utilization (live measurement) report for the currently executing instance of the FF browser.

On my install I am seeing some incredibly large numbers, not all of them mind you, but needless to say, they simply make no sense. This behaviour of course causes issues for various add-ons which attempt to monitor tab-specific memory usage and allow you to understand which web-sites are resource heavy.

I've uploaded the extracts of what I am seeing in my current session. The web site specifics are less important than the memory usage numbers being reported, in numerous cases Gigabytes are claimed to be used, this is certainly incorrect.

The following message is displayed in the TAB report area when invoking the 'about:memory' function:

"...WARNING: the 'heap-allocated' memory reporter and the moz_malloc_usable_size() function do not work for this platform and/or configuration. This means that 'heap-unclassified' is not shown and the 'explicit' tree shows much less memory than it should..."

What is strange is that in my example the 'explicit' tree actually shows some incredibly large values, so quite the opposite of what is implied above:

"635,127.87 MB (100.0%) -- explicit"

...that literally implies 635 Gig of use...

[memory-report_live-measurement.zip](https://github.com/bitwiseworks/mozilla-os2/files/1082586/memory-report_live-measurement.zip)

[memory-report-json-ANON.gz](https://github.com/bitwiseworks/mozilla-os2/files/1082589/memory-report-json-ANON.gz)

**Comment by SilvanScherrer** [comment]
Same as #31

**Comment by dspiatkowski** [comment]
Ahh...sorry, I had not caught that..my appologies. Please go ahead and close out this particualr ticket, it is clearly a duplicate.

Thanks!
