### ISSUE TITLE
support @font-face

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/mozilla-os2#23]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=500135

**Comment by SilvanScherrer** [comment]
to have this working we probably need to enable gfx.downloadable_fonts again.

**Comment by dryeo** [comment]
On 07/03/15 05:20 AM, Silvan Scherrer wrote:
> to have this working we probably need to enable gfx.downloadable_fonts
> again.

It can always be enabled in about:config for testing purposes.

**Comment by SilvanScherrer** [comment]
sure. This was just a reminder, that we need to revert the flag when we work on this issue. Only reverting does nothing afair.

**Comment by dryeo** [comment]
On 07/03/15 08:39 AM, Silvan Scherrer wrote:
> Only reverting does nothing afair.

Firefox crashes every time it tries to load and display a webfont, so 
@font-face will need testing before reverting

**Comment by wztest** [comment]
Was this non working code touched in recent times? The old bugzilla entry for the font face bug https://bugzilla.mozilla.org/show_bug.cgi?id=500135 doesn't tell much about the code quality, maybe this time we should try to understand the win source? :-)

**Comment by abwillis** [comment]
Most often our code does follow the Windows code, however; our font code has followed more the Linux path since Cairo graphics have been being used as that is how the fonts were added into Cairo.  So it may be helpful to understand the win source but I am certainly not confident of it.

**Comment by dryeo** [comment]
Last time was pre-4. Peter started work on it just before moving on and 
Rich tried but admitted he wasn't any good with glyph stuff.
As Andy said, we probably need to follow the Linux route and I wouldn't 
be surprised if mzfntcfg needs local font support added.

**Comment by SilvanScherrer** [comment]
as #65 is done, I guess https://github.com/bitwiseworks/mozilla-os2/commit/4f06effa0171e7b24e0baa17caf7db21aa4bc4da should be backed out.

**Comment by dmik** [comment]
Silvan, please read https://github.com/bitwiseworks/mozilla-os2/issues/74#issuecomment-163355276 :)

**Comment by dmik** [comment]
BTW, another thing we should do now when we switched to the complete fontconfig port is check our default `font.*` settings (also in `all.js`). Created #146 for that.

**Comment by dmik** [comment]
Support for @font-face appears to be fully working after 63e9aeafb5cb978f60f68894d6e54fbefb366603. This is how the bottom of www.bitwiseworks.com/shop (using several @font-face attributes) now looks:

![713231299_6915356053729200347](https://cloud.githubusercontent.com/assets/900726/13019744/30906a16-d1e2-11e5-98bc-007f9dfb54a2.jpg)

Note that github.com is not a measure for @font-face anymore since they switched to SVG icons instead of web fonts in their UI.

**Comment by dryeo** [comment]
Interestingly the fonts appear on http://www.bitwiseworks.com/shop even 
without toggling gfx.downloadable_fonts.enabled to true. Using SM 2.35

**Comment by dryeo** [comment]
Actually I seem to be getting different fonts from your screenshot.
Here's how it looks in my build of FF38ESR, looks the same in SM as well

**Comment by dryeo** [comment]
The page actually shows different fonts here. Unluckily Github is acting up and not letting me attach the screenshot

**Comment by dryeo** [comment]
The page actually shows different fonts here. Unluckily Github is acting up and not letting me attach the screenshot

**Comment by dmik** [comment]
This is how the page looks with `gfx.downloadable_fonts.enabled` set to `false` here (note that not only you get wrong icons but also the font used for the headers (Store Information, Follow us) is different:

![2016-02-13 14 41 52](https://cloud.githubusercontent.com/assets/900726/13027414/7b5661ee-d260-11e5-8eaa-1188e96d00bb.png)

If changing `gfx.downloadable_fonts.enabled` doesn't make any difference for you then either you have the required fonts locally available or something else is broken in your setup.

BTW, you can enable logging for the user fonts module with ` export NSPR_LOG_MODULES=userfonts:9`.

**Comment by dmik** [comment]
Note that I also re-enabled downloadable_fonts by default in a8aebd900bf73a98de60268f7ee21bcdf83361f6.

**Comment by dryeo** [comment]
3 different systems (2 different %HOME%0, 3 slightly different renderings of the above, none of which look like your screenshot. I'll try attaching one again.
https://archive.org/details/softwarelibrary_win3 also only displays the missing glyph boxes.
I guess have to wait for the same library versions as you're using for better comparison.
file:///F:/EMBLSH/font_face.png

**Comment by dmik** [comment]
Yes, most likely, you need the new cairo/pixman builds. I'm working on RPMs for them so they should be available shortly.

**Comment by dmik** [comment]
BTW, you can try my own test build using http://rpm.netlabs.org/test/38bin2.zip and replacing XUL.DLL with x5.zip and x5d.zip.
