### ISSUE TITLE
firefox-45-5-patch-yb9p2.zip lack of: print.os2.postscript.use_builtin,  in about:config 

### ISSUE THREAD

**Issue by GAnchieri** [bitwiseworks/mozilla-os2#233]
I've installed the test version  in object but I don't can  print anymore with CUPS 1.48 because this version don't have the statement in title, in about:config that I've settled to true  in official version 45.5. thus preventing the possibility to print using CUPS,  
it's this a missed statement or a  function that has been dropped?.
G.M. Anchieri

**Comment by SilvanScherrer** [comment]
please have a look at README.OS2 is also describes how to add the setting, if it's missing.

**Comment by dmik** [comment]
It's possible that this setting has never been there by default, not even as `false`. Does adding it manually as `true` fix your CUPS printing problem in this test build?

**Comment by GAnchieri** [comment]
Yes, inserting this line in about:config I can print using CUPS.
Thank you for this aid.
G.M. Anchieri

p.s. You can close this issue.
