### ISSUE TITLE
Wrong z-index of flash plugin drawing

### ISSUE THREAD

**Issue by an64** [bitwiseworks/mozilla-os2#234]
Many video players for now uses flash for play unsupported by browser video formats and places control elements on top of flash area
For example video-js player in flash fallback mode
So i make an examples for you:

http://babyenglish.club/test1
In ff38/win it show video and controls (play/pause button, volume slider..) over it , on ff38/os2 it shows only video (i removed avcode56.dll for switch to flash mode for mp4 playback) 

http://babyenglish.club/test2
In windows it shows
![ffwin](https://user-images.githubusercontent.com/6424651/28950765-e195491c-78c6-11e7-88ee-8493d478308c.png)
In os/2 
![ffos2](https://user-images.githubusercontent.com/6424651/28950775-ecea63ba-78c6-11e7-9a8f-3a23c7ce8df6.jpg)

Can't test it under ff45 for now, so sorry if it already fixed

Ps param name="wmode" value="transparent" must be set for flash object for transparency , but it doesn't help in os/2

**Comment by dmik** [comment]
I confirm the problem in FF45 as well. However I'm not sure if and when we will work on it given that Flash will inevitably and completely sink in the next year or so (given the official EOL in 2020 announced a few weeks ago).

**Comment by dmik** [comment]
@an64 Another question is if it only relates to Flash or z-order is not obeyed at all. Could you please check that? I mean replace the Flash object with something non-plugin-based and play with Z-order.

**Comment by LewisR** [comment]
FWIW, this animation works as expected (and the text-over-Flash test works, too) using Shumway on FF45.9 on ArcaOS.

Once again, an old version of Flash could be at fault. While Shumway has also been discontinued, it is far newer than the Flash for OS/2.

It's not enough to test OS/2 against Windows. To verify that it is not Flash itself, one needs to test the same version of Flash on Windows.

**Comment by dmik** [comment]
@LewisR indeed, very valid point. Our Flash is 11.x it may not support Z layering or something. A quick look didn't reveal any problems with Z order from the OS/2 widget point of view.

**Comment by an64** [comment]
Above screenshot is from ff38/flash 11.6 on win - exactly same as on os/2

> Another question is if it only relates to Flash or z-order is not obeyed at all
I think its only flash problem, at least html objects z-order seems right

**Comment by dmik** [comment]
Okay, good that you tested it. So not a FF issue. Closing.
