### ISSUE TITLE
Locale Object not always properly freed

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/mozilla-os2#236]
Stumbled over this (minor Problem).

https://github.com/bitwiseworks/mozilla-os2/blob/master/intl/locale/os2/nsOS2Locale.cpp
routine "nsOS2Locale::GetPlatformLocale":

Locale is not freed via "UniFreeLocaleObject(locObj)" in case an error happens on calling "UniQueryLocaleValue". Maybe some:
LocaleObject locObj = nullptr;
do {
...
   if (error)
      break;
} while (0);
if (locObj) UniFreeLocaleObject(locObj);

could eliminate the premature function return.

**Comment by dmik** [comment]
Yes, it's minor (almost never happens) but still thanks!
