### ISSUE TITLE
Frequent crashes on maps

### ISSUE THREAD

**Issue by NeilWaldhauer** [bitwiseworks/mozilla-os2#238]
I'm seeing crashes in web pages which contain maps. Google maps is the most frequent, but crashes have also occured for Bing and Mapquest. The map can be alone or embedded.
No .TRP is created and no entry in Popuplog.os2, either. SeaMonkey crashes the same way.
I'm using Firefox 45 beta 8. I have tried a new profile, and for one or two times the problem did not occur. Then is was back.

If I can think of a way to give a test URL, I will. For now, any URL that crashes Firefox disappears before I can copy to the clipboard.

This bug report is accompanied by a discussion on OS/2 World;
http://www.os2world.com/forum/index.php?topic=1469.msg14191#msg14191

**Comment by StevenLevine** [comment]
I would not recommend investing too much effort trying to stabilize beta8, which is now 4 months old.  It would be more effective to test with the firefox rpm available from the Arca Noae experimental repository along with the updated libcx and libc066 available from the Netlabs experimental repository.

Did you check the firefox log file for a trap file?

To remind those that might have forgotten.  Firefox is a kLIBC app.  This means you will rarely get a popuplog entry.  kLIBC replaces the default exception handler, so no populog unless the exception occurs before kLIBC installs its exception handler.  Also, firefox is a GUI app.  This means that you will never see the kLIBC exception report unless you capture standard error to a log file.  Run! can do this for you, but if you are not using Run!, you can do

  firefox 2>fireflox.log

Also, as discussed in the libcx release notes, libcx now logs errors to %UNIXROOT\var\log\libcx, so you need to check this directory for error logs.

The most likely reason for the traps you are seeing is firefox running out of memory.  If your trap file has references to malloc and friends, this is almost surely what happened.

I will note that the current firefox rpm does not seem to play well with AdBlock, so you might need to disable it if you seem to get 100% CPU usage for no obvious reason.

**Comment by NeilWaldhauer** [comment]
Thanks for the information on finding the log and .TRP file

[0181_01.TRP.log](https://github.com/bitwiseworks/mozilla-os2/files/1329696/0181_01.TRP.log)

I decided to upload the trap file for better information on this bug. I plan to install the experimental Firefox rpm, but I need to prepare a new bootable volume for that.

**Comment by SilvanScherrer** [comment]
this seems to be fixed since longer. see #212 and #215

**Comment by StevenLevine** [comment]
@SilvanScherrer, are we sure it is fixed?  I don't see anything from Darius in #212 stating the it was working for him.  Do you happen to know which binary builds the fix went into?

**Comment by SilvanScherrer** [comment]
@StevenLevine in the latest rpm it's in for sure. there have been some test dll as you can see in #212. Darius his issue was something different, as he could not get it to run at all. Some libcx conflict or such.

**Comment by guzzi-g5** [comment]
The latest rpm does not crash on google maps here. Even streetview works and that has been a while on OS/2)

**Comment by guzzi-g5** [comment]
Free shared memory did drop down to almost zero. Closing the maps tab does not get the memory back.

**Comment by StevenLevine** [comment]
You might want to take a look at the actual memory utilization with Theseus.  Closing the tab will release the memory to the Firefox heap.  However, the Firefox heap can only release the heap chuck to the kernel when it is completely free.

While I don't think much of the free shared memory monitors, I do find it odd that your free shared memory is dropping so much.  It implies that Firefox is not able to use high memory as well as it should be able to.  It might be worthwhile investigating this.

**Comment by guzzi-g5** [comment]
Shared memory just went low again and FF crashed. This is what Theseus showed just before the crash. There were 2 FF processes.
[FF.txt](https://github.com/bitwiseworks/mozilla-os2/files/1331053/FF.txt)
[FF2.txt](https://github.com/bitwiseworks/mozilla-os2/files/1331054/FF2.txt)

**Comment by StevenLevine** [comment]
I would recommend using the linear memory map report.  It does a better job of showing fragmentation.  The ff.txt and ff2.txt reports show that Firefox's shared memory utilization is not excessive, numerically.

  [d:\tmp]rexxtry say 1958 * 4096 pages / 1024**2 = 7.6484375 MB

Private memory utilization is significant:

  [d:\tmp]rexxtry say 36878 pages * 4096 / 1024**2 = 144.054688 MB

However, if this is allocated in high memory, it is not excessive.  If the linear memory map shows that the private memory is allocated in low memory, this probably needs to be looked at.

**Comment by guzzi-g5** [comment]
This the output of linear usage by process. I hope i is of use without the hyperlinks. Firefox is the 4th column from the right.
[FF-LINEAR.TXT](https://github.com/bitwiseworks/mozilla-os2/files/1335133/FF-LINEAR.TXT)

**Comment by StevenLevine** [comment]
Please grab another map listing using http://www.warpcave.com/os2diags/linear_memory_map_cmd-20151107.zip.  It use the Theseus REXX API and avoids the 

 .>>>> Theseus2's window buffer is full.

message and the early cutoff of the map.

Based on what I can see in the map, either there is a leak or the firefox code is assuming there's a lot more memory available than we will ever have on a OS/2 box.  The linear memory map generated by linear_memory_map.cmd will be a bit more informative.  The cutoff map does not tell us if upper memory is exhausted.

**Comment by guzzi-g5** [comment]
Here it is:
[FF-uncut.txt](https://github.com/bitwiseworks/mozilla-os2/files/1335983/FF-uncut.txt)

**Comment by StevenLevine** [comment]
At bit of math tells us your firefox instance is using

  10010000 - 10000 / 100000 = 256MB lower private
  50901000 - 20000000 / 100000 = 777MB upper private

or a bit more than 1GB of private memory.

Shared memory usage is nominal

  1FFE0000 - 13000000 / 100000 - 39t = 168MB lower shared
  5FFE0000 - 56CA0000 / 100000 - 97t  = 50MB upper shared

What we need to do is figure out why Firefox is using so much private memory.

While not perfect, Firefox's about:memory might provide some clues.

Theseus' Process->Memory leak detection might provide some clues as to when the jumps in memory utilization occur.

**Comment by guzzi-g5** [comment]
Hope tjis is of use
[FF-LEAK1.TXT](https://github.com/bitwiseworks/mozilla-os2/files/1340446/FF-LEAK1.TXT)
[FF-LEAK2.TXT](https://github.com/bitwiseworks/mozilla-os2/files/1340445/FF-LEAK2.TXT)
[memory-report.json.gz](https://github.com/bitwiseworks/mozilla-os2/files/1340451/memory-report.json.gz)
[memory-report2.json.gz](https://github.com/bitwiseworks/mozilla-os2/files/1340450/memory-report2.json.gz)

**Comment by StevenLevine** [comment]
It looks as though you started the Theseus leak detection after firefox had been running for a while.  The reports tells us that firefox is using

  40992 * 4096 / 1024**2 = 160.125MB

of memory, which is similar to what we saw in the linear memory map.

It's hard to say exactly what the firefox memory reports are teillig us.  I think I see a lot of unused chunks of memory used by javascript that cannot be returned to the heap to be used for other purposes.  Search the .json report for the word "unused" to see what I am referring to.

I would like to see a Theseus Leak Detection run for just FireFox.  Select FireFox in the main window,  then use Process->Memory Leak Detection.  I recommend you start the Leak Detection before FireFox has started to use memory.  While the Leak Detection is running you should watch for big jumps in memory usage and make a note of what you were doing, or what you were watching when the jump occurred.  We already know that Firefox is using memory.  This information is not going to do us much good until we learn when and how the the large chucks get used.

 Also, we should capture Process->Memory Utilization after Firefox has finished loading to get an idea of what the baseline memory utilization is.

**Comment by guzzi-g5** [comment]
[FF-LEAK3.TXT](https://github.com/bitwiseworks/mozilla-os2/files/1347471/FF-LEAK3.TXT)
[FF-START.TXT](https://github.com/bitwiseworks/mozilla-os2/files/1347470/FF-START.TXT)

The memory use shoots up when using google maps, zooming in, then dragging the map. At first memory use will jump up and return back to normal after less than a second, after dragging some more it will stay high.

**Comment by dryeo** [comment]
You might want to repeat the test in safe-mode

**Comment by guzzi-g5** [comment]
Does not make a difference. Will try a fresh profile next.

**Comment by guzzi-g5** [comment]
Same with a fresh profile

**Comment by StevenLevine** [comment]
Bjorn, FF-LEAK3.TXT looks like another system leak detection run, not the process leak detection run I recommended.

FF-START.TXT shows that the initial memory utilization is nominal - about 25MB or so of private memory.

**Comment by guzzi-g5** [comment]
My mistake, used the wrong pull down menu....
[FF-LEAK4.TXT](https://github.com/bitwiseworks/mozilla-os2/files/1351532/FF-LEAK4.TXT)

**Comment by StevenLevine** [comment]
The log tells us that the vast majority of the memory usage is for the heap.  This is probably for the best.  If PM was leaking shared memory, the issue would be that much hardware to debug.
I recommend we hold off on more analysis until 45.9 goes GA.  You are going to need Dmitriy's help in analyzing exactly which parts of Firefox are requiring so much memory.  The about:memory reports give us some clues, but as the reports note, our platform is not capable of fully reporting the memory usage details.

**Comment by NeilWaldhauer** [comment]
I did finally run Firefox 45.9 GA, and the maps situation is much improved. It doesn't crash. I haven't tried a long maps session, but at least visiting a page that embeds a map is possible. Clicking on the map and doing an operation or two is no problem.

**Comment by guzzi-g5** [comment]
The same problem still exists. It doesn't cause a crash, until memory is depleted. Dragging a zoomed in map a few times will still cause a huge use of memory.

**Comment by SilvanScherrer** [comment]
how does it behave with GA 1.1?

**Comment by guzzi-g5** [comment]
Currently using Dave's build, but that should not make any difference. Zooming and dragging worked fine, smooth, until suddenly freeSharedMem showed a drop from 184,949,592 bytes to 13,000,000  and a bit and FF crashed. Can do tests with the official build of course.

[007C_01.TRP.txt](https://github.com/bitwiseworks/mozilla-os2/files/1944384/007C_01.TRP.txt)

**Comment by NeilWaldhauer** [comment]
The maps seem to work on GA 1.1 to at least a casual user. A normal session, looking for a thing or two, even with Street View, works acceptably. Dave Yeo's build also works as far as I can tell.

**Comment by dmik** [comment]
Ok, good to hear. I guess this can be closed then.
