### ISSUE TITLE
int3 in RunWatchdog when closing FireFox

### ISSUE THREAD

**Issue by OS4User** [bitwiseworks/mozilla-os2#243]
After viewing some video from youtube and closing FireFox,  system stops in int3 
/toolkit/components/terminator/nsTerminator.cpp line 158 (MOZ_CRASH("Shutdown too long, probably frozen, causing a crash."); )

**Comment by dmik** [comment]
This appears to be a duplicate of #269. Well, the other way around, but still. Closing this one as #269 contains more information. @OS4User thanks for reporting!
