### ISSUE TITLE
Decide on mmap usage in JS

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#250]
Historically, Mozilla code uses raw `DosAlloc[Shared]Mem` where big chunks of memory are needed. This includes various JS memory allocators. While it might look feasible to use the fresh `mmap` implementation that is provided by LIBCx just like on Unix platforms to simplify code, there are a couple of thoughts against it:

1. In most of the use cases, only memory itself is needed, it's not backed up by any file, i.e. MMAP_ANONYMOUS is used (it's just that this is how big chunks of memory are allocated on Unix historically). On OS/2 we have a kernel API to do so, just like on Windows, so using it directly allows to avoid mmap overhead.

2. The `mmap` implementation provided by LIBCx is far from being perfect, it has some edge cases (mostly because it's impossible to fully implement the requested behavior without the support from the kernel, which we lack, this includes support for C-O-W memory pages in the first place).

In most places in Mozilla `DosAllocMem` is already used where `mmap(MAP_ANON)` is used. However, there are some places where `mmap` is now used even on OS/2. This should be changed to `DosAllocMem`. This is JS code in `js/src/vm/ArrayBufferObject.cpp` and  `js/src/vm/SharedArrayObject.cpp`.

There is also one place where `mmap` is used to map a file. This can't be changed to `DosAllocMem` and we have to use LIBCx `mmap` for that because this is what it was initially done for. This code is JS Shell (`js/src/shell/js.cpp`). As far as I understand, this code isn't used in Firefox itself, but the shell itself is heavily used in various JS test frameworks and we need that. (See #247). Currently, there are some problems with LIBCx `msync` which cause JS to crash, see https://github.com/bitwiseworks/mozilla-os2/issues/247#issuecomment-346048314.

**Comment by StevenLevine** [comment]
@dmik, I agree that if there is no reason to use mmap, it should be avoided.  BTW, do you really mean use DosAllocMem directly or via a wrapper or via malloc?  Does any of this code need to allocate from lower memory?

One possible downside to using DosAllocatMem is that it tends to fragment memory for allocations that are not a multiple of 64KB.

**Comment by komh** [comment]
@dmik mmap(MAP_SHARED) is used ? If not, DosAllocMem() is the correct choice. Even if MAP_SHARED is used, if it is used with MAP_ANON, DosAllocSharedMem() can replace it. There is no need to introduce another bug by using not perfect codes.

And for copy-on-write, it's possible to emulate most things of it without kernel.

**Comment by dmik** [comment]
@StevenLevine no, it's about using DosAllocMem directly — it's used in JS to allocate large chunks of memory for the JS heap so fragmentation is not an issue. And all allocations are performed from high memory of course, when it's available.

@komh both MAP_SHARED and MAP_PRIVATE. And yes, I'd been replacing these with `DosAlloc[Shared]Mem` in the past. These `src/vm` bits is just some new code. I had a thought once that we should use `mmap` instead of `Dos` to hide various implementation details but that adds unnecessary overhead so I now tend to use `Dos` directly unless there is a non-anonymous mmap.

Regarding COW. Sure, it can be emulated to some degree — and that's precisely what LIBCx `mmap` does. But there are some edge cases and some principal limitations. The biggest problem is that it's impossible to have a memory page that is first mapped to a shared page and then gets remapped to a private page (which is a copy of the shared one) *retainig* its virtual address. And this makes some `mmap` use cases either very inefficient or simply impossible on OS/2.

**Comment by komh** [comment]
@dmik Do you mean remapping a shared memory to a private memory ? If I understand correctly, I did it already when implementing mmap(). DosAliasMem() will be your friend. Unfortunately, however, that friend has a shortage that it allocates an aliased object only in address spaces of low memory.

**Comment by komh** [comment]
@dmik Ooops... Sorry about off-topic, again.

**Comment by dmik** [comment]
@komh np. Re `DosAliasMem`, it couldn't become my friend, unfortunately. While you can indeed map a shared page into the private address space this way, it's not a real COW page — all processes will share the same content and any change to it will be visible in any process. Not what we need for `mmap`. And more over, there is some weird behavior with protection flags of aliased pages. See e.g. here https://github.com/bitwiseworks/libcx/issues/13#issuecomment-258186694 and below. Also this https://github.com/bitwiseworks/libcx/issues/12#issuecomment-253897674 and around. All in all, `DosAliasMem` is quite useless in `mmap` case from my experience.

**Comment by komh** [comment]
@dmik COW is not needed for MAP_SHARED. Because in case of MAP_SHARED, all processes should see the changes as well as the same content at the same time. DosAliasMem() does it with different addresses.

Instead, COW is needed for MAP_PRIVATE. However, MAP_PRIVATE can be implemented without COW. Just copying at the first is enough. Of course, efficiency will decrease. 

And for the protection flags of aliased pages, it works here for a child process even if it's related to shared pages.

**Comment by dmik** [comment]
Nobody said that COW is needed for MAP_SHARED, it's needed for MAP_PRIVATE. LIBCx `mmap` implements MAP_PRIVATE w/o COW either but this has its flaws and limitations. One of them is inefficiency but I recall there is something more than that. In general, we can't support all cases the real `mmap` impl supports. BTW, I know you have your own `mmap` implementation. But It won't survive many test cases that the LIBCx one survives, to my understanding it's only useful for very simple use cases (just like the old mmap impl based on WIn32 memory mapped file emulation from WPTK which LIBCx was designed to extend — mostly to support Samba which has *very strict* mmap requirements).

BTW, here is another show stopper that even LIBCx `mmap` can't overcome as of yet: https://github.com/bitwiseworks/libcx/issues/25. And there is also https://github.com/bitwiseworks/libcx/issues/32. It's not about COW, but COW is not the only thing we miss to make `mmap` support efficient and complete, this is my statement #2 in the ticket description.

**Comment by komh** [comment]
Ooops... Sudden comparison of mmap() implementation. It has no meanings at all. I don't care about what survive more test cases, because it's enough to improve the functionality if there are cases it fails. But if you want to argue that, provides the real test results not your wish. Or this is just FUD. This does not help to each other at all.

In case of COW, I meant COW was not a critical feature for mmap() implementation. Anyway you said that you also didn't use COW. Then it's ok.

**Comment by dmik** [comment]
Hey, please let's not get offended (it's never my intention). You were apparently referring to your own implementation of mmap when you told about COW and DosAliasMem. I spoke because I looked at it back then and even evaluated some tests against it — and above is just my conclusion (which may be outdated or even wrong tough). I would love if your impl could solve some of mmap problems in Samba but it wasn't so at that time (your impl didn't differ much from the old mmap impl in my view). You may run LIBCx mmap tests against it yourself if you want proofs. Whether COW is critical or not is an open question. I tend to the former as it shows poor results in real life (which means that if a multiprocess app uses MAP_PRIVATE w/o MAP_ANON on a large number of big files, we're in trouble and it's better to redo it w/o mmap than use its poor implementation w/o COW — something similar applies to LIBC `fork` btw and it's one of the reasons I got rid of `fork` in Python).

Anyway, while it's off topic here, I understand that there is nowhere else we could communicate. I value communication a lot — this is what helps everyone and allows to make software better. I'd love to see you on our Slack (you can join via IRC), I've sent you an invitation (to your GitHub email). And I'm sorry if you felt offended.

**Comment by dmik** [comment]
My current thought about LIBCx `mmap` is that it came to its maximum given the limitations of OS/2 (the lack of finer page mapping control which includes COW). It will work in many cases (git is a good example — old mmap didn't work there and I expect your mmap won't either — correct me if I'm wrong) but not in such extreme cases like Samba. And given that Firefox has enough of its own complexity, I just don't want to bring another one in unless it's absolutely necessary (so far it is not).

**Comment by komh** [comment]
My referring to my implementation cannot be the reason why you said the your own comparision to show your implementaion is superior. Here, just exchanging ideas of each other is enough.  If it's acceptable, it's ok to accept, else to reject. That's it. It's not a problem from where they are. You said not helpful words to problem solving.

Anyway, it's ok. Go ahead your hard work. Do not waste your precious time.

**Comment by dmik** [comment]
I said what I said because I *learned* your implementation's details seeking for a solution of problems in my implementation (I pointed them out above). I'm eager to be wrong with my conclusion that there is no way to solve these problems (and this is all I'm talking about) so if you think you know a solution please speak up. I don't care about whose impl is superior, I only care if a problem can be solved or not.

Back to the topic, I did some investigation and found out that the `ArrayBuffer` implementationonly uses the C heap (its `calloc` to be precise) for all memory allocations. More over, I ran a trace build of LIBCx and haven't found any `mmap` usage (despite `mmap` calls in the sources from the ticket above). Some of `mmap` usage seems to be disabled by preprocessor and the other methods seem to just never get called on OS/2 for some reason. There's something more to test/try. But the fact that we're allocating from the regular C heap may explain premature OOM conditions: this heap might get quite fragmented over time...

**Comment by dmik** [comment]
I just observed that some `mmap`s are behind ASMJS_MAY_USE_SIGNAL_HANDLERS_FOR_OOB. This define is used to enable OOB (out of bounds) checks using signal handlers (like the guard pages). This code used to exist on OS/2, this is what this `AsmJSOS2ExceptionHandler` is all about. However, the mozilla devs then decided that this is only efficient on 64-bit platforms so this code is currently completely disabled on OS/2 (on 32-bit platforms they perform out of bounds checks in a different way, see https://bugzilla.mozilla.org/show_bug.cgi?id=986981, https://bugzilla.mozilla.org/show_bug.cgi?id=1135903). I don't have full understanding which is best on OS/2 ATM but let's trust the JS devs for now and go the common 32-bit route they offer (makes sense also given that Win32 goes that route either; though I don't know how well the 32-bit Windows builds are supported now). Anyway, this means that the relative OS/2 parts are dead code for now (this includes e.g. https://github.com/bitwiseworks/mozilla-os2/commit/1b4fff0041ffbf714855e9e3eeee2d37414dfbef).

**Comment by dmik** [comment]
JFTR, I did some tracing and I see that both the JS Shell and FF use `jit/ProcessExecutableMemory.cpp:ReserveProcedssExecutableMemory` (128 MB) once, this is (most likely for JIT code), then one `gc/Memory.cpp:MapAlignedPagesRecursively` call for 16 MB, and then a relatively small number of `MapAlignedPagesRecursively` calls for 1 MB blocks. Both of these calls use `DosAllocMem` directly. The rest goes through `calloc`, it seems. No other memory allocation APIs seem to be used on the JS side.

**Comment by dmik** [comment]
Ok, OOM in `testResize.js` (see https://github.com/bitwiseworks/mozilla-os2/issues/247#issuecomment-347295425) together with the fact that `calloc` is used brought some doubt about whether it's high-mem enabled or not and guess what: I found out that it returned *low memory*! That would be a perfect explanation why it'd bail out allocating 80 MB after already having allocated 192. Together with 128 MB allocated via `DosAllocMem` this is very close to the 512 MB limit of low memory.

Using logging LIBC quickly revealed the DLLs that voted against high memory: it's ICU DLLs. In particular, ICUUC.DLL and ICUIN.DLL. Seems that `-Zhigh-mem` slipped away from these libraries too (we already had a few cases like that in the past). BTW, it doesn't look clear now why Knut decided to use this voting mechanism at all: it makes more harm than good. Of course, ICU didn't vote for low memory deliberately, it's just the GCC default unless `-Zhigh-mem` is given. And all other falling cases are just like that. I'm really considering now that we should make `-Zhigh-mem` a new default for LIBC/GCC. Actually, I don't remember a single case where I'd have to avoid using `-Zhigh-mem`.

Anyway, even after I fix ICU DLLs by adding `-Zhigh-mem`, the problem still remains. A user may have a different version of some DLL which will vote for low memory and it'll make the whole JS in FF (as well as parts of FF itself) use low memory, despite what the application wants. Not good. For JS I can theoretically fix it by forcing `_hcalloc` via JS_USE_CUSTOM_ALLOCATOR instead of `calloc`. But still, the rest of FF might fall to using low-mem versions... I'm in doubt. May be, we should override `calloc` in LIBCx so that we could force global high-mem usage regardless of other DLL votes. We could even control it via an environment variable to allow for local overrides in case of any problems (as well as for tests).

**Comment by dryeo** [comment]
What about just putting GCCOPT=-Zhigh-mem in the environment?

**Comment by dmik** [comment]
@dryeo GCCOPT is about the build stage and in our RPM environment this is covered by `LDFLAGS=-Zhigh-mem` before calling `configure` (virtually all .spec files do it). And I'm talking about the runtime above. We can't control how people build their DLLs (and we may get mistaken ourselves), so we need a way to force high memory at runtime.

**Comment by StevenLevine** [comment]
>@dryeo GCCOPT is about the build stage and in our RPM environment this is
>covered by LDFLAGS=-Zhigh-mem before calling `configure`. And I'm talking
>about the runtime above. We can't control how people build their DLLs
>(and we may get mistaken ourselves), so we need a way to force it at
>runtime.

@dmik, I'm not sure what the best choice is.  You could force the voting
or you could force a shutdown if some DLL is built with -Zlow-mem.  I'm on
the fence which is the better solution.  Shutting down will require the
user to update the system and get rid of the non-conforming DLLs.  Forcing
-Zhigh-mem allows the app to run, but might allow the non-conforming DLLs
to cause hard to diagnose failures.

As I understand the code, voting is done each time a DLL is loaded.  The
current state can be queried with __libc_HeapGetResult().  It's like that
voting can be overridden by replacing __libc_HeapVote().

FWIW, my guess is that Knut made -Zlow-mem for safefy.  It took a while to
get all the DLLs rebuilt with os2safe.h.  Also, it was not that long ago
that os2safe.h needed an update to handle an API that was believed to be
high-mem safe.

**Comment by dspiatkowski** [comment]
Hi Everyone!

On Wed, 29 Nov 2017 00:32:28 +0000 (UTC) StevenLevine wrote:
>
>> @dryeo GCCOPT is about the build stage and in our RPM environment this  
>> is
>> covered by LDFLAGS=-Zhigh-mem before calling `configure`. And I'm  
>> talking
>> about the runtime above. We can't control how people build their DLLs
>> (and we may get mistaken ourselves), so we need a way to force it at
>> runtime.
>
> @dmik, I'm not sure what the best choice is.  You could force the voting
> or you could force a shutdown if some DLL is built with -Zlow-mem.  I'm  
> on
> the fence which is the better solution.  Shutting down will require the
> user to update the system and get rid of the non-conforming DLLs.   
> Forcing
> -Zhigh-mem allows the app to run, but might allow the non-conforming DLLs
> to cause hard to diagnose failures.

Here is a some input from a very straight end-user perspective: if we  
assume and/or agree that high-mem loading is the preferred way (given the  
various benefits it provides one could also assume that the vast majority  
of users would likewise enjoy the benefits this provides) we should drive  
towards as much use of high-mem loading as possible. Therefore, the options  
we should pursue are the ones that will get us closer to that "target  
condition", in this case, force the shutdown & upgrade of the DLL to the  
high-mem version.

Now where this has the potential to fail in a massive way is when the  
support pieces (such as the various DLLs eligible for high-mem upgrade) are  
not out there and readily available (I'm thinking timely RPM/YUM packages  
and updates listed in the known repos).

But...those and many other challenges will always be there. I, as and  
end-user, need to accept some ownership over making sure my system is  
configured in the optimal way to make the best use of the software which is  
still being developed. I hate to say it, but there should be no "ifs, ands,  
buts, elses..." in this. The DEV team has a very unique opportunity in this  
case to create an optimal solution. This should be well announced and  
explained to the audience and I'm sure when the supporting arguments are  
clearly understandable the majority of the users will likewise embrace the  
approach.

So force the high-mem as the preferred default option, but provide the  
choice to run low-mem should the default cause problems on any particular  
end-user machine.

Thanks,
  - Dariusz

**Comment by komh** [comment]
@dmik I already reported the problem a few years ago. See http://trac.netlabs.org/libc/ticket/336. And I agree with you to override callc(). In addition, I would like to say to use both memory pool. That is, if fails in high-mem, then try in low-mem.

**Comment by dmik** [comment]
@StevenLevine checking for whether some DLL is built without -Zhigh-mem is an interesting option but it's not a trivial task as there is no way to get control over voting — it's hard-coded within LIBC. I may replace `__libc_HeapVote` in LIBCx with my own call of course, but it won't be used by DLLs not built against LIBCx (or built earlier, prior to this export) as they are statically linked to the LIBC version of the function. In other words, it's not possible to change voting which is happening in the DLLs this way by linking just the final EXE against LIBCx — you will have to rebuild all DLLs it loads and that's equivalent to just specifying `-Zhigh-mem` in their LDFLAGS (which is much simpler so replacing `__libc_HeapVote` makes no sense).

Note that heap voting starts soon after the EXE entry point gets control and ends just before `main()` on thread 1 is called. Any further attempt to vote (no matter from a DLL or from the EXE itself) will be silently ignored. The only legal way to change the default heap after entering `main()` is to call `_udefault()` with either `_hinitheap()` or `_linitheap()`. But this only changes the default for the current thread — newly created threads will start off using the vote result (stored in the `_um_regular_heap` global variable). Yes, we may assign _hinitheap() to `_um_regular_heap` but it doesn't look like a legal way. It's better then to override the default from LIBCx where I already inject code before `main()` (so I have full control over the final vote result) — both ways are not "legal", but the latter one doesn't require any application code, just linking against `-lcx` is enough (just like with EXCEPTQ support).

I understand that Knut made the low mem a default choice for safety. I just want to say that it has no practical sense any more in the current reality and it makes more evil than good. I have no real life examples where a DLL would freak out because the app forces high memory. And even if there are such DLLs, the whole voting system won't help much here because the app may still allocate high memory via `_hmalloc` or via `DosAllocMem` directly (many apps do that including Firefox!) and supply this buffer to such a DLL. This means that workarounds should be done on a DLL by DLL basis here, not via global voting at application startup. I.e. either the bad DLL should be fixed (rebuilt with Safe Dos wrappers) or the app should take a precaution and supply only low mem buffers to such a DLL if it's impossible to rebuild it.

**Comment by dmik** [comment]
Also, it looks like a completely wrong approach when a single DLL decides for the whole application which memory it should use. So in my opinion Knut's decision was conceptually wrong from the beginning (although I understand why it was done).

@komh yes, I recalled that now. You are completely right (and see also above). Regarding falling back to low memory — this is actually already done in LIBC: `_hinitheap()` will return the same value as `_linitheap()` if high memory is not available.

@dspiatkowski your point is clear but it's not practically possible to detect which DLLs are not ready for high mem and abort the application. And it's not the application's task in the first place. It's a system task. I.e. one might provide a utility that will try to scan all the DLLs and see which ones are not high-mem ready, but the application should not do that.

Actually, given that LIBCx injects the code before `main()` I can detect from that code whether any DLL voted against high mem and abort the application in such a case. But I won't be able to tell which DLL exactly voted against it (as I said above, it's not trivial to detect). And getting "hey I can't run because something is wrong somewhere" is non-informative and frustrating for the end user, especially when the app can run just fine (as in case of ICU DLLs and many other potential cases where high men wasn't enabled not because it's not compatible but just because the DLL developer didn't care about which memory to use).

So I still tend to force high memory from LIBCx with support for `LIBCX_HIGHMEM=0` that will suppress such forcing. My only concern is what if the app/DLL wants low mem and LIBCx at the same time. Perhaps, I will introduce a callback so that the app could override this w/o the requirement of `LIBCX_HIGHMEM=0` in the environment.

**Comment by dmik** [comment]
BTW, https://github.com/bitwiseworks/libcx/issues/48#issuecomment-347984076. This means that OOM crashes that some Firefox users reported are not related to ICU libs and low memory heap: the Firefox process would always use high memory even if some DLL voted against it. Which doesn't cancel other cases like the JS.EXE one (JS.EXE, as opposed to FIREFOX.EXE, is linked to ICU DLLs statically).

**Comment by StevenLevine** [comment]
@dmik, my thinking was that any mods to the voting system would be done via a tweaks to libc06x.  I could not envision a way that libcx0 could supply the needed logic to apps not linked with libcx0.  If the mods  were in libc06x, it should be possible to report the offending module.

That said, I don't see any significant issues with your plan to force high mem when linked with libcx0.  At worst, we will need to get better at recognizing when a failure implies that an app needs to be modified to us os2safe.h and _talloc().

**Comment by dmik** [comment]
BTW2, I just got another idea while thinking on all that: FF uses the high memory C heap but does not use the low memory C heap (which is also there anyway, and there may be around 200-300 MB of additional free space). Note that in cases where FF allocates memory directly with `DosAllocMem` this is already the case: if the OBJ_ANY (high mem) allocation fails, it will retry to allocate from low mem immediately. I guess this should work just great.

**Comment by dmik** [comment]
@StevenLevine yes, see https://github.com/bitwiseworks/libcx/issues/48 please (this is the respective LIBCx ticket). Also your opinion about both heads (see above) is appreciated.

**Comment by StevenLevine** [comment]
@dmik.  re: https://github.com/bitwiseworks/mozilla-os2/issues/250#issuecomment-347987741. The way I understand the klibc heap code is that when -Zhigh-mem is active, klibc will use OBJ_ANY when adding blocks to the high memory heap.  This means that the high memory head can contain blocks from low memory.

**Comment by dmik** [comment]
@StevenLevine Are you sure that with OBJ_ANY `DosAllocMem` will return low memory if there is no space in the high memory arena any more? Well, yes it makes sense judging from the `ANY` part of the flag name but I don't have any proof of such a behavior. Of course, if it's like you say, then no need to join two heaps manually.

**Comment by komh** [comment]
I did simple test if falling back to low memory is needed when fails in high memroy.

1. If _hmalloc() which allocates both in high memory and in low memory fails, _lmalloc can allocate some more memory in low memory
2. If DosAllocMem() with OBJ_ANY fails, DosAllocMem() without OBJ_ANY also fails
3. If unamed DosAllocSharedMem() with OBJ_ANY fails, unnamed DosAllocSharedMem() without OBJ_ANY also fails
4. If named DosAllocSharedMem() with OBJ_ANY fails, named DosAllocSharedMem() without OBJ_ANY also fails

As a result, in order to use both memory pool, in case of kLIBC, it's needed to call _lmalloc() family when _hmalloc() family fails. However, in case of OS/2 APIs, just OBJ_ANY is enough. However, for the compatibility with OS/2 version not supporting OBJ_ANY flag, it's needed to fall back to the call without OBJ_ANY when it fails.

After all, I think, falling back to low-memory allocation is a good programming way.

**Comment by StevenLevine** [comment]
@komh, what allocation sized were you using for testcase #1?  It's possible that when the high memory heap can no longer be enlarged, there's still space available in the already existing low memory heap.

Also, the klibc heap uses two different allocation strategies.  One for crumbs and one for larger blocks.  This means there might be a large number of free crumbs in the heap, but there will not be space to allocate a block that is too big to be a crumb.

**Comment by komh** [comment]
I tried 1 KiB to 512 MiB. It's possible to allocate in low-memory up to 16 MiB to 64 MiB depending on a block size when running out of high-memory.

And I've found a funny thing. If falling back to _hmalloc() when _lmalloc() fails, the more total memory could be allocated than falling back to _lmalloc() when _hmalloc() fails.

Here is my test code.

```
/* highmem5.c */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <emx/umalloc.h>

static int m_h = 0;
static int m_l = 0;

static void *alloc( size_t size )
{
    void *p;

    p = _hmalloc( size );
    if( !p )
    {
        printf("Try to alloc in low-memory\n");
        p = _lmalloc( size );
        if( p )
            m_l += size;
    }
    else
        m_h += size;

    return p;
}

int main( void )
{
    void *p;

    while(( p = alloc( 1024 * 1024 )) != NULL )
        printf("p = %p, 512 MB = %p, high = %d\n",
               p, 512L * 1024 * 1024, ( uintptr_t )p > 512L * 1024 * 1024 );

    printf("high = %d, low = %d, total = %d\n",
           m_h / 1024 / 1024, m_l / 1024 / 1024, ( m_h + m_l ) / 1024 / 1024 );

    return 0;
}
```

**Comment by dmik** [comment]
@komh cool, interesting findings! I guess that the reason why you have a different amount of total memory when exhausting low memory first is because the kernel somehow tries to balance between private and shared as both in low and high memory arenas and the strategy it uses for balancing is somehow different. This whole idea of having two arenas for private/shared growing towards each other is not the best option, obviously. But this is what we don't have any control over.

**Comment by dmik** [comment]
Did local tests with the slightly modified @komh's example that also shows how much low mem was allocated through `_hmalloc`:
```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <emx/umalloc.h>

static size_t high_mem = 0;
static size_t low_mem = 0;
static size_t high_mem_real = 0;
static size_t low_mem_real = 0;

#if HIGHMEM_FIRST
#define ALLOC1 _hmalloc
#define ALLOC2 _lmalloc
#define MEM1 high_mem
#define MEM2 low_mem
#else
#define ALLOC1 _lmalloc
#define ALLOC2 _hmalloc
#define MEM1 low_mem
#define MEM2 high_mem
#endif

#define STR_(x) #x
#define STR(x) STR_(x)
#define TO_MB(n) (((n) + (1024 * 1024 - 1)) / 1024 / 1024)

static void * alloc (size_t size)
{
  void *p;

  p = ALLOC1 (size);
  if (p)
    MEM1 += size;
  else
  {
    p = ALLOC2 (size);
    if (p)
      MEM2 += size;
  }

  if (p)
  {
    if ((uintptr_t) p >= 512 * 1024 * 1024)
      high_mem_real += size;
    else
      low_mem_real += size;
  }

  return p;
}

int main( void )
{
  void *p;

  printf ("Allocating using " STR(ALLOC1) " first...\n");

  while ((p = alloc (1024 * 1024)) != NULL)
    ;

  printf ("alloc via _hmalloc = %04lu MB, via _lmalloc = %04lu MB, total = %04lu MB\n",
          TO_MB (high_mem), TO_MB (low_mem), TO_MB (high_mem + low_mem));
  printf ("alloc high mem     = %04lu MB, low mem      = %04lu MB, total = %04lu MB\n",
          TO_MB (high_mem_real), TO_MB (low_mem_real), TO_MB (high_mem_real + low_mem_real));
  printf ("low via _hmalloc   = %04lu MB\n", TO_MB (high_mem - high_mem_real));

  return 0;
}
```
Here are my results for -DHIGHMEM_FIRST=1 (note that I have VAL=3072):
```
Allocating using _hmalloc first...
alloc via _hmalloc = 2326 MB, via _lmalloc = 0031 MB, total = 2357 MB
alloc high mem     = 2086 MB, low mem      = 0271 MB, total = 2357 MB
low via _hmalloc   = 0240 MB
```
And here are the results for -DHIGHMEM_FIRST=0:
```
Allocating using _lmalloc first...
alloc via _hmalloc = 2086 MB, via _lmalloc = 0296 MB, total = 2382 MB
alloc high mem     = 2086 MB, low mem      = 0296 MB, total = 2382 MB
low via _hmalloc   = 0000 MB
```
Indeed, the "_lmalloc first" route brings extra 25 MB of memory. Funny. And this test (thanks @komh) also proves that `_hmalloc` eventually allocates from low mem w/o any additional effort (so @StevenLevine was right). But given that the biggest difference between using only `_hmalloc` and using either combination of `_hmalloc` + `_lmalloc` is only 56 MB (2382 - 2326) here, I don't think it's worth changing the JS memory allocation code (other than forcing `_hmalloc` to be used by default which is already done by LIBCx). I expect the difference to be less if the user has a lower value of VAL.

**Comment by dmik** [comment]
This one may be closed as LIBCx forces `_hmalloc` by default since 0.6.1 (already released) and it's been decided to live with direct `DosAllocMem` calls for now (mmap implementation on OS/2 has its own pitfalls and it's not always possible to use the Linux code as is which beats the whole purpose of changing the direct OS-specific API to mmap).
