### ISSUE TITLE
45.9.0: chained list of device drivers broken - strange issue with memory corruption ?

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/mozilla-os2#276]
I have this config:
8-core system, Firefox 45.9.0, code for XUL.DLL, MOZSQLT3.DLL, LGPLLIBS.DLL is loaded into high memory but I also tried with the DLL code loaded into normal memory.

For the following, you need to have Theseus installed which can be found here:
ftp://ftp.boulder.ibm.com/ps/products/os2/fixes/v4.5warp/theseus4/

This is what I did:
1) open "Theseus" and have a look at System->General System->Device Drivers and browse to the end of the window. All device drivers are listed ok.
2) then open Firefox and use it for an extended period of time. In particular playing video clips (high memory use) seems to trigger the following problem. I think if you additionally open Thunderbird this error will show up even more quickly.
3) open "Theseus" and again have a look at System->General System->Device Drivers and browse to the end of the window. You will now see that this list is incomplete/broken with the following message:
t2system:DeviceDriversContens - error 65552

In practice that means that the chained list of device drivers is broken which of course is a very bad thing to happen. I suspect that this is a memory issue.
Could you at least confirm that this also happens on your systems ?

**Comment by lerdmann** [comment]
Never mind, I have found the bug. It has nothing to do with Firefox. It's either a broken USBEHCD.SYS or a broken USBAUDIO.SYS. It therefore happens when Firefox plays any sound (because I am using a USB sound device). You can close this bug.

**Comment by SilvanScherrer** [comment]
Ok closing on request.
