### ISSUE TITLE
Warning: Unresponsive Script

### ISSUE THREAD

**Issue by abwillis** [bitwiseworks/mozilla-os2#28]
I see this on many many pages but http://www.yahoo.com is certainly one it occurs on.  The page begins loading and right at first I may be able to start scrolling but only a fraction of an inch before Firefox goes non-responsive and then the WPS does as well.  Ctrl ESC, Alt ESC will normally break the WPS free but Firefox is non-responsive until it pops up a box saying: Warning: Unresponsive Script the script at such and such a URL (varies of course) is not responding do you want to continue or stop.  Selecting stop sometimes then frees the browser up but often it just right back to unresponsive state and later the popup again.
Deleted the profile directory and let it rebuild and it seems more likely to stop when I click stop but it still initially goes unresponsive.  Disabled flash plugin and with the clean profile no longer have flashblock (which I had disabled previously thinking it may be involved by that didn't seem to make a difference).

**Comment by dmik** [comment]
yahoo.com works quite well in both ESR24 and ESR31 with `dom.ipc.plugins.enabled` set to `false` here.  This proves that the reason of unresponsiveness is problems with IPC in `plugin-container.exe`. And the latter is dealt with in #106. So I'm closing this one.
