### ISSUE TITLE
Sumpin' ain't right here

### ISSUE THREAD

**Issue by mepe** [bitwiseworks/mozilla-os2#281]
I'm not able to install Firefox 45.9.0 from ANPM or YUM.

A search for firefox* on ANPM shows no package found.

Similarly, "yum install firefox* gets me only firefox-himem, which may or may not be a good idea, but not what I'm wanting right now.

Is there something I need to know so obvious that it wasn't included in the ReadMe or the instructions on the website?

Thanks.

**Comment by SilvanScherrer** [comment]
Its not available as rpm beside as arcanoae customer. So you need to ask arcanoae. Sorry about that.
