### ISSUE TITLE
Release GA

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#5]
Ticket to collect small issues related to the release. To be closed together with the milestone after the release is made.

**Comment by dmik** [comment]
Big news is coming. We decided to release our current version of Firefox 45.9.0 as GA as all serious problems have been fixed and the application is rather stable nowadays. The release will happen in a few days (and then we'll immediately update codebase to 52esr and release it a our next version once it's tested).

**Comment by dspiatkowski** [comment]
Hi Dimitriy and Team,

That is awesome news, I realize there have been large amounts of work put into getting us 
here...all of that has been greatly appreciated!

Looking forward to that next build release...

-Dariusz


On Mon, 02 Oct 2017 15:31:57 +0000 (UTC), Dmitriy Kuminov wrote:

>Big news is coming. We decided to release our current version of Firefox 45.9.0 as GA as all 
serious problems have been fixed and the application is rather stable nowadays. The release 
will happen in a few days (and then we'll immediately update codebase to 52esr and release it 
a our next version once it's tested).

**Comment by dmik** [comment]
Released.
