### ISSUE TITLE
Update TimeStamp implementation in XPCOM

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#56]
Currently, OS/2 uses quite a dummy implementation based on `PR_IntervalNow()` which in turn uses the MS counter via `DosQuerySysInfo` by default. We need to make use of the high-res timer available through `DosTmrQueryFreq` (`PR_IntervalNow()` also uses it which may be used as an example).

We also need to provide an implementation for the new `TimeStamp::ComputeProcessUptime()` call which calculates time used by the process since its startup. Perhaps, this . with `DosPerSysCall` or `DosQProcStat`. Some details are here: http://www.edm2.com/0607/cpu.html.

**Comment by SilvanScherrer** [comment]
is ComputeProcessUptime() still used in ffox? Or done different now?

**Comment by dmik** [comment]
I see no reason for this to remain open. One note though: the `TimeStamp` class has moved from XPCOM to MOZGLUE somewhere at or after ESR 38. MOZGLUE is (I guess) designed to have no NSPR or similar external dependencies or such. And while we don't need NSPR when using the hires timer, we still link to it as we use `PR_IntervalNow` as a fallback when the hires timer is disabled or fails to operate (we also use an NSPR mutex in the fallback scenario to handle the rollover case when the uptime is more than 49 days). We can get rid of this NSPR dependency by using LIBC `ftime` (just like `PRMJ_Now` in JS does) but I don't see any need in this so far. This would be needed for embedding XPCOM in different apps which is not used OS/2 at all.
