### ISSUE TITLE
MP3 HTML5 playback does not work.

### ISSUE THREAD

**Issue by dbanet** [bitwiseworks/mozilla-os2#67]
Hi.

According to [this page](https://wiki.mozilla.org/QA/H264-AAC-MP3_support), support of HTML5 MPEG layer 3 audio playback has been implemented in Firefox 22.

But the [HTML5 test page](http://html5test.com) I've visited with FF24 on OS/2 reports that MP3 audio playback is not supported by the browser:

> MP3 support No ✘

I know also, that MP3 audio playback on all other major platforms uses **system** MP3 codec to decode the media format, so I've installed the [MP3 MMIOProc](http://hobbes.nmsu.edu/h-search.php?key=mmecs_mp3&pushbutton=Search) on my eCS 2.2 system, but that didn't change anything (although the ioproc does work and I can playback MPEG layer 3 audio files with WPS with no problem).

It seems that the thing that should interoperate with the system's codecs is just not yet ready in the OS/2 port. I hope this will be fixed.

Best regards,
Boris.

**Comment by dmik** [comment]
BTW, here https://bugzilla.mozilla.org/show_bug.cgi?id=1207429#c24 they claim that starting from Firefox 44 it will be possible to play MP3 via the ffmpeg decoder w/o the need for gstreamer. This will most likely work on OS/2 as well and hence close this issue. I'm removing it from Beta 7 then.

**Comment by SilvanScherrer** [comment]
please try with latest firefox45

**Comment by dmik** [comment]
Silvan, no need to try it as Dave already tried and playing a local file worked for him (see https://github.com/bitwiseworks/mozilla-os2/issues/216#issuecomment-305675425). And it works exactly as planned for FF 44 (see my comment above). So this one may be closed.
