### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by an64** [bitwiseworks/mozilla-os2#70]
In FF24 i have no sound at all
Nor in youtube html5 player, nor in this demos for example
http://audiocogs.org/codecs/mp3/
http://www.createjs.com/#!/SoundJS/demos/testSuite
https://developer.mozilla.org/en-US/demos/detail/voron/launch

All plays well in FF17

Maybe this related with https://bugzilla.mozilla.org/show_bug.cgi?id=886886

I use very old uniaud driver from vladest becouse it work stable with my sb live card , all other programs works with it without any problems

**Comment by dbanet** [comment]
Should be closed now I suppose?

**Comment by dmik** [comment]
I can confirm that with applying libkai patches (see #12) the sound is back. I could hear sound in all the links from the description, including youtube in HTML5 mode. Closing this one. Any further discussion is in #12.
