### ISSUE TITLE
FF crashes sometimes when clicking on a download link

### ISSUE THREAD

**Issue by an64** [bitwiseworks/mozilla-os2#71]
When i click to download links it on a page it crashes , but usually not at first click
For example if you start to downloading files one by one  from here http://home.earthlink.net/~steve53/betas/  it usually crash at doscall1.dll-sym-14.062.w4fp15.zip , but not always exatly at this file

No exceptq report or popuplog entry generated

**Comment by an64** [comment]
I discovered, whats going wrong - its my strange native  plugin npdjvu, i leave it in plugins directory after testing #47
It seems FF initializes it in any case, when checks if the plugins can support  mime type of download link, even if i set it to disable in addons\plugins page

So i think this crashes  related to the  ticket #47

**Comment by SilvanScherrer** [comment]
as this crash goes away with disabling the plugin, I close this one here in favour of #47
