### ISSUE TITLE
100% CPU with javascript

### ISSUE THREAD

**Issue by ydario** [bitwiseworks/mozilla-os2#73]
On my dual core laptop some sites are raising one core to 100% cpu usage; it happens on sites using heavy scripting (facebook) or using extensions. E.g. passwordbox.com extension is getting a long delay on login due to this issue, while login is almost instant using windows or linux builds.
FF17 is not showing this issue. But in the recent 17.0.11 it appears again, I don't know if due to backported code or what: the delay is not as long as in ff24.

Even the free passwordbox shows the login delay, but smaller due to the limit of 25 passwords.

**Comment by ydario** [comment]
I discovered that this issue goes away if I disable my lastpass extension (last one working on os2 is 3.0.1, https://lastpass.com/releases/lp3.0.1.xpi). I have a few hundreds password saved, I don't know if this makes a difference, I will try again later with an empty account.

**Comment by ydario** [comment]
I created an empty account, the issue is still here :-)

and one more thing: when ffox is busy, if I type 'ctrl-esc' and wait for OS/2 termination program dialog, it says

    'program: LastPass Master login'

is the guilty program. is it possible we have hidden PM windows around?

**Comment by aschnellb** [comment]
> is it possible we have hidden PM windows around?

Your question rings a bell for me. In most cases when SeaMonkey or Firefox crash, I see hidden Mozilla windows in the process list. Most of them are cookies confirmation windows. (I have cookies configured to ask me everytime.) That happens here with all Mozilla versions since about 4 years.

**Comment by dmik** [comment]
It seems that ESR31 improves JS performance a lot here. I could successfully use Lastpass 3.9.2 here and also I don't experience any problems with staying on facebook.com for quite a while and even chatting from there. Tried it on ESR24 again and there web content becomes unresponsive quite soon after going to facebook.com but the main window's menu works and I could terminate Firefox it quickly.

I did get a system freeze on facebook with ESR31 after some time but this seems to be unrelated to the original problem Yuri reported — see #105 (and #106) for details.

I will leave it open until I give Yuri a test build of ESR31 to try.

**Comment by dmik** [comment]
@ydario so can we close it with your ESR31 experience?

**Comment by dbanet** [comment]
I think ESR31 doesn't solve this.
It's usually quite performing, but after some time of active usage, and after ~1 GiB of RAM gets allocated (closing even all but one tab doesn't return the memory or original performance back, see #55), I get CPU peaks with FF going unresponsive quite often, especially when I type text (huge sentences/paragraphs on one line) in whatever input field on a web page. I'm suffering from this right now.

**Comment by dmik** [comment]
Are you sure it is not related to #105 and #106?

**Comment by dbanet** [comment]
Well, does it **quit** after some time? I can't imagine ``plugin-container.exe`` starting up for several seconds, giving 100% CPU, then quitting, returning responsiveness to Firefox.

Anyway #105 and #106 appear to be 31ESR-only related (are they?), but I have had this issue with 24ESR and probably 17ESR.

**Comment by dmik** [comment]
Yes, that's what `plugin-container.exe` occasionally does now: starts up, gives 100% CPU load, then exits and all works well afterwards.

No, #106 has been always there. Only #105 is new. This means that if you see `plugin-container.exe` among the running processes when you get 100% CPU pikes (provided that you have `dom.ipc.plugins.enabled` set to `false`, then it's a new issue and most likely unrelated to this one.

**Comment by dbanet** [comment]
Well, I actually cannot see it running at all neither during those peaks, nor while operating normally.

**Comment by dbanet** [comment]
I don't have any native plugins currently installed.

**Comment by dbanet** [comment]
Eh, how the fuck did I read your last message.

I indeed do have ``dom.ipc.plugins.enabled`` set to ``false``, so it's unrelated to #105 and #106.

**Comment by dmik** [comment]
I think that you still read it wrong :) If you have IPC plugins disabled and still have CPU spikes, then, if you notice `plugin-contanier` is running during these spikes, then it's a subject of #105. Otherwise, this must be something else but it's not necessarily related to this defect, #73.

**Comment by dbanet** [comment]
Well yea :), but at least my conclusion is still justified, as I really don't see ``plugin-container.exe`` running during the spikes.

**Comment by dmik** [comment]
How do you check that? It can really start very quickly and then go away.

**Comment by dbanet** [comment]
I have left WatchCat running along with Firefox on the screen with processes sorted alphabetically and the process list scrolled down to the processes with module name starting with ``P``. Then I've started typing into the Github issue comment field making Firefox unresponsive for ~10 seconds. ``plugin-container.exe`` did not appear.

To be sure that the process list is actually updating while everything is unresponsive, I've compiled a small program which calls ``DosSleep(1000)``, then quits, named it ``p.exe`` and made Bourne shell to run it in a loop. So during the CPU peak, when PM user input is blocked, I was able to see ``p.exe`` constantly reappearing in the process list, while ``plugin-container.exe`` never appeared.

**Comment by dbanet** [comment]
I have to remark that if I restart Firefox, it will handle text input correctly without going unresponsive so frequently and so easily, until it allocates almost all of my RAM again.

**Comment by dmik** [comment]
Okay, then your issue is completely different indeed from both #105 and this one and sounds to me more related to #55.

**Comment by ydario** [comment]
The ffox31 test build does no longer show the 100% CPU usage related to lastpass and passwordbox extensions. No issues even with facebook browsing. CPU usage is now comparable to what I can see in windows build, so I'm closing this ticket.

**Comment by dmik** [comment]
Good, thanks.
