### ISSUE TITLE
FF doesn't accept webpages from commandline

### ISSUE THREAD

**Issue by JoopN** [bitwiseworks/mozilla-os2#81]
For some reason FF17 doesn't accept output from other programs. First I thought program error, but with FF6.02 the page is loaded, with FF17 this doesn't work, don't get an error, its just nothing is happening and you can wait until...

**Comment by SilvanScherrer** [comment]
As it seems that the reporter doesn't want to test what we asked him to do I close this ticket. Especially we have not heard of similar problems.
