### ISSUE TITLE
Drag & Drop with Alt

### ISSUE THREAD

**Issue by englehome** [bitwiseworks/mozilla-os2#86]
On SeaMonkey 2.14 build 20140621130907 the drag and drop while holding down the alt key to transfer the contents of a file into SeaMonkey is not working.

**Comment by aschnellb** [comment]
Ctrl+MB2drag works for me. I was not aware that aware that Alt+MB2drag previously had any function.

**Comment by dryeo** [comment]
On 07/19/15 04:15 PM, aschnellb wrote:
> Ctrl+MB2drag works for me. I was not aware that aware that Alt+MB2drag
> previously had any function.

Alt+MB2 drag picks up the file (same as right clicking and choosing 
"pickup" from the context menu). I don't think any Mozilla app ever 
worked with the drop part and testing with sm 1.19 doesn't work.
Possibly using Rich's dragtext or other WPS extension might modify things.
Bug is off topic here anyways and if not repeatable with up to date 
Firefox, should be closed.

**Comment by SilvanScherrer** [comment]
No updates since long and as Dave suggested to close it I do so now. If someone thinks that's wrong, please reopen with a explanation.
