### ISSUE TITLE
Crash while watching Youtube video

### ISSUE THREAD

**Issue by michaelsnyder** [bitwiseworks/mozilla-os2#88]
Firefox crashed when youtube video finished playing.  http://www.youtube.com/watch_popup?v=SNPJMk2fgJU

Trap and dump files available on request.  msnyder one at cfl dot rr dot com

**Comment by wztest** [comment]
You might want to tell what build of firefox you are using and if the flash plugin is enabled or if the browser plays the video itself using html5 webm.

**Comment by michaelsnyder** [comment]
Thank you.  I'm using Firefox 24.8.1 beta 3 with flash plugin 11.5 r502 to play that video.

**Comment by michaelsnyder** [comment]
Just trying to answer the question, not to close the issue.

**Comment by dmik** [comment]
Thanks for the report. How stable is the crash? Each time on this video?

Also, please paste your .trp file to e.g. http://pastebin.com and publish a link in the comment. We will see if dump files are necessary.

**Comment by michaelsnyder** [comment]
I deleted my link to the video, so I can't test it.  I was just so pleased
to see that you had fixed the exceptq problem and I actually got a trap
file that I had to post the bug. :-)  Unfortunately, I've zipped the trap
file and the two dump files that seemed to be contemporaneous to it and
deleted the original separate files.  Do you not want the zip?

**Comment by dmik** [comment]
I see. You may upload the ZIP somewhere but I'd prefer you to unzip it and paste the .TRP contents to pastebin so that everybody could see it online.
