### ISSUE TITLE
Firefox 24.8.1 beta 3 does not draw window controls for windows raised from web console

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/mozilla-os2#90]
Lousy subject, but it pretty well sums it up. Start FF. Ctrl-Shift-K to open the web console. Reload the page. Click on a GET link in the console.

A window is raised showing the content of the GET, however, there are no window controls at the top of the window. It is not movable, and cannot be minimized, maximized, or closed by any "normal" means (including keyboard; in fact, Alt-F7 allows dragging the main FF window around, while the popup window is pushed to the bottom of the screen).

The only way to close the popup (or popups, as opening more windows just stacks them; the z-order is visible) is to close the web console (or close FF).

This behavior is present whether the web console is docked or undocked.

SeaMonkey does not suffer from this affliction, obviously, due to the difference in the console architecture.

**Comment by LewisR** [comment]
Confirmed that this is still present in 31.8b5.

**Comment by SilvanScherrer** [comment]
what about 38?

**Comment by SilvanScherrer** [comment]
I can reproduce it in 38.2.

**Comment by dmik** [comment]
Still the same with the latest 38.6 test build with tab behavior (#125) fixed. This must be something else. In Firefox v46 under OS X it just opens a new pane in the Network tab of the web console. I believe this has something to do with widget parenting. Something has changed and the OS/2 code doesn't follow it. Might be not that easy to fix (a lot of "reverse engineering" is necessary).

**Comment by SilvanScherrer** [comment]
I just tried it in Firefox 45, but it seems to behave right now. Could anyone else also try?

**Comment by dmik** [comment]
Just checked, all is fine now in FF45.
