### ISSUE TITLE
Builtin object tokens missing from 24.8.1

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/mozilla-os2#91]
I'm still trying to figure this out, but opening https://www.mantisbt.org under FF (or the related SM build) yields a security warning about the issuer not being trusted (the issuer is StartCom, Ltd). Looking more closely, the intermediate server CA(s) is/are missing from the chain, and these should be builtin tokens (StartCom's validity goes back to 2006, and the intermediate was issued in 2007). These are missing when viewing the certificate chain under FF. This issue is not present in earlier builds (10.x.x). I haven't tested earlier 17.x.x or 24.x.x builds. Did we lose something along the way?

Also, do we have a recent build of mozilla-nss-tools available anywhere (certutil is handy)?

**Comment by dryeo** [comment]
On 01/16/15 12:29 PM, Lewis Rosenthal wrote:
> I'm still trying to figure this out, but opening
> https://www.mantisbt.org under FF (or the related SM build) yields a
> security warning about the issuer not being trusted (the issuer is
> StartCom, Ltd).

Opens fine here with both SM and TB (Thunderbrowse). Did you try with a 
fresh profile?

**Comment by LewisR** [comment]
Thanks, Dave. I reset the profile I was using in FF. Same result. I then created a new profile. Same result. Note that SM was using a completely fresh profile when I tested. Safe mode makes no difference, either (not that I would expect a difference after testing fresh profiles). It looks like the CAs from the Software Security Device are not showing up. Ugh... That's it.

Only the top three StartCom CAs are built in. All the intermediates are software security device. I'd never visited MantisBT.org in these profiles, and never accepted the intermediate CAs. I just tested a fresh profile under FF 34.0.5 on openSUSE; same issue. Looks like I should complain to Mozilla about not including these!

Sorry for the noise!!

**Comment by dryeo** [comment]
It would be nice to get another opinion, perhaps they're serving up 
different certificates to foreigners? I did try Qupzilla which 
complained and also tried FF which also worked fine.
Note that newer builds have had the certificates handling changed quite 
a bit in the interest of security.

**Comment by LewisR** [comment]
Apparently, I'm not the only one with this issue, and it's not a break in our port:

https://support.mozilla.org/en-US/questions/984505

I agree with the (intelligent) comments on the above-referenced page that StartCom's servers should provide the intermediate CAs, and apparently, they don't.

More on this may be found in the Mozilla wiki:

https://wiki.mozilla.org/CA:Recommended_Practices

and unfortunately, StartSSL (StartCom, Ltd) is offline for maintenance over the weekend (perhaps this was the issue earlier? I didn't check the time difference), so I can't even access their FAQ, though a quick web search for problems with StartCom intermediate CAs comes up with a bunch of hits.

It's the fault of the mantisbt.org server configuration:

https://www.ssllabs.com/ssltest/analyze.html?d=mantisbt.org

(Note the incomplete certificate chain.) I should ahve checked this, first. (BTW, my server gets an A+ at SSL Labs...jus' sayin'...) ;-)
