### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by an64** [bitwiseworks/mozilla-os2#95]
When i try  switch to the fullscreen it comes to completely mess
Example link http://www.w3schools.com/html/html5_video.asp or any other html5 player / game with fullscreen ability

**Comment by guzzi-g5** [comment]
I just tested that link, works fine here in full screen. Video driver is SNAP.

**Comment by an64** [comment]
Hmm, Panorama 1280x1024

**Comment by DavidMcKenna** [comment]
Works for me too - Panorama and Dave's latest SeaMonkey.

**Comment by dmik** [comment]
Most likely, it's a Panorama problem. Please try a different driver as a test.

**Comment by dmik** [comment]
Closing due to no feedback. In FF45 fullscreen works well.
