### ISSUE TITLE
idl files with DOS line endings

### ISSUE THREAD

**Issue by abwillis** [bitwiseworks/mozilla-os2#96]
Building FireFox I hit a build break it took me a while to figure out  It said a comment in an IDL file was not recognized.  I finally found https://community.activestate.com/node/9504  and after running dos2unix it built until the next idl file.  I then ran a for loop and converted them all.

**Comment by dryeo** [comment]
On 03/14/15 04:13 PM, abwillis wrote:
> Building FireFox I hit a build break it took me a while to figure out It
> said a comment in an IDL file was not recognized. I finally found
> https://community.activestate.com/node/9504 and after running dos2unix
> it built until the next idl file. I then ran a for loop and converted
> them all.
>

This may be due to how your git is configured as checking a bunch of 
random idl files here show *nix type line endings.
Dave

**Comment by StevenLevine** [comment]
@abwillis check your .gitconfig setting for core.autocrlf.  For my
purposes autocrlf=false seems to work best.

**Comment by dryeo** [comment]
Mine is set to
[core]
         autocrlf = input
and has worked well for me. I installed git a long time back and can't 
remember if, why and when I set the above, perhaps Mozilla or the 
YUM/RPM project should come with a minimal .gitconfig or yum/rpm should 
launch a script to set things up. Come to think of it I haven't noticed 
any yum/rpm install doing any setup

**Comment by StevenLevine** [comment]
>Mine is set to
>[core]
>         autocrlf = input

IIRC, the downside of this setting is that it strips CR/LFs that should be
there.  For example this will breaks Classic REXX code with our git build,
because, by default, it acts more like a linux build than a windows build.

**Comment by dryeo** [comment]
I haven't had any problems with the REXX script in security/nss/cmd 
unlike with mercurial and CVS where I often had to fix the line endings.
I believe it just uses the line endings as set upstream.

**Comment by abwillis** [comment]
StevenLevine wrote:
> @abwillis check your .gitconfig setting for core.autocrlf.  For my
> purposes autocrlf=false seems to work best.
>
Indeed, yum seems to install it with true, changed it to false.

**Comment by abwillis** [comment]
For the record:
.idl
.xml
.css
.js
.inc

I believe these were all the file types I had to convert in case anyone else runs into it.
I am using 4os2:
for /r %x in (*.idl) do dos2unix %x
changing idl to the appropriate type of course.
Unless it is thought that this needs to be left opened for some reason, I'd say it can be closed.  I just wanted to document the filetypes in case anyone else ran into the issue and came across this.

**Comment by dmik** [comment]
@abwillis can you point to a particular IDL file with DOS line endings? Here all IDL files have Unix line endings and I didn't do anything special to these files or to git (I use the RPM version 2.0.0-2 here) so git defaults are used WRT CRLF.

**Comment by SilvanScherrer** [comment]
@abwillis Andy could you please reply on the questions?

**Comment by abwillis** [comment]
I do not remember which all I saw for certain but they were all that way due to the autocrlf=true.  I think this bug can be closed as it is a GIT issue that might ought to be documented but does not seem to be a problem in the actual repository.

**Comment by dmik** [comment]
Okay.
