### ISSUE TITLE
Opening a certain page causes great memory troubles

### ISSUE THREAD

**Issue by dbanet** [bitwiseworks/mozilla-os2#99]
http://habrahabr.ru/post/254759/

I didn't test a lot, neither on another OS/2 machines, nor on another platforms.
Opening the above URL makes FF consume terrible (around a GiB?) amount of memory due to unknown reason (maybe because the GIFs? I really didn't investigate). Scroll down to the animated black and white pictures.

I don't know whether is this normal (there is a possibility FF behaves the same on another platforms, so this is not the drawback of the port), but it can nevertheless be used to test #55, as the above page makes FF rapidly allocate big amount of memory, which is **not freed upon the page's closing**.

**Comment by guzzi-g5** [comment]
I can confirm this. Opening the page and scrolling down will eat all available shared memory, FF crashed and memory was released again. Repeatable. Exceptq .trp on request. dll's marked to load code high. Dooble does not crash, but shared memory gets eaten too. Qupzilla loads the page and does not use any extra shared memory while scrolling. Did not check general memory usage.

**Comment by herwigb** [comment]
This mighty be the same issue as #111.

**Comment by dmik** [comment]
This actually belongs to #55. I will transfer your comments there and closing this one.
